### ISSUE TITLE
Very invalid type Rec ***Rec

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#100]
``src/encoding/gob/codec_test.go``
```go
func TestBadRecursiveType(t *testing.T) {
	type Rec ***Rec // WHAT IS THIS ?!
	var rec Rec
	b := new(bytes.Buffer)
	err := NewEncoder(b).Encode(&rec)
	if err == nil {
		t.Error("expected error; got none")
	} else if !strings.Contains(err.Error(), "recursive") {
		t.Error("expected recursive type error; got", err)
	}
	// Can't test decode easily because we can't encode one, so we can't pass one to a Decoder.
}
```
It compiles Go code:
```go
type Rec ***Rec
```
to Haxe code: 
```haxe
@:named typedef Rec_testBadRecursiveType_0 = Rec_testBadRecursiveType_0;
```

Biggest issue I see is that I can't find any other type ``Rec`` in the package, perhaps this is supposed to error for the compiler?

**Comment by elliott5** [comment]
So a `type` which is a pointer to a pointer to a pointer to that same `type` is valid Go ... although not at all useful, and perhaps even a logical impossibility!

The interesting part above, is how `err := NewEncoder(b).Encode(&rec)` returns an error to declare it `recursive` at runtime ... presumably by using the `reflect` package.

**Comment by PXshadow** [comment]
> So a `type` which is a pointer to a pointer to a pointer to that same `type` is valid Go ... although not at all useful, and perhaps even a logical impossibility!
> 
> The interesting part above, is how `err := NewEncoder(b).Encode(&rec)` returns an error to declare it `recursive` at runtime ... presumably by using the `reflect` package.

The logical impossibility part is driving me a little mad 😅 , So... how would you advise we proceed @elliott5 ?

**Comment by elliott5** [comment]
If you declare a Go `type` inside a function, its scope is local to that function - so any `Rec` type outside of `TestBadRecursiveType()` could not refer to a `type` declared within it.

There is nothing to do here except to carry on with running Go's tests...

The key problem I can see is that the Haxe 
```
@:named typedef Rec_testBadRecursiveType_0 = Rec_testBadRecursiveType_0;
```
may not adequately model the Go
```
type Rec ***Rec
```
as the three levels of indirection don't seem to be modelled.

If `reflect` attempts to dereference the type, how will it know how many pointers-to there are?

I was expecting something more like:
```
@:named typedef Rec_testBadRecursiveType_0 = pointer_to(pointer_to(pointer_to(Rec_testBadRecursiveType_0)));
```
 Where the `pointer_to` wrapper is mostly there just to allow `reflect` to function properly.

**Comment by elliott5** [comment]
`reflect` needs Go type information at runtime in order to work. 
`go2hx` must decide how to model the storage of that Go type information. 
But since a Go type is an interface definition - https://pkg.go.dev/reflect#Type - there are many options for achieving this, not just the "wrapper" approach I described above.

**Comment by elliott5** [comment]
Haxe (metadata)[https://haxe.org/manual/lf-metadata.html] is a candidate method of storing the Go type information.

**Comment by PXshadow** [comment]
> Haxe [metadata](https://haxe.org/manual/lf-metadata.html) is a candidate method of storing the Go type information.

At the moment I get the Go type information from the compile type info using macros, however pointer info is not accessible yet for non basic types.

Perhaps I can make a new typedef called ``PointerAlias<T>`` and simply have it be:
```haxe
typedef PointerAlias<T> = T;
```
That way there is no runtime performance hit but the macros at compile time know that the type is a pointer for reflection type info?

I could also have it so every time Go.toInterface is called I have go2hx pass the amount of pointer wraps the type has. This seems to be a better approach for Haxe developers as they don't need to understand that the typedef generic everywhere is only for the compiler for reflect data and is merely noise unless you want to retrieve reflect type info too from reflect.

**Comment by PXshadow** [comment]
Yes indeed I have the ``Go.toInterface`` that does that, looking now at the implementation the only issue counting the alias approach is I wouldn't count it inside of struct fields, perhaps I should use the ``PointerAlias`` approach for struct fields?

**Comment by elliott5** [comment]
Certainly consistency is generally best, special cases usually cause problems at some point.

Remember that `Go.toInterface` must work for every addressable Go location and must pass all the information required to answer all of the (relevant) methods of the `reflect.Type` interface definition.
