### ISSUE TITLE
Documentation efforts

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#102]
I think the wiki pages should be removed and the content moved to the go2hx github site.
The reasoning is the wiki is obscure in terms of looking through the project, having the documentation be on the website makes it more seamless, and also more friendly on mobile.

Nice looking graphs and charts are huge QOL features and should be prioritized more, charts/graphs could include:
* passing std pkgs with per target check results
* go2hx per target to go native comparisons
* supported library graphs with per target performance test passing and binary size compared to go native as well
* go2hx compile speed comparisons to native go

Another thing is branding and nice looking pictures for both documentation/blogs. Well developed pictures capture the mind's imagination and therefore should have resources dedicated to them.

The content delivery stream should be as follows: Twice a month goal, Once a month minimum, github releases with a minimal and polished changelog -> link to a corresponding go2hx blog post showing off the new features/bug fixes in practice -> the info from the blog post should then be cut up and included into the go2hx documentation boat.

Each new version should be valuable enough both from a new shiny utility aspect but also as content to spread effortlessly through word of mouth for devs that would be interested in this compiler.

Lots of work should be done on the documentation part to make the initial impression and subsequent views enjoyable to look through, highly valuable from an information standpoint and easy to navigate and look through all of the documentation with ease.

The work for this on my part should be phased in as more std pkgs publicly pass test compliance on multiple targets.

**Comment by elliott5** [comment]
My advice is to concentrate on documentation that can be auto-generated, especially graphs (as you suggest).

Keeping documentation up-to-date is very difficult long-term, which is why sensible solutions, from both Haxe and Go, revolve around surfacing the code comments as documentation.

**Comment by PXshadow** [comment]
Thank you for the great advice @elliott5 !
Plugging into the go docs and auto generating the standard library would be superb for working with the generated code, even if the go doc changes would be minor from the go version to the Haxe version keeping them precise with Haxe specific info would be a real benefit. Maybe performance info if possible could also be included into the go2hx generated go docs.
For example how in the go docs you can set the architecture:
<img width="277" alt="Screen Shot 2022-05-04 at 14 50 20" src="https://user-images.githubusercontent.com/9813078/166684677-6645dbd6-1483-46cc-b07a-b6e0e6ceed3b.png">
The same could be done for the go2hx version but for the supported go2hx targets such as Java,C++,C#,Hashlink/C.

And for example if you looked at math.Abs and it has a performance test for the function it would say: 80% avg Go test speed.

Let me know what you think @elliott5 :)

**Comment by elliott5** [comment]
What version of a Go package to build is determined by both "build tags" and "file suffixes" ( see https://dave.cheney.net/2013/10/12/how-to-use-conditional-compilation-with-the-go-build-tool ), I'm not sure how `go2hx` handles these at the moment.

`go2hx` will probably need to choose one of these Go targets as the basis of all of its code generation, most likely the one that best fits with the Haxe `System API` - linux?    

As far as generating Haxe documentation for `go2hx` transpiled code is concerned... 

- Using a modified version of [`godoc`](https://go.dev/blog/godoc) with added code to convert the names from Go to Haxe format and change to `go2hx` calling conventions would be possible, but probably not the best way forward. 

- I think it would be easier for Haxe developers if `go2hx` used the familiar format of [`dox`](https://github.com/HaxeFoundation/dox) to generate its documentation. It would also be more likely to be accurate and require less maintenance. To achieve this, `go2hx` would need to include comments from the Go code into the Haxe output in the format required by `dox`.

**Comment by PXshadow** [comment]
@elliott5 yeah you're right it would be preferable to use [dox](https://github.com/HaxeFoundation/dox) I'd need to send in some pull requests to support features such as images and additional special comments for performance stats.

The go target I think is best to use for code generation purposes is wasm/js because it doesn't have any assembly code.

The current build tags go2hx uses are these:
```go
BuildFlags: []string{"-tags", "netgo,purego,math_big_pure_go,compiler_bootstrap"}, // build tags
```
and config env vars:
```go
cfg.Env = append(os.Environ(), "GOOS=js", "GOARCH=wasm", "CGO_ENABLED=0")
```

**Comment by elliott5** [comment]
Yes @PXshadow the wasm/js target is good because it does not have any assembly code to deal with. But it is bad because it does not have any file (or network) IO either, with dummy functions where they should be. Work will be required to overload these as the project develops, if file (or network) access is required later. However, I don't think that fulsome IO is required for the project to deliver a usable Haxe library generation service in the first instance.

**Comment by elliott5** [comment]
I agree @PXshadow, no Go target OS easily maps to the Haxe `System API`.

**Comment by PXshadow** [comment]
Documentation efforts are well underway and all of the tasks except ones to do with benchmarking are now being covered by the website.
