### ISSUE TITLE
Get the reflect tests working first, using Go's own reflect code

### ISSUE THREAD

**Issue by elliott5** [go2hx/go2hx#11]
@PXshadow wrote in an e-mail to @elliott5:
"...from what I understand now, I think it would be better to get the reflect tests working first and instead of handwriting the go's std reflect or go2hx needing it's own modified go repo, go2hx can transpile the package and then inject in the functions that use `//:go:noescape` for instance in tardisgo's modified go, you do this [here](https://github.com/tardisgo/tardisgo/blob/master/goroot/haxe/go1.4/src/reflect/value_haxe.go#L2971-L2980). This idea may also be applicable to speed up, finishing the go standard library as before my thought was that if any package used `syscall` or `internal` it would need to be hand written in Haxe however this could make it only necessary to write the functions in the package that use syscall or internal."

This seems a good idea, but in addition to rewriting the `syscall` and `internal` functions, would also require hx2go to create all of the data-structures around Go type information (routinely created by the Go compiler) that the `reflect` code expects. ["These data structures are known to the compiler..."](https://github.com/golang/go/blob/master/src/reflect/type.go#L225)

Further investigation is required, looking both at how GopherJS and TinyGo handle this issue, and also at how TardisGo did.

**Comment by elliott5** [comment]
TinyGo have written their own [cut-down `reflect` package](https://github.com/tinygo-org/tinygo/tree/release/src/reflect).

**Comment by PXshadow** [comment]
I was just reading this today, This is a great example to shoot for, I'll work on mimicking this and also pulling your reflect prototype at the same time.

**Comment by elliott5** [comment]
I think it might be better to entirely implement `reflect` in Haxe.

If every go2hx Go `type` -> Haxe `Class` implemented (key parts of) the [`reflect.Value`](https://golang.org/pkg/reflect/#Value) methods interface, then the type information could be written as the AST is generated from the type definition, rather than being centralised as it is by the Go compiler.  

Then, to go alongside this, key parts of the TinyGo `reflect` package would need to be re-written in Haxe.

**Comment by PXshadow** [comment]
Got append working again, this time I spent time looking over how golang does deep equal, and gophersjs. The only places I really skipped corners was for the Pointer (value checking not an adress) and not using Reflect's Type and Value system witch I will add later.

Let me know if you spot anything @elliott5 

https://gist.github.com/PXshadow/66fcfcce92dc15ac7fb354ff309e526a

**Comment by elliott5** [comment]
You have acknowledged the two key areas still to emulate for Go - pointers and reflection - so I'll not comment on those.
 
I think the use of Haxe `Any` for Go `interface{}` is good practice.

I like the `localTypeName_containingFunctionName` naming convention, and I think the code generated for `T_verifyStruct` is superb (and will feed well into the pointer and reflection work still to be done).

I am learning a great deal by reading your Haxe macros... they certainly make the generated code more readable.

On the subject of readability, would it be possible to put the Go code in comments above the generated Haxe code?

Although some of the generated code seems to be out-of-order... 
In the Go code, the declarations of types `T1` and `T2` come just before `func verifyType()` where they are used. Yet in the Haxe they appear much earlier in the code, after the constant declarations. Why?

This is promising work, keep going, you are on the right track.

**Comment by PXshadow** [comment]
> I think the use of Haxe Any for Go interface{} is good practice.


Fantastic! I got the chance to read more about Go interfaces and Haxe's Any data type defiently seems more accurate.

> I like the localTypeName_containingFunctionName naming convention, and I think the code generated for T_verifyStruct is superb (and will feed well into the pointer and reflection work still to be done).

This is great to hear, In the future I want to have a smarter naming system as currently there can still be name conflicts, but this should solve most cases.

> On the subject of readability, would it be possible to put the Go code in comments above the generated Haxe code?

This took some engineering however it seems to be working pretty well so I'll push on the results to you.

> Although some of the generated code seems to be out-of-order...
In the Go code, the declarations of types T1 and T2 come just before func verifyType() where they are used. Yet in the Haxe they appear much earlier in the code, after the constant declarations. Why?

The typer types all of the types and variables first and then runs the functions, it's also the standard convention that Haxe code is written, however if you think it makes sense to keep the order, I can write a reorder system for it.

Thank you @elliott5 for the kind words, hopefully these changes help for code inspections witch I am extremly grateful you are doing. Here is the new latest: 
https://gist.github.com/PXshadow/fbe35e1c0f1f22f96d6ffc6d040527b2

**Comment by elliott5** [comment]
Thank you @PXshadow , having the original Go in the comments will make future generated code inspections much easier! 
It may also make eventual go2hx end-users more confident to use the tool.

**Comment by elliott5** [comment]
I'm investigating using the Haxe `rtti` (Run Time Type Information) interface as the primary source of type information for Go, it works for go2hx because it captures the Abstract type names. https://haxe.org/manual/cr-rtti.html

To use this approach, every Go named type / Haxe class will need to be prefaced by `@:rtti`. 

Also, in order to use `@:rtti` every anonymous structure will need to become a very simple Haxe class too (with an auto-generated name).

There is some information that Go `reflect` needs that is not in the `rtti` data, but there is a simple way to add this using meta-data. https://haxe.org/manual/lf-metadata.html

If this approach works, it will require very little additional code generation.

**Comment by PXshadow** [comment]
Reflection is completly using a macro approach now so this issue can be closed, @elliott5 I do hope I did not insult you by rewriting a lot of the reflection code, the @:rtti system worked very nicely and only missed a few edge cases that I thought for stability sake would make sense to have a single reflection system. Also I very much feel I am standing on the shoulders of giants, without the work done with ``GT_enum`` and the seralizer parsing system which built the entire foundation for Reflection.
