### ISSUE TITLE
Go strings initialising []byte constants do not use escape sequences - blocking the regexp package

### ISSUE THREAD

**Issue by elliott5** [go2hx/go2hx#110]
This problem identified by testing https://gobyexample.com/regular-expressions.

The Go library code at https://cs.opensource.google/go/go/+/refs/tags/go1.18.3:src/regexp/regexp.go;l=718
```
     for _, b := range []byte(`\.+*?()|[]{}^$`) {
```
is transpiled into Haxe by go2hx as
```
     for (_b in (("\.+*?()|[]{}^$" : Slice<GoByte>))) {
```
this in turn generates the Haxe compiler error:
```
     Invalid escape sequence \.
```

Although I cannot find it in the Go spec, it seems from this library example that a []byte initiation string cannot contain utf-8 encoding, so must be read on a byte-by-byte basis.

There are a number of ways to resolve this issue:
1. add Haxe escape characters to make every character correspond to a byte,
2. put every character in the string into the "\xNN" format (my personal favourite), or
3. initialise the  Slice<GoByte> with a set of integers.

**Comment by PXshadow** [comment]
If I compile that code in isolation I get the correct result:

```haxe
for (_0 => _b in (("\\.+*?()|[]{}^$" : Slice<GoByte>))) {
```

However when I run the regex gobyexample I get the same issue, so something is messing up the cache for generation I will investigate further.

**Comment by PXshadow** [comment]
Issue was the stdgo version of the package regexp had not been generated in a while and got skipped by having it be excluded from the excluded.json.

**Comment by elliott5** [comment]
Although testing of https://gobyexample.com/regular-expressions shows many other compilation errors, this issue is fixed.
