### ISSUE TITLE
interp target initialises variables to null

### ISSUE THREAD

**Issue by elliott5** [go2hx/go2hx#111]
Discovered testing https://gobyexample.com/channels, but applies to other channel tests too.

Channel length not initialised to null for `interp` target, but to zero for `hl` target, at https://github.com/go2hx/go2hx/blob/7b10b54d21b92e153245f70192908d0265771556/stdgo/Chan.hx#L141

Test works correctly for `hl` target, but fails for `interp` target with runtime error:
```
/Users/elliott/Documents/haxe/haxelib/go2hx/git/stdgo/Chan.hx:168: characters 3-11 : Uncaught exception Invalid operation: null + 1
```

My suggestion is to remove `interp` as a valid target for `go2hx`, as it will never be used in production, otherwise solving this and other (?) inconsistencies will be a long-term time-cost that will never be repaid.

**Comment by elliott5** [comment]
...or, alternatively, use the 'interp' target as a way to catch when variables have not been explicitly initialised to zero, which the Go spec says they should be (otherwise they might contain random data).

**Comment by PXshadow** [comment]
@elliott5 I appreciate your honesty, I agree interp is not a production level target, however I think without networking requirements at the moment it's the easiest dynamic sys target to support [nullability](https://haxe.org/manual/types-nullability.html) requirement to be consistent requires all numbers to be initialized with 0, it's best practice in Haxe and should have been done for this.

**Comment by elliott5** [comment]
Testing https://gobyexample.com/channels, and a couple of other channel tests too, now give correct results.
