### ISSUE TITLE
Syscall.hx - GoInt cannot be null

### ISSUE THREAD

**Issue by elliott5** [go2hx/go2hx#117]
/usr/local/lib/haxe/lib/go2hx/git/stdgo/syscall/Syscall.hx:16: characters 27-31 : On static platforms, null can't be used as basic type stdgo.GoInt
/usr/local/lib/haxe/lib/go2hx/git/stdgo/syscall/Syscall.hx:17: characters 25-29 : On static platforms, null can't be used as basic type stdgo.GoInt
/usr/local/lib/haxe/lib/go2hx/git/stdgo/syscall/Syscall.hx:18: characters 27-31 : On static platforms, null can't be used as basic type stdgo.GoInt
/usr/local/lib/haxe/lib/go2hx/git/stdgo/syscall/Syscall.hx:19: characters 26-30 : On static platforms, null can't be used as basic type stdgo.GoInt
/usr/local/lib/haxe/lib/go2hx/git/stdgo/syscall/Syscall.hx:20: characters 27-31 : On static platforms, null can't be used as basic type stdgo.GoInt
/usr/local/lib/haxe/lib/go2hx/git/stdgo/syscall/Syscall.hx:21: characters 25-29 : On static platforms, null can't be used as basic type stdgo.GoInt
/usr/local/lib/haxe/lib/go2hx/git/stdgo/syscall/Syscall.hx:16: characters 27-31 : On static platforms, null can't be used as basic type stdgo.GoInt
/usr/local/lib/haxe/lib/go2hx/git/stdgo/syscall/Syscall.hx:17: characters 25-29 : On static platforms, null can't be used as basic type stdgo.GoInt
/usr/local/lib/haxe/lib/go2hx/git/stdgo/syscall/Syscall.hx:18: characters 27-31 : On static platforms, null can't be used as basic type stdgo.GoInt
/usr/local/lib/haxe/lib/go2hx/git/stdgo/syscall/Syscall.hx:19: characters 26-30 : On static platforms, null can't be used as basic type stdgo.GoInt
/usr/local/lib/haxe/lib/go2hx/git/stdgo/syscall/Syscall.hx:20: characters 27-31 : On static platforms, null can't be used as basic type stdgo.GoInt
/usr/local/lib/haxe/lib/go2hx/git/stdgo/syscall/Syscall.hx:21: characters 25-29 : On static platforms, null can't be used as basic type stdgo.GoInt

**Comment by PXshadow** [comment]
Next Std generation commit should fix this.

**Comment by PXshadow** [comment]
Is fixed now, changed invalid type to be pointer rather then ref so null as default should not cause this error.
