### ISSUE TITLE
internal go type bug for signature

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#118]
``rnd/main.go``
```go
package main

func main() {
	var x X
	x.t()
}

type X int

func (X) t() {
}
```

```sh
go run . ./rnd .
```

Inside of check.json:
```json
{
      "hash": 0,
      "id": "Signature",
      "params": null,
      "recv": null,
      "results": null,
      "typeParams": [],
      "variadic": false
}
```

The fields stop being null if an arg is added to the t function.

Can you try to replicate this @elliott5 it would be helpful.

**Comment by elliott5** [comment]
I have replicated `check.json` for the above code.

`typeList/hash/0` is an empty function call signature representing `func (?) ?()`.

`typeList/hash/1` representing  `type X ?`  references `typeList/hash/0` at `methods/{ index/0 | name/"t" | type/hash/0}` to document the type of the method `t`.

Which looks correct to me.

**Comment by PXshadow** [comment]
@elliott5 Well done, now how do we move forward on this, should you or I try and look into the internals and fix it, or submit an issue to go/tools with a minimal test case?

I'd like to go ahead and fix it myself but at the same time I'm quite aware how big of a rabbit hole it'd be. So I'll take your advise, on the next steps.

**Comment by elliott5** [comment]
Sorry @PXshadow, I'm not sure what you are expecting to see in this JSON other than `null` entries.

I think the only reason there is a `[]` in the `typeParams` entry is because your code puts it there at https://github.com/go2hx/go2hx/blob/acb31791c5f4143df432cec72f95e5661aff2bf6/export.go#L852

`null` is a perfectly valid entry for an empty Go `interface{}`.

Am I missing some additional piece of knowledge?

**Comment by PXshadow** [comment]
@elliott5 ah sorry should've been more clear, I think it's a bug that recv is null not TypeParams/results/args etc.

If I add an argument into the function like so:
```go
package main

func main() {
	var x X
	x.t("")
}

type X int

func (X) t(string) {
}
```

I get this result:
```json
{
      "hash": 2,
      "id": "Signature",
      "params": {
        "hash": 3,
        "id": "HashType"
      },
      "recv": {
        "id": "Var",
        "name": "",
        "type": {
          "hash": 1,
          "id": "HashType"
        }
      },
      "results": null,
      "typeParams": [],
      "variadic": false
    }
   ```
   
   As you can see recv is not null but is a varType holding a hashType value exactly as it should be but if you do the example above without a function arg.. recv becomes null, which is incorrect.

**Comment by elliott5** [comment]
Before a bug can be reported (and there could be one), the code needs to be updated to use latest library - `golang.org/x/tools v0.1.12` (`go.mod` file currently specifies `golang.org/x/tools v0.1.8`).

`export.go` does not currently compile on the new version, I got the error:
```
/usr/local/lib/haxe/lib/go2hx/git/export.go:117:80: too many arguments in call to packages.Load
	have (*packages.Config, *types.StdSizes, []string)
	want (*packages.Config, ...string)
```

If after upgrading to the new version of the library the problem persists, it should be reported, and a work round put in place.

The work round is that the `recv` value is either the named type that the method operates on, or a pointer to that named type.

Changing the test code to have a pointer receiver:
```go
func (*X) t() {  // <-- now a pointer to X
```
generates the correct JSON:
```json
      "methods": [
        {
          "index": [
            0
          ],
          "name": "t",
          "recv": {
            "elem": {
              "hash": 1,
              "id": "HashType"
            },
            "id": "Pointer"
          },
          "type": {
            "hash": 0,
            "id": "HashType"
          }
        }
      ],
```

So the code work-round is to assume that a `null` `recv` value means that the named type should be used as the target, not a pointer to it.

**Comment by PXshadow** [comment]
@elliott5 Updated to the latest version.

At the bottom of the ``go.mod`` This line:
```
replace golang.org/x/tools => ./tools
```
Is used to replace tools with the fork of tools found at https://github.com/go2hx/tools/
Just in case I'll update the ``go.mod``

Anyways the bug is still occurring.

**Comment by elliott5** [comment]
Because of the version incompatibility I mentioned earlier in the thread, I don't understand how `go4hx` is still compiling:

https://github.com/go2hx/go2hx/blob/e2fe642c6ed358fdce22903782a94a12d9b38ab2/export.go#L117

is incompatible with

```go
func Load(cfg *Config, patterns ...string) ([]*Package, error)
```
https://pkg.go.dev/golang.org/x/tools@v0.1.12/go/packages#Load

The Go compiler should complain about the extra parameter.

**Comment by PXshadow** [comment]
@elliott5 It's using the package inside go2hx's directory named "tools"
https://github.com/go2hx/tools/blob/master/go/packages/packages.go#L252

**Comment by elliott5** [comment]
The version of the go tools library packages in the https://github.com/go2hx/tools repo are not up-to-date. I'm afraid I don't know enough about Git to know why that should be.

I've recompiled `go4hx` with the up-to-date libraries by making the following change on line 117:
```go
initial, err := packages.Load(cfg /* ,&types.StdSizes{WordSize: 4, MaxAlign: 8}*/, args...)
```

The resulting typeList component of the `check.json` was:
```json
  "typeList": [
    {
      "hash": 2,
      "id": "Basic",
      "kind": 2
    },
    {
      "hash": 0,
      "id": "Signature",
      "params": null,
      "recv": null,
      "results": null,
      "typeParams": [],
      "variadic": false
    },
    {
      "hash": 1,
      "id": "Named",
      "methods": [
        {
          "index": [
            0
          ],
          "name": "t",
          "recv": {
            "hash": 1,
            "id": "HashType"
          },
          "type": {
            "hash": 0,
            "id": "HashType"
          }
        }
      ],
      "params": [],
      "path": "command-line-arguments.X",
      "underlying": {
        "hash": 2,
        "id": "HashType"
      }
    }
  ]
```

Which is the same as before. 

I've checked, and the `recv` field of the `Signature` is only non-null when there are no parameters, as you reported.

Since this projects progress can't be delayed by Go's bug-fix cycle, a work-around is required.

My suggestion would be, before JSON output, look through all the methods of all the named types:
if the method's "type" has a null "recv" value, set it to the method's "recv" value.

I wrote the following code to insert after line 147 that fixes this example, I've not done further testing:
```go
	// Fix null "recv" in signatures
	for _, v := range data.TypeList {
		if v != nil {
			m := v["methods"]
			if m != nil {
				for _, mm := range m.([]map[string]interface{}) {
					recv := mm["recv"]
					typ := mm["type"]
					if recv != nil && mm != nil {
						sigToCheck := typ.(map[string]interface{})["hash"]

						// now search though all the types to find any missing recv...
						for i, p := range data.TypeList {
							if p != nil {
								if p["id"] != nil && p["id"].(string) == "Signature" {
									if p["hash"].(uint32) == sigToCheck.(uint32) {
										if p["recv"] == nil || len(p["recv"].(map[string]interface{})) == 0 {
											data.TypeList[i]["recv"] = recv
										}
										break
									}
								}
							}
						}
					}
				}
			}
		}
	}
```

**Comment by elliott5** [comment]
Spotted a bug, will rewrite! ;)

**Comment by elliott5** [comment]
Revised, more efficient code:
```go
	// Fix null "recv" in signatures

	// First find candidates that may need to be changed
	candidateSigs := map[uint32]*map[string]interface{}{}
	for i, p := range data.TypeList {
		if p != nil {
			if p["id"] != nil && p["id"].(string) == "Signature" {
				if p["recv"] == nil || len(p["recv"].(map[string]interface{})) == 0 {
					candidateSigs[p["hash"].(uint32)] = &data.TypeList[i]
				}
			}
		}
	}

	// Now look through methods and check against candidates, fixing if found
	fixedMap := map[uint32]bool{}
	for _, v := range data.TypeList {
		if v != nil {
			m := v["methods"]
			if m != nil {
				for _, mm := range m.([]map[string]interface{}) {
					recv := mm["recv"]
					typ := mm["type"]
					if recv != nil && len(recv.(map[string]interface{})) != 0 && typ != nil {
						sigToCheck := typ.(map[string]interface{})["hash"]
						if sigToCheck != nil {
							hash := sigToCheck.(uint32)
							if fixedMap[hash] {
								panic("method signature with nil recv already fixed") // TODO how to handle this?
							}
							if p := candidateSigs[hash]; p != nil {
								(*p)["recv"] = recv // replace recv value
								fixedMap[hash] = true
							}
						}
					}
				}
			}
		}
	}
```

**Comment by elliott5** [comment]
Actually, calling panic() is probably not the right thing to do ... consider the case of the large number of `String()` methods in Go.

I guess it would help to use the code on the standard library to determine how often the problem actually occurs.

**Comment by PXshadow** [comment]
This is a stellar and thorough job well done. I'm fine with leaving the panic() in case it can be used to quickly catch a case that slips through the cracks. I ran it against the standard library and all of the unit tests and there was no panic.

Thanks for the progress report on gobyexample :) it's nice to hear it steadily rising without actively looking at it.

You can decide what would be best for this issue now with your new code committed. To close it, to spend resources on a go issues etc, I'm happy to put resources where ever you think would be most beneficial.

Thank you for the investment on this and in general, I could not have a better person working on this project with :)

**Comment by elliott5** [comment]
Thank you @PXshadow, you are very kind.

I'm afraid lines 148 to 175 of the revised `export.go` in the commit above need to be removed as they are the (slow and buggy) 1st version of the code.

**Comment by PXshadow** [comment]
@elliott5 Of course.

Unfortunately if I remove line 148 to 175, the unit tests fail on https://github.com/go2hx/go2hx/blob/master/tests/unit/complex1.go I'll look into it more tomorrow.  At quick glance (full speculation mode) I assume it's working because it's correctly modifying ``data.TypeList[i]["recv"]`` for this test correctly.

Let me know what find.

**Comment by elliott5** [comment]
Bad news I'm afraid, for the complex1.go problem you cite, both `reflect.Value` and `reflect.Flag` use the same minimal signature (with an empty recv value).

```
Target signature: &map[hash:0 id:Signature params:map[] recv:map[] results:map[] typeParams:[] variadic:false]
used by method of reflect.flag -> map[index:[5] name:mustBeAssignable recv:map[hash:167 id:HashType] type:map[hash:0 id:HashType]]
used by method of reflect.flag -> map[index:[6] name:mustBeAssignableSlow recv:map[hash:167 id:HashType] type:map[hash:0 id:HashType]]
used by method of reflect.flag -> map[index:[3] name:mustBeExported recv:map[hash:167 id:HashType] type:map[hash:0 id:HashType]]
used by method of reflect.flag -> map[index:[4] name:mustBeExportedSlow recv:map[hash:167 id:HashType] type:map[hash:0 id:HashType]]
used by method of reflect.flag -> map[index:[7] name:panicNotMap recv:map[hash:167 id:HashType] type:map[hash:0 id:HashType]]
used by method of reflect.Value -> map[index:[14] name:Close recv:map[hash:48 id:HashType] type:map[hash:0 id:HashType]]
used by method of reflect.Value -> map[index:[2 5] name:mustBeAssignable recv:map[hash:48 id:HashType] type:map[hash:0 id:HashType]]
used by method of reflect.Value -> map[index:[2 6] name:mustBeAssignableSlow recv:map[hash:48 id:HashType] type:map[hash:0 id:HashType]]
used by method of reflect.Value -> map[index:[2 3] name:mustBeExported recv:map[hash:48 id:HashType] type:map[hash:0 id:HashType]]
used by method of reflect.Value -> map[index:[2 4] name:mustBeExportedSlow recv:map[hash:48 id:HashType] type:map[hash:0 id:HashType]]
used by method of reflect.Value -> map[index:[3] name:panicNotBool recv:map[hash:48 id:HashType] type:map[hash:0 id:HashType]]
used by method of reflect.Value -> map[index:[2 7] name:panicNotMap recv:map[hash:48 id:HashType] type:map[hash:0 id:HashType]]
```

This means that the simplistic "patching" approach I was advocating will not work. So please remove the code I wrote from `export.go`.

The work-round will have to be in the code generation phase:

> When generating code for a call, if the signature type has a nil recv value, use  the method's recv value .


"full speculation mode": this will always be the method's named type rather than a pointer to it.

**Comment by PXshadow** [comment]
@elliott5 Ah no worries, Do you by chance have a code example for this? 
> When generating code for a call, if the signature type has a nil recv value, use the method's recv value .
I have a method for grabbing the recv value from the method type rather then the type it self and that works when it's possible but does not cover every case. I guess I could store these methods and try to match them with the equivalent type. I am a little nervous of false postive matching I'll try to see if there's a way around that.

**Comment by PXshadow** [comment]
Also I believe you've tested this so no speculation required!
> "full speculation mode": this will always be the method's named type rather than a pointer to it.

If recv type is a var type I'll still need to know the type for the var name. So although this axiom is able to cover more cases it doesn't cover all of them correctly.

**Comment by elliott5** [comment]
Looking at the pretty-print AST for the original bug code: https://go.dev/play/p/jnruAukIaF_h

The problem AST is at line 71 onwards:
```
    71  .  .  .  .  .  1: *ast.ExprStmt {
    72  .  .  .  .  .  .  X: *ast.CallExpr {
    73  .  .  .  .  .  .  .  Fun: *ast.SelectorExpr {
    74  .  .  .  .  .  .  .  .  X: *ast.Ident {
    75  .  .  .  .  .  .  .  .  .  NamePos: 6:2
    76  .  .  .  .  .  .  .  .  .  Name: "x"
    77  .  .  .  .  .  .  .  .  .  Obj: *(obj @ 38)
    78  .  .  .  .  .  .  .  .  }
    79  .  .  .  .  .  .  .  .  Sel: *ast.Ident {
    80  .  .  .  .  .  .  .  .  .  NamePos: 6:4
    81  .  .  .  .  .  .  .  .  .  Name: "t"
    82  .  .  .  .  .  .  .  .  }
    83  .  .  .  .  .  .  .  }
    84  .  .  .  .  .  .  .  Lparen: 6:5
    85  .  .  .  .  .  .  .  Ellipsis: -
    86  .  .  .  .  .  .  .  Rparen: 6:6
    87  .  .  .  .  .  .  }
    88  .  .  .  .  .  }
```

`export.go` takes the type of the whole `ast.SelectorExpr` which returns a signature type with `recv=nil ` 
https://github.com/go2hx/go2hx/blob/e0d6790d554cf90365fdbcf7668145eeedcfe948/export.go#L1093

What I wonder is if it would be helpful to also capture the type of the `X: *ast.Ident` node on line 74, since this could then be inspected at code generation time.

Indeed I wonder if it would be helpful for the code generation if `export.go` always captured the types of `X: *ast.Ident` nodes.

**Comment by PXshadow** [comment]
I have removed the type patcher. You could submit a bug report with that test example. 

> What I wonder is if it would be helpful to also capture the type of the X: *ast.Ident node on line 74, since this could then be inspected at code generation time.

*ast.Ident node types should be getting captured, the next step as you said above would be inspecting and combining them at generation time for a recv, I'm not that optimistic about this approach as I've said before I believe this still leaves out the recv variable name (if it has one) and potential other edge cases that will slip through that need to be covered fully.

With the information now, I'm leaning towards us filling a bug report and then also potentially trying to fix the internals in addition.

Curious to know what you think should be the next steps for this issue @elliott5

**Comment by elliott5** [comment]
We will no doubt chat about the issue during our planned conversation on the 16th @PXshadow.

I've also noticed that `export.go` is not capturing one of the Signature type's fields (used since go1.18 for when the receiver is a generic type) - https://pkg.go.dev/go/types#Signature.RecvTypeParams

**Comment by elliott5** [comment]
This problem is something we are doing, because I can find the correct 'recv' value in test code:
https://go.dev/play/p/tfLD_QPpB1y

**Comment by elliott5** [comment]
As above, but finding correct method information (non-nil recv) from the AST:
https://go.dev/play/p/zZUU5Sg_PW6

**Comment by PXshadow** [comment]
It doesn't work for the generic2.go unit test:
https://go.dev/play/p/kkXbnRgilUl

**Comment by elliott5** [comment]
Fixed at https://go.dev/play/p/Wyc9kCUi8zR

**Comment by elliott5** [comment]
After this commit, I see generic2.go passes the tests for  the `hl` and `interp` targets, but not the `jvm` target. 

Significant progress @PXshadow, well done. The JVM is obviously a Haxe target that requires its own way of writing code.

**Comment by PXshadow** [comment]
@elliott5 I agree with that assessment of the JVM target, though it might come down to only a few bugs in the present JVM target generator for that to be the case, which is what I'm optimistic about.
