### ISSUE TITLE
Representation of Go pointers in go2hx

### ISSUE THREAD

**Issue by elliott5** [go2hx/go2hx#12]
All Haxe objects are of course pointers to the start of the contents of the object.

But how to represent pointers to elements within an object, or elements within elements?

I think a Go pointer type rendered in Haxe might contain two values:
1) (a pointer to) the base object
2) an array of indexes(into arrays) or field-names(for structures)

So a pointer to Go element `dingbat[4].foo.bar[26]` would be`{dingbat,[4,"foo","bar",26]}` in Haxe (inside a Class of course).

I fear Haxe reflection may be required to achieve this.

I see @PXshadow may be ahead of me on this, due to his work on [https://github.com/andyli/ptr](https://github.com/andyli/ptr).

**Comment by elliott5** [comment]
Obviously, for targets like C++ that actually have pointers, one could just use pointers.

**Comment by elliott5** [comment]
[GopherJS](https://github.com/gopherjs/gopherjs) must have a similar problem with pointers, but I have been unable to find how they model them yet - TODO.

**Comment by PXshadow** [comment]
I worked on pointers exclusively today, and I'm more confused at the end of the day now then the start. Simulation is really difficult, because it needs to allow field access and and array access on top of that it needs to signal that when pass by copy occurs it's actually a pass by refrence if it is type pointer. Then there is the issue of Go Arrays holding Pointers to structs and in the end alot of "has no field" errors , there is also an issue of destructing needing to extra hunt down types to figure out the function returns. 

So in the end I'm a little bit overwhelemed, love to see the model on how Gopherjs does it. I think I'll work on fool proof method next witch is to just pass out pointer value externally whenever any type of access (map/array/field) occurs.

**Comment by elliott5** [comment]
I'll write a prototype of how it might work in my mind, and post it here as a gist.

**Comment by elliott5** [comment]
The outlined solution in this [gist](https://gist.github.com/elliott5/37dbc5e8f0cb1bf5054780460d63128b) would require many Haxe `interface` and `class` types to be autogenerated... but seems to work so far without any (expensive) reflection.

I'm not sure I've explained everything properly, but have to rush off now, so let me know if more explanation is required!

**Comment by elliott5** [comment]
So as per the gist above:
- Each Go `type` (built-in or user-defined) would require a pointer type to it, modelled as a Haxe `interface` (see `IntPtrIface`, `StringPtrIface `, `UserPtrIface`).
- For a Go `struct`, each field requires it's own Haxe pointer class implementing one of the interfaces above.
- Pointers to nested objects (Go types) can be composed together by using the `interface` description of the pointer as the basis, except for the base object (see `User_pointer`).
- The `UserPtrIface` method `explain()` is just there to make clear how the pointer has been composed.

**Comment by elliott5** [comment]
If you'd prefer not to generate loads of extra Haxe interfaces and classes, it is possible to build on the current reflect-based [Pointer.hx](https://github.com/PXshadow/go2hx/blob/master/stdgo/Pointer.hx) code.

The approach will not be type-safe, so casts to the required types will be needed after values are retrieved from `Pointer.fieldRead(x)` (`Reflect.field(x,y)` returns `Dynamic`) and before `Pointer.fieldWrite(x,y)`. 

The advantage of using `Reflect` is that the the code may be easier to generate.
The disadvantage, at least on compiled targets, is that it is likely to be slower.

**Comment by PXshadow** [comment]
Yeah, I'd prefer not to build on the reflect code to be honest, because it's slower and there's still more headaches with the Pointer system for it that still requires changes. 

I think I might have a decent compromise, so the issue with my first idea of having ptr._value_ always be used for every type of access as described above is I would need the typer to know, every variable type when typing, and that adds an enernmous complexity on top that I am trying at all costs to avoid. I'd also prefer not to auto generate a ton of interfaces and classes but it is a better option then the current. However I think another solution is possible.

When the typing of the PointerType occurs, I can simply check through a list of BasicTypes and then see if the type is an alias of the BasicTypes to use a real Pointer, for all other data types, it could just be a very simple abstract wrapper, that could then be seen by macros when pass by copy comes up.

```haxe
@:forward
abstract PointerWrapper<T>(T) from T to T {}
```

Let me know what you think @elliott5 , and also I extremly apperciate the gist and explanation it was very helpful to wrap my head more around this, don't know what I would do without your exptertise ☺️

**Comment by elliott5** [comment]
Thank you @PXshadow!

An `abstract` cannot implement an `interface`, but it can convert to one by casting.

The following code works in my small-scale prototyping:
```
@:forward
abstract PointerWrapper<T>(T) from T to T {
	@:to
	public function toClass():PointerInterface<T> {
		return new PointerClass<T>(this);
	}
}

// this interface is really what a Pointer is...
interface PointerInterface<T> {
	public function get():T;
	public function set(_:T):Void;
	public function string():String; // explain the path
}

class PointerClass<T> implements PointerInterface<T> {
	public var value:T;

	public function new(v:T) {
		value = v;
	}

	public inline function get():T {
		return value;
	}

	public inline function set(x:T):Void {
		value = x;
	}

	public inline function string():String {
		return "Pointer<" + Type.typeof(value) + ">";
	}
}
```

Then to use the generic code above with the `User` typedef from the gist above:
```
	var dingbat:PointerWrapper<User> = {
		age: 42,
		name: "Fred",
		boss: null,
		colleagues: []
	};
	var dPtr:PointerInterface<User> = dingbat;
```

However... it is important to realise that in the code snippet above, the `User` data in `dPtr` is a copy of `dingbat` not a reference to it. 

To create a variable that could be passed by reference the code would need to be:
```
	var dingbat = new PointerClass<User>( {
		age: 42,
		name: "Fred",
		boss: null,
		colleagues: []
	});
         trace(dingbat.value.name); // direct reference
	var dPtr = dingbat;
         trace(dPtr.get().name); // indirect reference
```

I've got some ideas on how to make field access simpler to generate code for, so I'll come back to you on that...

**Comment by elliott5** [comment]
I've been trying to work out how to use `@:genericBuild` to autogenerate the pointer-to-field classes for much of the day ... but my knowledge if Haxe macros is not up to the task! 

The idea is simple enough - cycle through the fields of each Haxe version of a Go `struct` and generate a pointer class for each...
```
// simple field in this example (rather than indexed or map)

class PointerTo_GoStructName_GoFieldName implements PointerInterface<GoFieldType> {
	var base:PointerInterface<GoStructType>;
	public function new(b:PointerInterface<GoStructType>) {
		base = b;
	}
	public inline function get():GoFieldType {
		return base.get().GoFieldName;
	}
	public inline function set(f:GoFieldType) {
		var r = base.get();
		r.GoFieldName = f;
		base.set(r);
	}
	public inline function string():String {
		return base.string() + ".GoFieldName";
	}
}
```

Still generating the same classes behind the scenes, but with less code visible to the user in Haxe.

Any Haxe macro ideas for how to do this?

**Comment by PXshadow** [comment]
Oh no I'm sorry for getting you to spend much of your day on macro madness, the idea is possible with an auto build macro. I think however there is actually no need to generate a pointer class for each, as the forward metadata on a T type wrapped macro is able have the same functionality as the unwrapped version, and be used as identification when pass by copy occurs. Also all non basic types in Haxe are already refrences, so then the only virtualization for refrences need to occur for basic types and those can be handled with a single PointerData wrapped with an abstract.

I have ran into some peculiarities though that I'm not familar enough with Golang to figure them out, those being double pointer types, if there is any need to ever wrap a slice/map as a pointer, what functionality of the pointers will need to be included when unsafe pointers are eventually supported that could possibly be planned for.

Also extra note: I do think at the moment a system something like getFieldName will be needed but to signify as compile time that this type is actually the underlying type of a pointer, potentially something like _isPointer();  to be able to call when type switching.

Thanks so much for all of the insights, I hope I'm not missing anything.

**Comment by elliott5** [comment]
You have a better understanding of Haxe than me, so I'll wait and see how things develop. 

I tried a very simple example, but could not get it to work see #16.

**Comment by elliott5** [comment]
Yes, Go double pointers (and somewhere no-doubt in a dark corner of the ecosystem even triple-pointers) have their place, and will be difficult to replicate without having pointers within pointers. 

Go Slices (and arguably Maps) are just over-evolved pointers as you say... in Haxe terms they are likely to be classes, and any Haxe class is an `interface{}` in Go terms, having both a pointer to the data and a pointer to the methods.

Go2hx will not be able to implement `unsafe` Go pointers in any sensible way, except maybe for compiled targets, since it relies on reinterpreting a memory layout created as one type as being another type. However go2hx may need to allow `unsafe` pointers, just passing through any pointer value, in order for some of the Go libraries to work.

Likewise Go casting a pointer to a `uintptr` is not going to yield a sensible result, except on a compiled target. I think GopherJS always returns 1 as the `uintptr` value.  

As you say, the real issue with emulating Go pointers revolves round "getFieldName" issues, which you can either do by reflection at runtime, or by pre-building the access paths and letting the Haxe compiler resolve it.

**Comment by elliott5** [comment]
Just to say I really like the idea of the `Pointer.PointerData` class, with two soft functions within it for get/set. 

The functions could certainly be added at the macro phase of compile time as the `Go.pointer` macro seems to do, not sure if they could be added at runtime. 

What I don't understand is how those accessor functions see the underlying object or pointer that they should be acting on. This could be my lack knowledge about Haxe of course...

**Comment by PXshadow** [comment]
Strange I thought I wrote back a comment earlier, either way. 

I have no comprehension of where double/triple pointers would be useful to solve a programming problem, I know it's possible to implement with an extension to the pointer system, figuring the case though should help with building test examples though.

> ...but reflecting on it, the underlying object or pointer is perhaps captured by a closure (in Go terms).
Yes this is exactly the case, a pointer is an abstract closure wrapper system for the underlying type.

> Likewise Go casting a pointer to a uintptr is not going to yield a sensible result, except on a compiled target. I think GopherJS always returns 1 as the uintptr value.

This is a relief to know, as well as the useful idea of just having unsafe pointers operate in a pass through manner, this will be keep helpful with more generation of parts of the standard library I suspect.

> The functions could certainly be added at the macro phase of compile time as the Go.pointer macro seems to do, not sure if they could be added at runtime.

Good to hear you like the system! Yes I think runtime would be possible, from Haxe convention though macros > runtime reflection, but either could work certaintly.

Also feel free if you want to run examples quickly using go2hx, I built an rnd config system for that exact purpose. If you pull the repo, there's an rnd folder, with an rnd.go file, all that's needed is to change that file for a test case you have, and then run ```haxe rnd.hxml```, it will rebuild the transpiler and then transpile the Go code. Then it will run the generated Haxe code and Go source code side by side, which should help if you're interested in trying/creating more examples.

Finally I look forward to building up a fully featured pointer system and having it run through rigid unit tests in the near future.

**Comment by elliott5** [comment]
In the few tests I've done so far, the reflection pointer system works well. The approach has the big advantage of keeping all the generated code in the place where it is used in the AST.

The naming and visibility of Go struct fields is not quite sorted out yet, which has limited my testing, but I'm sure #17 will resolve this in time.

As for double pointers, they are certainly used in the go standard library, for example in the [gob Decoder struct](https://golang.org/src/encoding/gob/decoder.go?s=798:1581#L17).

```
grep -Frl "**" /usr/local/go/src | wc
```
Shows that there are 278 files in the standard library containing double-star, some of which may not be in the context of a pointer of course.

But only 25 standard files have a triple-star in them, again, not all as pointers, but including:
```
		return **((***g)(unsafe.Pointer(tls)))
```
in `/usr/local/go/src/runtime/os_windows.go` ... so *** pointers are very unusual!

**Comment by elliott5** [comment]
#27 shows that a pointer, for comparison purposes, must have a unique address of the item being pointed at, in addition to get/set operations of course. In the first post of this discussion, I set out how this might be achieved.

**Comment by elliott5** [comment]
Also, to aid reflection, it would be helpful if the hx2go pointer also contained the Go type of the data being referenced.

**Comment by PXshadow** [comment]
Sounds good, the system I used ``haxe.macro.Context.signature`` to achieve a unique address, I've never used before and is quite undocumented so there may be faults that I'm unaware of at the moment using it. The same error for #27 can be achieved with struct type pointers as it will use a pointer wrapper, and a signature system is not implemented for it as I think another hidden variable will need to be added for it, that being some type of ``_address__`` I'm interested to know if you have a prefrence for an address system be it a md5/uuid/or a simple number counter @elliott5 .

**Comment by PXshadow** [comment]
> Also, to aid reflection, it would be helpful if the hx2go pointer also contained the Go type of the data being referenced.

I agree, implementation is a little tricky for pointers though on a side note as it's a 2 system one policy, so the standard Pointer type that gets used for basicTypes is quite unrestricted in implementation, where as the PointerWrapper is very restricted as it is only a wrapper and all held data needs to be held in all structure types etc.  I think some more @:to black abstract magic can do the trick though.

**Comment by elliott5** [comment]
The use of `haxe.macro.Context.signature` to provide the address is inspired @PXshadow, even if I don't completely understand it, and so cannot judge if it will always work. But you are clearly working through associated issues ... alongside thinking about how to use yet more Haxe voodoo to also capture the referenced type. Good work!

I don't think it matters what the unique address system is, although faster is better ... for targets with pointers, it could just be a pointer!

**Comment by PXshadow** [comment]
Thanks! Yeah I've defiently learned enough Haxe voodoo for a few lifetimes, Good point on just using a Pointer for targets that have them, I should give the c++ target some time and implement things like Pointers natively for that target, still detirmined to get to the finish line for pointer virtulization before that and soon. The last things for Pointers in general If I'm correct is type switch integration, checked when pass by copy calls occurs to not copy, proper fmt printer, and finally probably some advanced usages that will probably be in ``go/test`` let me know if you think of anything I'm missing.

**Comment by elliott5** [comment]
I've written a simple (and not optimised) pointer simulation class `EPointer` as per my first post in this thread.

You can see it at: https://try.haxe.org/#E8d1AaaF

**Comment by elliott5** [comment]
The HashLink target of the pointer simulation above fails at runtime on the index access, complaining (not unreasonably) about a casting error.

**Comment by PXshadow** [comment]
> I've written a simple (and not optimised) pointer simulation class `EPointer` as per my first post in this thread.
> 
> You can see it at: https://try.haxe.org/#E8d1AaaF
> 
> The best output comes via `Neko`, rather than `JavaScript` ... `HashLink` does not build.

It's an interesting implementation, The offset system with the enum is much cleaner then I could've imagined with reflect, and with no abstracts, I'm very impressed with the implementation without using any magic tricks just solid generation. In the future I'd like to use the offset system for arrays and fields for adresses.

**Comment by PXshadow** [comment]
Pointers are pretty solid from what I understand at the moment. There is a discussion whether to remove PointerWrapper all together, however I think it makes sense to keep it from a Go perspective if someone is reading between the two and does not understand why for certain types Pointers cease to exist, either way make a new issue if anything is astray.
