### ISSUE TITLE
Non linear benchmark when creating large buffers

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#120]
```go
package main

import (
	"bytes"
	"fmt"
	"time"
)

func main() {
	const japanese = "日本語日本語日本語日"
	var b bytes.Buffer
	stamp := time.Now()
	for i := 0; b.Len() < 5_000; i++ {
		if i%100 == 0 {
			b.WriteString(japanese)
		} else {
			b.WriteString("0123456789")
		}
	}
	fmt.Println("elapsed:", time.Now().Sub(stamp).String())
}
```

5k:
* Haxe: elapsed: 8.380918016s
* Go: elapsed: 34.694µs

10k:
* Haxe: elapsed: 33.374898944s
* Go: elapsed: 60.878µs

The issue is very glaring when trying to run utf8 tests as Go has a wait time of less then a second for the init function and go2hx's Haxe code takes 4+ mins at least.

**Comment by elliott5** [comment]
I'm getting similar results:

- go = 20.292µs
- --interp = 3.077111808s
- --hl = 2.906765056s

I'll take a look.

**Comment by elliott5** [comment]
I think the problem is that the go2hx code is making a new allocation every time a slice is added too, rather than adding most new items into the free capacity at the end of the slice.

The key piece of code in the Go library is in `bytes.growSlice` - When making a new buffer, its capacity should be twice that of the old buffer, to avoid too many new allocations.
```go
	c := len(b) + n // ensure enough space for n elements
	if c < 2*cap(b) {
		// The growth rate has historically always been 2x. In the future,
		// we could rely purely on append to determine the growth rate.
		c = 2 * cap(b)
	}
	b2 := append([]byte(nil), make([]byte, c)...)
	copy(b2, b)
```
https://github.com/golang/go/blob/d4ff25ac69c90bb0e6a92aff7650d0bf3d41d29e/src/bytes/buffer.go#L238

However, the code in `Slice.hx` does not use the capacity of the slice other than as a memo field:
```haxe
	public function __setCap__(cap:GoInt):Slice<T> {
		@:privateAccess this._cap = cap.toBasic();
		return this;
	}
```
https://github.com/go2hx/go2hx/blob/6c6a7b8a70ff3fad4bd3e8ce56d7bcfea84dc42a/stdgo/Slice.hx#L93

Like Go, the TARDISgo implementation did use the capacity of the underlying array/Vector as an integral part of the logic for slices. The code can be seen at:
https://github.com/tardisgo/tardisgo/blob/master/haxe/haxeRuntime.go#L1377

**Comment by PXshadow** [comment]
No performance change for latest commit 
5d42496, I'm not sure what is missing for the performance gain.

**Comment by elliott5** [comment]
go2hx itself is not building for me:
```
stdgo/unicode/utf8/Utf8.hx:596: characters 67-102 : Not enough arguments, expected capacity:stdgo.GoInt, args:haxe.Rest<stdgo.GoUInt8>
stdgo/unicode/utf8/Utf8.hx:596: characters 67-102 : Void should be stdgo.Slice<stdgo.GoByte>
stdgo/unicode/utf8/Utf8.hx:737: characters 93-103 : stdgo.Slice<stdgo.GoUInt8> has no field __setCap__
stdgo/unicode/utf8/Utf8.hx:596: characters 67-102 : Not enough arguments, expected capacity:stdgo.GoInt, args:haxe.Rest<stdgo.GoUInt8>
stdgo/unicode/utf8/Utf8.hx:596: characters 67-102 : Void should be stdgo.Slice<stdgo.GoByte>
stdgo/unicode/utf8/Utf8.hx:737: characters 93-103 : stdgo.Slice<stdgo.GoUInt8> has no field __setCap__
src/Main.hx:160: characters 17-35 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module '/usr/local/lib/haxe/lib/go2hx/git/build.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by PXshadow** [comment]
The standard library is not updatimg because utf8 tests is stalling the runner (because of this issue) and failing the build process, I'll make it so tests are temporarily not run for utf8 to fix this.

Sorry about this @elliott5

**Comment by PXshadow** [comment]
@elliott5  You should be able to test now.

**Comment by elliott5** [comment]
--Interp fails:
```
% haxe -lib go2hx -cp golibs -m Main --interp  
Uncaught exception Unexpected value `?g(false), expected int
/usr/local/lib/haxe/lib/go2hx/git/stdgo/GoString.hx:76: characters 4-32 : Called from here
/usr/local/lib/haxe/lib/go2hx/git/stdgo/time/Time.hx:5512: characters 17-69 : Called from here
golibs/Main.hx:25: characters 62-156 : Called from here
```

--hl gives an unexpected result:
```
% haxe -lib go2hx -cp golibs --hl run.hl  -m Main
% hl run.hl
elapsed: 2
```

I'm not clear @PXshadow why it should work for you yet fail for me.

**Comment by PXshadow** [comment]
@elliott5 can you show me the line it fails on for ``GoString``?

**Comment by elliott5** [comment]
Line 76 on my machine is:
```haxe
			bytes.set(i, x[i].toBasic());
```

Whole function is:
```haxe
	@:from static function ofSliceByte(x:Slice<GoByte>):GoString {
		var bytes = haxe.io.Bytes.alloc(x.length.toBasic());
		for (i in 0...bytes.length)
			bytes.set(i, x[i].toBasic());
		return bytes;
	}
```

Since the error is complaining that an int is "`?g(false)`" it suggests that the "i" value in the expression is corrupt.

My guess is that an extra `.toBasic()` is required to give the correct end of the range, and the loop should be:
```haxe
		for (i in 0...bytes.length.toBasic())
			bytes.set(i, x[i].toBasic());
```

**Comment by elliott5** [comment]
The other possibility is that very large `Slice` allocations or incorrect `haxe.ds.Vector.blit` parameters, have over-written the stack, as "i" is stored on the stack.

**Comment by PXshadow** [comment]
@elliott5 you may be right, I wish I could reproduce I've never seen a ``?g(false`` error before, if possible could you try to test on your non m1 mac as well perhaps it's occurring from that. If you can also get an isolated test case that would be great?

**Comment by elliott5** [comment]
I can try it on my old mac tomorrow @PXshadow.

Reading through the code, is it a problem that in `Slice.hx` `SliceData<T>` a number of the functions do not reference `pos` when I would have expected them to:
- `toArray`
- `toVector`
- `underlying`
- `grow`

**Comment by elliott5** [comment]
As for "an exact test case", I'm running the code at the start of this thread.

**Comment by PXshadow** [comment]
> As for "an exact test case", I'm running the code at the start of this thread.

Oh yes of course sorry, I forgot 😅

**Comment by elliott5** [comment]
As requested, terminal transcript from my running the original code on my x86 mac:
```
elliott@Elliotts-MacBook-Pro15-2 issue120 % haxelib remove go2hx
Library go2hx removed

elliott@Elliotts-MacBook-Pro15-2 issue120 % haxelib git go2hx https://github.com/go2hx/go2hx
Installing go2hx from https://github.com/go2hx/go2hx
  Current version is now git
Done

elliott@Elliotts-MacBook-Pro15-2 issue120 % go run main.go
elapsed: 126.282µs

elliott@Elliotts-MacBook-Pro15-2 issue120 % haxelib run go2hx main.go --interp
create compiler instance
listening on local port: 6251
nodejs server started
accepted connection
Generated: golibs//Main.hx - 0.926kb
haxe -lib go2hx -cp golibs -m Main --run Main
Cloning into 'tools'...
Updating files: 100% (2183/2183), done.
Invalid_argument("String.blit / Bytes.blit_string")

elliott@Elliotts-MacBook-Pro15-2 issue120 % haxelib run go2hx main.go --hl run.hl
create compiler instance
listening on local port: 6250
nodejs server started
accepted connection
Generated: golibs//Main.hx - 0.926kb
haxe -lib go2hx -cp golibs --hl run.hl  -m Main
hl run.hl
elapsed: 26
```

To be fair, on the M1 mac I get similar results, with only the --interp code failing:
```
Go:
elapsed: 18.417µs

--interp:
create compiler instance
listening on local port: 6142
nodejs server started
accepted connection
Generated: golibs//Main.hx - 2.081kb
haxe -lib go2hx -cp golibs -m Main --run Main
Uncaught exception Unexpected value `WZ(false), expected int
/usr/local/lib/haxe/lib/go2hx/git/stdgo/GoString.hx:76: characters 4-32 : Called from here
/usr/local/lib/haxe/lib/go2hx/git/stdgo/time/Time.hx:5512: characters 17-69 : Called from here
golibs/Main.hx:25: characters 62-156 : Called from here

--hl:
create compiler instance
listening on local port: 6126
nodejs server started
accepted connection
Generated: golibs//Main.hx - 2.081kb
haxe -lib go2hx -cp golibs --hl run.hl  -m Main
hl run.hl
elapsed: 2
```

Suspicion must fall on --interp use of "bilt".

But it is still very slow...

**Comment by elliott5** [comment]
...one reason it is slow may be:
https://github.com/go2hx/go2hx/blob/c4efb51560e84f20653e8df3741f5083f4758e99/stdgo/Slice.hx#L130

Every time `Slice<T>.__append__(args:Rest<T>):Slice<T>` is called, all of the slice's data is copied!

Go just writes the new contents into the free space of the existing slice, if there is capacity.
If there is not capacity, then it allocates a new underlying array and copies the existing and new content to it.

**Comment by PXshadow** [comment]
@elliott5 Isn't a new copy required each time for append because append copies the slice?

**Comment by elliott5** [comment]
To quote the Go doc for append:
> The append built-in function appends elements to the end of a slice. If it has sufficient capacity, the destination is resliced to accommodate the new elements. If it does not, a new underlying array will be allocated. Append returns the updated slice. It is therefore necessary to store the result of append, often in the variable holding the slice itself.

See https://pkg.go.dev/builtin#append

**Comment by PXshadow** [comment]
@elliott5 I see the issue now thank you! Should only at most have 1 allocation per append, right now it's possible to have 2 and the copy is premature at the top of the append.

**Comment by PXshadow** [comment]
Once utf8 passes this issue should be closed as the init code for utf8 test relies on this benchmark being fast enough to not timeout the test runner.

**Comment by elliott5** [comment]
The speed issue is certainly much improved: µs in Go, ms in (interpreted) Haxe.

The only immediate issue remaining is the difference between Go & Haxe bytes.Buffer capacity figures: 8192 for Go 7292 for Haxe. But perhaps this should be the subject of another issue.

```
Go:
elapsed: 17.625µs cap: 8192

--interp:
create compiler instance
listening on local port: 6234
nodejs server started
accepted connection
Generated: golibs//Main.hx - 1.667kb
haxe -lib go2hx -cp golibs -m Main --run Main
elapsed: 13.950976ms  cap: 7292

--hl:
create compiler instance
listening on local port: 6131
nodejs server started
accepted connection
Generated: golibs//Main.hx - 1.667kb
haxe -lib go2hx -cp golibs --hl run.hl  -m Main
hl run.hl
elapsed: 17.733888ms cap: 7292
```

**Comment by PXshadow** [comment]
@elliott5 yes a new issue for the capacity difference of bytes buffer would be great.

**Comment by elliott5** [comment]
With the C++ target now working, my latest speed test is (some output elided):
```
Go:
elapsed: 19.542µs

--interp:
elapsed: 16.25984ms

--hl:
/usr/local/lib/haxe/std/haxe/Rest.hx:48: character 2 : Don't know how to cast hl.types.ArrayBytes_hl_F32 to hl.types.ArrayDyn

--cpp:
elapsed: 1.085952ms
```

So  go2hx C++ is really very fast compared with --interp and --hl (when it works) ... but not as fast as native Go of course.

I'll open an issue for the --hl compilation failure.

**Comment by elliott5** [comment]
Latest figures from me:
```
Go:
elapsed: 18.209µs

--cpp:
elapsed: 1.074944ms

--interp:
elapsed: 14.83904ms

--hl:
elapsed: 17.761024ms
```

**Comment by PXshadow** [comment]
Nice! I'll close this issue as it's now in the performance optimization realm not bug fixing.

**Comment by PXshadow** [comment]
Testing on latest it's gotten better :,)

```go
package main

import (
	"bytes"
	"fmt"
	"time"
)

func main() {
	const japanese = "日本語日本語日本語日"
	var b bytes.Buffer
	stamp := time.Now()
	for i := 0; b.Len() < 1000_000; i++ {
		if i%100 == 0 {
			b.WriteString(japanese)
		} else {
			b.WriteString("0123456789")
		}
	}
	fmt.Println("elapsed:", time.Now().Sub(stamp).String())
}
```

This is with 1 million

Haxe hl: 3s
Go: 1.68863ms
