### ISSUE TITLE
Errors compiling to the HL/C target (medium term issue)

### ISSUE THREAD

**Issue by elliott5** [go2hx/go2hx#128]
In attempting to see if issue #120 would go faster if compiled, I tried to compile to HL/C, but had errors:
```
% haxe -lib go2hx -cp golibs --hl c/issue120.c  -m Main
Code generated in c/issue120.c automatic native compilation not yet implemented

% cd c

% gcc -O3 -o issue120 -std=c11  issue120.c -I . -I /Users/elliottstoneham/code/haxe/hashlink-1.12/src -lhl -L /usr/local/lib  -arch x86_64
n file included from issue120.c:29:
In file included from ./stdgo/reflect/Value.c:7:
./stdgo/reflect/_Reflect/Reflect_Fields_.h:86:6: error: cannot combine with previous 'int' declaration specifier
        int bool;
            ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/stdbool.h:15:14: note: expanded from macro 'bool'
#define bool _Bool
             ^
In file included from issue120.c:29:
In file included from ./stdgo/reflect/Value.c:7:
./stdgo/reflect/_Reflect/Reflect_Fields_.h:86:2: warning: declaration does not declare anything [-Wmissing-declarations]
        int bool;
        ^~~~~~~~
./stdgo/reflect/_Reflect/Reflect_Fields_.h:87:6: error: duplicate member '_int'
        int _int;
            ^
./stdgo/reflect/_Reflect/Reflect_Fields_.h:60:6: note: previous declaration is here
        int _int;
            ^
./stdgo/reflect/_Reflect/Reflect_Fields_.h:110:6: error: duplicate member '_struct'
        int _struct;
            ^
./stdgo/reflect/_Reflect/Reflect_Fields_.h:83:6: note: previous declaration is here
        int _struct;
            ^
In file included from issue120.c:79:
./stdgo/reflect/_Type.c:450:15: error: expected identifier
                                        r4 = r8->bool;
                                                 ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/stdbool.h:15:14: note: expanded from macro 'bool'
#define bool _Bool
             ^
In file included from issue120.c:79:
./stdgo/reflect/_Type.c:522:15: error: expected identifier
                                        r4 = r8->bool;
                                                 ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/stdbool.h:15:14: note: expanded from macro 'bool'
#define bool _Bool
             ^
In file included from issue120.c:215:
./hl/init.c:103739:7: error: expected identifier
        r63->bool = r9;
             ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/stdbool.h:15:14: note: expanded from macro 'bool'
#define bool _Bool
             ^
1 warning and 6 errors generated.
```

Most of these errors appear to be naming clashes, so will need to be resolved in order to target C in this way.

**Comment by elliott5** [comment]
From the above, it would seem that if you use the name `bool` in your Haxe, HL/C does not alter the name so as not to clash with the C usage.

**Comment by PXshadow** [comment]
@elliott5 Don't know how to run the hl c code but it seems the error is no longer occurring after adding "bool" to the reserved list.

**Comment by elliott5** [comment]
Unfortunately my retesting is currently hitting issue #132

**Comment by elliott5** [comment]
Issue #132 is now resolved, so I tried again to find the pattern to these compilation failures.

In good news, the issues here are not within the go2hx generated code.

Rather they are name clashes from within the hand-written Haxe implementing:
- reflect (`bool` as a field name; `_bool` , `_int`, `_struct` as identifiers)
- syscall/js (`_float`)

**Comment by PXshadow** [comment]
@elliott5 very nice, I just pushed a commit to add these keywords as reserved and rewrite the keywords manually in reflect, hopefully now HL/C will compile the test code.

syscall/js is no longer handwritten but compiled with the extern keyword meaning it strips out all of the function exprs and a few other modifications to stop at that abstraction level. It's especially useful for the patch approach now, as code that references it, can compiles at runtime and throws with the "not yet implemented" message at runtime, allowing sequential patching, of the functions being used.

**Comment by elliott5** [comment]
I can confirm this now works:
```
% ./c/issue120
elapsed: 17.040896ms
```

By comparison, the non compiled version is marginally slower:
```
% hl run.hl
elapsed: 17.988096ms
```

...so HL/C could be added to `go2hx`'s targets!
