### ISSUE TITLE
Typedefs vs Classes

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#13]
A discussion wich typesystem should be used for now (of course in the future it'd be possible to have both options and use the non default one with a flag).

*Here are the features and drawbacks for the two diffrent types*

## Typedef
*  Closer to the Go style
* Function declerations are required to be outside of the datatype, keeping the same style as Go
*  Structual sub-typing allows the same implicit relationship between types that Go has for interfaces.
* No impact on performance for dynamic targets, static targets slower, with optimization on JVM/HL for common cases, worst case however requiring dynamic lookup - https://haxe.org/manual/types-structure-performance.html
* multiple extensions allowed
* No private fields, have to use @:noCompletion meta data to hide private fields from ide auto compleition.

## Class
* No implicit type relationship, needs to be figured out during the typing phase.
* No multiple extensions allowed, need to reduce to one and consolidate types together.
* No performance issues.
* Go style is not kept, requires a new constructor, at least.
* Function declerations can be both within the data type and outside of it.
* Can implement interfaces.
* Allows private fields and potentially less macro usage, with the draw back of more AST typing, and figuring out implicit type relations.

**Comment by elliott5** [comment]
I did not realise that a `typedef` could have a function declaration on it, still less how to write one.

Typedef certainly seems to fit better with a direct translation of Go AST.
 
The only issue is preserving the type information correctly when going in/out of Haxe `Any`/`Dynamic` when a Go `interface{}`, but this could perhaps be done with a method on the `typedef` - needs to be tested, but I don't know how!

**Comment by elliott5** [comment]
I see module-level `function` declarations that enable this are new in  [Haxe version 4.2](https://haxe.org/blog/module-level-fields/).

**Comment by PXshadow** [comment]
I spent a decent amount of time trying to rnd, to see what typesystem could work for all of the cases raised. unfortunatly typedefs don't work for isOfType, "is" operator, so I've written a macro to fill in the gaps to allow class structs to multi extend, and be the new typesystem used. new issue for it here: #14 .

Let me know if I'm missing anything, and yes modularity is extremly nice, current generation should use it, the question for functions that have a reciever function is should they be added into the Class type or should it stay a modular function and then linked into the Class like so.

```haxe

class Data {
     public var x:Int;
     public function test() {
         test(Go.makePointer(this));
     }
}

function test(d:Pointer<Data>) {
    d.x = 10;
}
```

or conventional Haxe style, 

```haxe
class Data {
     public var x:Int;
     public function test() {
         var d = Go.makePointer(this);
         d.x = 10;
     }
}
```

**Comment by elliott5** [comment]
I've been thinking about how to make the generated Haxe files look like the source Go files, but keep the methods of a Go type in a single Haxe class.

The conclusion I have come to is to write all of the required classes into a single file with a well known name after all of the Go source files have been processed.

So in go2hx Haxe source files with same name as Go source files:
```
// Go: type User struct {Age int; Name string;}

// NOTE Haxe for Go type "User" is in "wellknown_filename.hx"

// Go: func (u *User) isOld() bool {return u.Age>40;}

var isOld_method_User = function(u:User):Bool {
	return u.Age > 40;
}
```

Then in "wellknown_filename.hx". written at end of processing all Go source in a directory, containing a class declaration for each Go type:
```
class User {
	public var Age:Int;
	public var Name:String;

	public function new(new_Age:Int, new_Name:String) {
		this.Age = new_Age;
		this.Name = new_Name;
	}

	inline public function isOld():Bool {
		return isOld_method_User(this);
	}

	// other auto-generated method calls for Go type User...
}
```

**Comment by PXshadow** [comment]
This is a fantastic idea! It would be extremely nice to be able to also keep the file structure within each of the other files, but then use a system of type aliasing potentially and the "wellknown_filename.hx" static functions calling into the local files. I'm still not as experienced as I would like to be with this, so it will probably take some trial and error, but the idea is very solid and will be a great step towards clean generation. Potentially for the name it could be the package name its self, so for example:  reflect.Reflect as the global file, with reflect.Deepequal,  reflect.Type, reflect.Value, reflect.Swapper etc.

**Comment by PXshadow** [comment]
Last part of Class system needed is the main class decleration for the entire package. "Then in "wellknown_filename.hx". written at end of processing all Go source in a directory, containing a class declaration for each Go type" - @elliott5

**Comment by PXshadow** [comment]
This should now be done, it's a very wild mix of import.hx default importing, pkg path, with a global file. Haxe really likes files and Go doesn't even know what a file is 😄
