### ISSUE TITLE
new Slice call signature

### ISSUE THREAD

**Issue by elliott5** [go2hx/go2hx#134]
Looking at the example code we will be presenting to our users for them to emulate, some of it is quite off-putting in it's complexity.

In particular `new Slice` requires the construction of an entire array of default items:

```haxe
function exampleEncodeRune():Void {
	var _r:GoInt32 = ("世".code : GoInt32);
	var _buf = new Slice<GoUInt8>((3 : GoInt).toBasic(), 0, ...[for (i in 0...(3 : GoInt).toBasic()) (0 : GoUInt8)]);
	var _n:GoInt = stdgo.unicode.utf8.Utf8.encodeRune(_buf, _r);
	stdgo.fmt.Fmt.println(_buf);
	stdgo.fmt.Fmt.println(_n);
}
```

Could `new Slice<sliceType>` not have the parameters:
- length (as now)
- capacity (as now)
- default value matching `sliceType`
- ...optional initialisation values (as now)

Then `new Slice<T>(len, cap, default, ...init)` could fill all the uninitialised space in the slice with the default value, both at initialisation and subsequently after an append or changed capacity.

**Comment by PXshadow** [comment]
> Could `new Slice<sliceType>` not have the parameters:
> 
>     * length (as now)
> 
>     * capacity (as now)
> 
>     * default value matching `sliceType`
> 
>     * ...optional initialisation values (as now)

That's a great idea, if we are passing the default type perhaps we could just save it within the Slice and then when null is returned from the vector we return the default value, so we don't need to spend resources filling up the array unless optionally initialized.

**Comment by PXshadow** [comment]
You can now do this:
```haxe
var _buf = new Slice<GoUInt8>(3,3).__setNumber32__();
```
