### ISSUE TITLE
Generation of tests when a separate  "_test" package is not used.

### ISSUE THREAD

**Issue by elliott5** [go2hx/go2hx#135]
A very simple example from the Go team:
 https://github.com/golang/example/blob/master/stringutil/reverse_test.go 

This formula should also generate test code, the runner of which should be in a `stringutil_test` directory, but calling `TestReverse` in the `stringutil` directory.

**Comment by PXshadow** [comment]
I ran this command inside the example repo

```sh
haxelib run go2hx --rebuild golang.org/x/example/stringutil --test
```

result:
```
Generated: golibs/golang_org/x/example/stringutil/Stringutil.hx - 1.919kb
Generated: golibs/golang_org/x/example/stringutil_test/Stringutil.hx - 1.666kb
haxe -lib go2hx -cp golibs --hl test.hl  -m golang_org.x.example.stringutil_test.Stringutil
hl test.hl
=== RUN   TestReverse
--- PASS: TestReverse (0.000792980194091797)
```

I see that ``TestReverse`` is inside of ``stringutil`` and it should be inside ``stringutil_test``, is that the issue @elliott5 ?

**Comment by elliott5** [comment]
No, `TestReverse` should be inside `stringutil` as that is how the test was written.

For that command I get a HL compilation error:
```
% haxelib run go2hx --rebuild golang.org/x/example/stringutil --test
rebuilding...
create compiler instance
listening on local port: 6243
nodejs server started
accepted connection
Generated: golibs/golang_org/x/example/stringutil/Stringutil.hx - 1.914kb
Generated: golibs/golang_org/x/example/stringutil_test/Stringutil.hx - 1.666kb
haxe -lib go2hx -cp golibs --hl test.hl  -m golang_org.x.example.stringutil_test.Stringutil
/usr/local/lib/haxe/std/haxe/Rest.hx:48: character 2 : Don't know how to cast hl.types.ArrayBytes_hl_F32 to hl.types.ArrayDyn
hl test.hl
File not found 'test.hl'
```

... but it does generate the Haxe to run tests, and interp does work.
```
% haxe -lib go2hx -cp golibs --interp  -m golang_org.x.example.stringutil_test.Stringutil

=== RUN   TestReverse
--- PASS: TestReverse (0.000418901443481445312)
```

...which is very pleasing.

I think my issue was understanding how to generate the test code. 

It seems to generate the test code you must individually run the generation for each directory, rather than it coming aa a consequence of compiling the following with the `--test` flag:
```go
package main

import (
	_ "golang.org/x/example/stringutil"
)

func main() {}
```

**Comment by PXshadow** [comment]
> It seems to generate the test code you must individually run the generation for each directory, rather than it coming aa a consequence of compiling the following with the `--test` flag:
> 
> ```go
> package main
> 
> import (
> 	_ "golang.org/x/example/stringutil"
> )
> 
> func main() {}
> ```

This may be a consequence of what the Go compiler is giving out in terms of data. It would be plausible that the compiler would simply dce the test packages of stringutil with the example from above as there is no call to the Test functions.

I'm glad it's working in the wild isolated @elliott5 I'm quite pleased as well, it's come a long way.

**Comment by elliott5** [comment]
Which version of HashLink are you using?

**Comment by PXshadow** [comment]
@elliott5 same version
```
% hl -v
HL/JIT 1.12.0 (c)2015-2022 Haxe Foundation
  Usage : hl [--debug <port>] [--debug-wait] <file>
```

It's possible I compiled from source but I'm pretty sure I installed it through brew.

**Comment by elliott5** [comment]
Interestingly, if I add `-dce full` to the haxe command, the problem goes away:
```
% haxe -lib go2hx -cp golibs --interp  -m golang_org.x.example.stringutil_test.Stringutil

=== RUN   TestReverse
--- PASS: TestReverse (0.000415086746215820312)

% haxe -lib go2hx -cp golibs --hl run.hl   -m golang_org.x.example.stringutil_test.Stringutil

/usr/local/lib/haxe/std/haxe/Rest.hx:48: character 2 : Don't know how to cast hl.types.ArrayBytes_hl_F32 to hl.types.ArrayDyn

% haxe -lib go2hx -cp golibs --hl run.hl -dce full  -m golang_org.x.example.stringutil_test.Stringutil

% hl run.hl
=== RUN   TestReverse
--- PASS: TestReverse (0.00190281867980957)

```

**Comment by PXshadow** [comment]
That is quite interesting, perhaps that info would be useful in a Haxe issue.

I create this issue before https://github.com/HaxeFoundation/haxe/issues/10535 perhaps it's related I'll have to isolate out the Haxe code and send in an issue eventually.
