### ISSUE TITLE
Jvm target failing casting for unit tests

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#142]
```
regression results: 
jvm|interface0
jvm|interface11
jvm|interface12
jvm|interface14
jvm|interface6
jvm|interface7
jvm|named5
jvm|named7
jvm|named8
```

named5 part of the error:
```sh
Exception Details:
  Location:
    github_com/go2hx/go4hx/rnd/X_asInterface.__underlying__()Lstdgo/AnyInterfaceData; @71: aload_0
  Reason:
    Type 'stdgo/PointerData' (current frame, stack[2]) is not assignable to 'java/lang/Integer' 
```

**Comment by elliott5** [comment]
It is certainly true that `stdgo/PointerData` - a [class](https://github.com/go2hx/go2hx/blob/2163be450e50a055ca6f79ea51774a4a32e5090e/stdgo/Pointer.hx#L76) with quite a few variables -  is unlikely to be assignable to `java/lang/Integer`.

So the question is, from which Go/Haxe statement is this obviously wrong JVM code being generated?

I can't see this `rnd.go` code as it is not in the main repo.

**Comment by PXshadow** [comment]
Yes you are right, and here is the code @elliott5 .

rnd.go
```go
package main

type x int

func (x) run() {}

type i interface {
	run()
}

func main() {
	var y x = 10
	var z any = y
	z.(i).run()
}
```

**Comment by elliott5** [comment]
Could you please also share the generated Haxe @PXshadow

**Comment by PXshadow** [comment]
It's working now, jvm is very specfic about casting.

**Comment by elliott5** [comment]
Well done for finding the bug @PXshadow
