### ISSUE TITLE
multi var invalid order for setting the vars

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#145]
```go
func main() {
	dc := 632
	extra := 7
	extraMask := 127
	dc, fracc := dc>>extra, dc&extraMask
	fmt.Println(dc, fracc)
}
```

```haxe
function main():Void {
	var _dc:GoInt = (632 : GoInt);
	var _extra:GoInt = (7 : GoInt);
	var _extraMask:GoInt = (127 : GoInt);
	var _dc:GoInt = _dc >> _extra, _fracc:GoInt = _dc & _extraMask;
	stdgo.fmt.Fmt.println(_dc, _fracc);
}
```

Haxe: 4, 4
Go: 4, 120

**Comment by elliott5** [comment]
I believe the issue is the second declaration of `_dc` in Haxe.

If I change the name of the second declaration to be `_dc2`, then insert a new statement to set `_dc=_dc2`,  it works correctly, see this [TryHaxe code](https://try.haxe.org/#59DfD287).

**Comment by PXshadow** [comment]
> I believe the issue is the second declaration of `_dc` in Haxe.
> 
> If I change the name of the second declaration to be `_dc2`, then insert a new statement to set `_dc=_dc2`, it works correctly, see this [TryHaxe code](https://try.haxe.org/#59DfD287).

So temp variables should be made for all multi variable statements? @elliott5

**Comment by elliott5** [comment]
That would certainly be the simplest approach @pxshadow.

The compilation optimisation process should eliminate the temporary variables that are not actually needed, so their existance should not affect the final speed of the code.

**Comment by elliott5** [comment]
The central problem remains that in Go you can write:
```go
a := 42
a , b := 1 , 2
```
But because `a` has already been declared, the second declaration (alongside `b`) is ignored.

This behaviour needs to be modelled by `go2hx`.

That modelling requires keeping track of which variables have already been declared.

From the Go [spec](https://go.dev/ref/spec#Variable_declarations):

> Unlike regular variable declarations, a short variable declaration may redeclare variables provided they were originally declared earlier in the same block (or the parameter lists if the block is the function body) with the same type, and at least one of the non-[blank](https://go.dev/ref/spec#Blank_identifier) variables is new. As a consequence, redeclaration can only appear in a multi-variable short declaration. Redeclaration does not introduce a new variable; it just assigns a new value to the original.

**Comment by PXshadow** [comment]
This now works:
Haxe: 4 120
Go: 4 120
```haxe
function main():Void {
	var _dc:GoInt = (632 : GoInt);
	var _extra:GoInt = (7 : GoInt);
	var _extraMask:GoInt = (127 : GoInt);
	var _0:GoInt = _dc >> _extra,
		_1:GoInt = _dc & _extraMask,
		_fracc:GoInt = _1,
		_dc:GoInt = _0;
	stdgo.fmt.Fmt.println(Go.toInterface(_dc), Go.toInterface(_fracc));
}
```
