### ISSUE TITLE
Improve go mod experince

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#158]
There is no documentation at the moment discussing setting up a go mod file and if they are needed to use non std pkgs.

It seems the go4hx part of the compiler does not parse non std pkgs if there is no go.mod file.

The compiler should handle all of this for the user and not require any experience with using go's pkg mod system.

**Comment by elliott5** [comment]
Go needs `go.mod` to tell it which versions of the called packages used by the main package to `go get` before Go2hx can do its work.

Go2hx then uses those Go packages to generate the Haxe code.

I agree, the beginner Haxe user, using pre-baked Go2hx libraries, would not need to know anything about `go.mod` or even Go.

But to develop your own Go2hx library, for use in your own code, a correct `go.mod` file is vital. See https://github.com/go2hx/go2hxdoc/tree/master/example-project

**Comment by PXshadow** [comment]
go2hx now automatically generates a go mod if one doesn't exist, and if one does exist it will modify the one in the directory where the go2hx commands are called.
