### ISSUE TITLE
All classes need to be public because of Reflect's usage of std.Type.resolveClass

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#159]
``std.Type.resolveClass`` unfortunately can't resolve private classes from other packages, and this functionality is needed for reflect defaultValue creation of named struct types, as those are classes.

In the short term I will mark all classes that would normally be private with ``:private`` metadata and set them to public, hopefully go2hxdoc, can parse the metadata.

In the long term it'd be great to dig into the internals and figure out how to allow private classes to still be resolved with ``std.Type``.

**Comment by elliott5** [comment]
This seems like a good approach, I'll add an issue for go2hxdoc to implement it.

**Comment by elliott5** [comment]
Appologies @PXshadow , my change to go2hxdoc to remove public classes with "@:private" metadata seems to have failed, I will revisit.

**Comment by PXshadow** [comment]
@elliott5 no problem at all, I'm happy to simply get the ci passing again, I'm sure go2hx doc will be able to pick up the private metadata soon.

**Comment by PXshadow** [comment]
All classes are public at the moment.
