### ISSUE TITLE
Getting go version 1.20.0 passing all regression tests

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#160]
Go has ramped up its testing efforts this version it seems along with slowly bringing in new internal functions and even some functions with generics.

I'll document the commits here that will bring go2hx in line with the latest go version.

Here is an example "test":
```go
// For testing *Pointer[T]'s methods can be inlined.
// Keep in sync with cmd/compile/internal/test/inl_test.go:TestIntendedInlining.
var _ = &Pointer[int]{}
```

**Comment by elliott5** [comment]
For the record, I think emulating Go's inlining rules in go2hx would be very "ambitious" (which in my polite indirect form of UK English actually means "foolish").

**Comment by PXshadow** [comment]
> For the record, I think emulating Go's inlining rules in go2hx would be very "ambitious" (which in my polite indirect form of UK English actually means "foolish").

I agree with you completely, however it indirectly shows an issue with go2hx's type handling:

```haxe
private var _15:Ref<Pointer_<T>> = (new Pointer_<GoInt>(new GoArray<Pointer<GoInt>>(...[for (i in 0...0) (null : Pointer<GoInt>)]), ({} : T_noCopy),
	null) : Ref<Pointer_<T>>);
```

**Comment by elliott5** [comment]
Good catch!

**Comment by PXshadow** [comment]
This is now working!

**Comment by elliott5** [comment]
Superb @PXshadow !
