### ISSUE TITLE
Haxe implementation of Go map

### ISSUE THREAD

**Issue by elliott5** [go2hx/go2hx#163]
The TardisGo implementation:
```haxe
class GOmap {
	public var baseMap:Map<String,{key:Dynamic,val:Dynamic}>;
	public var kz:Dynamic; // "key" zero value
	public var vz:Dynamic; // "val" zero value
	public function new (kDef:Dynamic,vDef:Dynamic) {
		//trace("DEBUG new",kDef,vDef);
		baseMap = new Map<String,{key:Dynamic,val:Dynamic}>();
		kz = kDef;
		vz = vDef;
	}
	#if cpp
		static var setDefaultFormat:Bool=true;
	#end
	public static function makeKey(a:Dynamic):String{
		#if cpp
			if(setDefaultFormat){ // TODO rewrite this so that we don't check every time
				cpp.Lib.setFloatFormat("%.17g");
				setDefaultFormat=false;
			}
		#end
		//trace("DEBUG makeKey",a);
		if(a==null) return "<<<<NULL>>>>"; // TODO how can this be more unique?
		if(Reflect.isObject(a)){
			if(Std.is(a,String))
				return a;
			if(Std.is(a,Pointer))
				return cast(a,Pointer).toUniqueVal();  
			// NOTE Object could be an abstract
			#if !abstractobjects
			if(Std.is(a,Object)){
				//trace("DEBUG makeKey Object found");
				var r=cast(a,Object).toString(); 
				//trace("DEBUG makeKey Object="+r);
				return r;
			}
			#end
			if(Std.is(a,Complex)){
				return Complex.toString(a);
			}
			if(Std.is(a,Interface))
				return cast(a,Interface).toString();
			if(Std.is(a,Slice)) 
				return a.toString();
			if(Std.is(a,Channel))
				return a.toString();
			if(Std.is(a,GOmap)||Std.is(a,Closure)) {
				Scheduler.panicFromHaxe("haxeruntime.GOmap.makeKey() unsupported haxe type: "+a);
				return "";
			}
			#if abstractobjects
				return a.toString(); // must be an Object or Int64
			#else
				return GOint64.toString(a);
			#end
		}
		#if cs			
			if(Std.is(a,Float)) {
				// in cpp & cs, Std.string(1.9999999999999998) => "2"
				// TODO consider how to deal with this issue in the compound types above
				return GOint64.toString(Go_haxegoruntime_FFloat64bits.callFromRT(0,a));
			}
		#end
		return Std.string(a);
	}
	public function set(realKey:Dynamic,value:Dynamic){
		var sKey = makeKey(realKey);
		//trace("DEBUG set",sKey,realKey);
		if(baseMap.exists(sKey)){
			if(!Force.isEqualDynamic(baseMap.get(sKey).key,realKey))
				Scheduler.panicFromHaxe("haxeruntime.GOmap non-unique key for: "+sKey);
		}
		baseMap.set(sKey,{key:realKey,val:value});
	}
	public function get(rKey:Dynamic):Dynamic {
		var sKey = makeKey(rKey);
		//trace("DEBUG get",sKey,rKey);		
		if(baseMap.exists(sKey))	return baseMap.get(sKey).val;
		else 						return vz; // the zero value
	}
	public function exists(rKey:Dynamic):Bool {
		var sKey = makeKey(rKey);
		//trace("DEBUG exists",sKey,rKey);		
		return baseMap.exists(sKey);
	}
	public function remove(r:Dynamic){
		var s = makeKey(r);
		//trace("DEBUG remove",s,r);		
		baseMap.remove(s);
	}
	public function len():Int {
		var _l:Int=0;
		var _it=baseMap.iterator();
		while(_it.hasNext()) {_l++; _it.next();};
		//trace("DEBUG len",_l);		
		return _l;
	}
	public function range():GOmapRange {
		var keys = new Array<String>();
		var k = baseMap.keys(); // in C# and Java, this may not work if new items are added to the map
		while(k.hasNext()) 
			keys.push(k.next());
		return new GOmapRange(keys,this);
	}
}

class GOmapRange {
	private var k:Array<String>;
	private var m:GOmap;
	public function new(kv:Array<String>, mv:GOmap){
		k=kv;
		m=mv;
	}
	public function next():{r0:Bool,r1:Dynamic,r2:Dynamic} {
		var _hn:Bool=k.length>0;
		if(_hn){
			var _nxt=k.pop();
			if(m.baseMap.exists(_nxt))
				return {r0:true,r1:m.baseMap.get(_nxt).key,r2:m.baseMap.get(_nxt).val};
			else
				return next(); // recurse if this key is not found (deleted in-between?)
		}else{
			return {r0:false,r1:m.kz,r2:m.vz};
		}
	}
}

```

The "key" issue I would draw your attention is the need to store the key value as part of the map's data structure to allow easy iteration.

**Comment by elliott5** [comment]
Note also that pointers need to have unique values (rather than always being `1`, as now), as pointers are often used as map keys.

From the above code:
```haxe
	return cast(a,Pointer).toUniqueVal();  
```

Pointers are also often cast to `uintptr` and then processed and compared.

In TardisGo, each Go object in Haxe contained an integer field `uRef` assigned a unique value when the object was created, which acted as its "pointer". This could be cast to `uintptr` when required and to string for use as map keys.

```haxe
// as part of new object creation...
// uniqueCount is a global variable & would need a mutex round it for go2hx use
	uniqueCount += 1;  
	uRef = uniqueCount;
```

**Comment by PXshadow** [comment]
@elliott5 What is the advantage of having a unique number, when reference equality can be used for pointer comparison?

**Comment by elliott5** [comment]
The TardisGo code above has to mess about with the precision of printing Float values inside Haxe to make the map keys work reliably.

If I were making a map-key from a float64 now, I would cast the float64 to uint64, so that precision when converting to string was not an issue.

**Comment by elliott5** [comment]
There are 3 places where a unique number might be helpful:

1. Creating keys for a Haxe map, assuming Haxe maps cannot have objects as their keys;
2. Casting pointers to `uintptr` and getting unique values per object when you do; and
3. Potential `unsafe` casting of `uintptr` to pointer, assuming that a memory map exists:

```haxe
public static var memory = new Map<Int,Object>()
```

Where a new value is created every time a pointer is cast to `uintptr`.

This last one is for the future I know.

**Comment by elliott5** [comment]
I see there is [`haxe.ds.ObjectMap`](https://api.haxe.org/haxe/ds/ObjectMap.html) available on some platforms.

**Comment by elliott5** [comment]
Borrowing and amending the Haxe comments for `Map` key values:

1. if `K` is a `String`, `haxe.ds.StringMap` is used => Go `string`
2. if `K` is an `Int`, `haxe.ds.IntMap` is used =>  Go `int32`
3. if `K` is an `EnumValue`, `haxe.ds.EnumValueMap` is used  => (no direct Go equivalent, but see below)
4. if `K` is any other class or structure, `haxe.ds.ObjectMap` is used => Go `*something` (a pointer)
5. if `K` is any other type, it causes a compile-time error

`haxe.ds.EnumValueMap` is the only one of the above implementations that is written in Haxe, and that by extending `haxe.ds.BalancedTree`. The extension only requires two functions to be written:
```haxe
	override function compare(k1:EnumValue, k2:EnumValue):Int {}
	override function copy():EnumValueMap<K, V> {}
```

Clearly, if the Go map key is `string`, `int32` or `*something` those target-specific implementations of Map should be used.

But for everything else, either:

1. all keys could be expressed as enums (unsurprisingly, I have ideas for how to do this); or
2. for each Go type used as a map key, create a custom extension of `haxe.ds.BalancedTree` for that Go type; or
3. as with TardisGo,  `haxe.ds.StringMap` could be used by stringifying the key; or
4. the map code could be written in Go, for example using https://pkg.go.dev/github.com/google/btree

**Comment by PXshadow** [comment]
What approach do you think is best to try first in your view? @elliott5 

I'm uneasy about a stringifying method, 2 and 4 look the best to  me.

**Comment by elliott5** [comment]
I think option 2, creating custom extensions of `haxe.ds.BalancedTree`  is most likely to be successful @PXshadow.

This requires creating an extension to  `haxe.ds.BalancedTree` for every Go type. The extensions probably need to be declared immediately after the type is declared, with a consistent naming convention, so that whatever the `typeName` is, the code generator knows that it should be using `typeName_map` (or whatever naming convention) as the map type with that type as the key.

Special handling will be required for the built-in `string` / `haxe.ds.StringMap`, `int32` / `haxe.ds.IntMap` and `*something` / `haxe.ds.ObjectMap` maps.

Maps with having an `interface{}` key also require special handling. The `override function compare` can use [`reflect.Equal()`](https://pkg.go.dev/reflect#Value.Equal) to test equality, but would need to use two `fmt.Sprintf("%v",value)` values to create comparable strings to define the ordering (see comment on [`reflect.String`](https://pkg.go.dev/reflect#Value.String)). For speed, these generated string key values should  be kept in each `haxe.ds.BalancedTree` extension node, to prevent multiple (slow) calls to `fmt.Sprintf()`.

In terms of sequencing this work, you should consider getting the system working correctly, then speeding it up. To get the map system working quickly but correctly, implementing all go2hx maps as having `interface{}`  keys (using the technique in the paragraph above) would require least code changes I imagine.

A second phase could then roll out custom maps for every Go type, which would make them faster.

**Comment by PXshadow** [comment]
This approach is so clean and I think it will work great, I'm really happy you thought about this your expertise is invaluable!

Here are to the 2 most complex maps (still prototyping before I commit):
```haxe
class GoObjectMap<K,V> extends BalancedTree<K,V> {
	public var t:_Type;
	public function new(t) {
		super();
		this.t = t;
	}
	override function compare(k1:K, k2:K):Int {
		final key = new AnyInterface(k1,t);
		final objKey = new AnyInterface(k2,t);
		return key == objKey ? 0 : 1;
	}
}

class GoAnyInterfaceMap<AnyInterface,V> extends BalancedTree<AnyInterface,T> {
	override function compare(k1:AnyInterface, k2:AnyInterface):Int {
		return k1 == k2 ? 0 : 1;
	}
}
```

For AnyInterfaceMap I think I need to write if the types can be compared first, but the general idea is there. I hope to share more progress soon!

**Comment by elliott5** [comment]
The logic of the compare functions you have written is not quite right @PXshadow :

```haxe
override function compare(k1:K, k2:K):Int { // should return a -ve, +ve, or 0 result:
   // If k1 is less than k2, the result is negative. 
   // If k2 is less than k1, the result is positive. 
   // If k1 and k2 are equal, the result is 0.
}
```

See [code for `compare`](https://github.com/HaxeFoundation/haxe/blob/e5eec3122454bfc95412437d938d1d8d3e77ed68/std/haxe/ds/BalancedTree.hx#L225) and [documentation for `Reflect.compare`](https://api.haxe.org/Reflect.html).

**Comment by elliott5** [comment]
To see why this ordering is important, look at the [code for `get(key:K):Null<V>`](https://github.com/HaxeFoundation/haxe/blob/e5eec3122454bfc95412437d938d1d8d3e77ed68/std/haxe/ds/BalancedTree.hx#L54).

**Comment by elliott5** [comment]
I think any `map` key that is a Go go2hx type that fits into Haxe `Int`: 
```haxe
typedef GoByte = GoUInt8;
typedef GoRune = GoInt32;
typedef GoInt = GoInt32;
typedef GoUInt = GoUInt32;
private typedef Int8 = #if simulate_num Int; #elseif cpp cpp.Int8; #elseif cs cs.Int8; #elseif java java.Int8; #else Int #end
private typedef Int16 = #if simulate_num Int; #elseif cpp cpp.Int16; #elseif cs cs.Int16; #elseif java java.Int16; #else Int; #end
private typedef Int32 = haxe.Int32; // #if cpp cpp.Int32 #elseif cs cs.system.Int32 #else haxe.Int32 #end;
private typedef UInt8 = Int; // #if hl hl.UI8 #elseif cpp cpp.UInt8 #elseif cs cs.UInt8 #else Int #end;
private typedef UInt16 = #if simulate_num Int; #elseif hl hl.UI16; #elseif cpp cpp.UInt16; #elseif cs cs.UInt16; #else Int; #end
private typedef UInt32 = #if simulate_num UInt; #elseif cpp cpp.UInt32; #elseif cs cs.system.UInt32; #elseif eval eval.integers.UInt64; #else UInt; #end
``` 

Should (maybe eventually) use `haxe.ds.IntMap`, because the ordering is not important so long as it is consistent (so unsigned values will not matter).

**Comment by PXshadow** [comment]
@elliott5 my apologizes, you're right I will use sprintf and compare strings with one another, and use IntMap for Int values that fit into Int32 space.

**Comment by PXshadow** [comment]
@elliott5 I ran into a slight problem https://pkg.go.dev/reflect#MapIter.Value I think requires all Maps to have the type data passed inside of them, do you think there's a way around it? 

The map iterates on values inside of the map, which means that the value's reflect type is also needed from my understanding.

**Comment by PXshadow** [comment]
Also here's my current write up of GoAnyInterfaceMap (map[any]unknown):
```haxe
class GoAnyInterfaceMap<AnyInterface,T> extends BalancedTree<AnyInterface,T> {
	override function compare(k1:AnyInterface, k2:AnyInterface):Int {
		#if nolinkstd
		return 0;
		#else
		final k1Str = stdgo.fmt.Fmt.sprintf("%v", k1);
		final k2Str = stdgo.fmt.Fmt.sprintf("%v",k2);
		return if (k1Str == k2Str) {
			0;
		}else if (k1Str > k2Str) {
			1;
		}else{
			-1;
		}
		#end
	}
}
```

**Comment by elliott5** [comment]
@PXshadow, your code for GoAnyInterfaceMap should work, but be slow because of recreating the string version of the key for every comparison.

To get round this, the `stdgo.fmt.Fmt.sprintf("%v",key)` value needs to be created only once for each entry in the map.

There are two approaches to doing this, either:
```haxe
class GoAnyInterfaceMapKey {
  var ai:AnyInterface;
  var ais:String;

  function new(k:AnyInterface) {
    ai = k;
    ais = stdgo.fmt.Fmt.sprintf("%v",k);
  }
}

class GoAnyInterfaceMap<AnyInterfaceMapKey,T> extends BalancedTree<AnyInterfaceMapKey,T> {
  // code as you have it but comparing AnyInterfaceMapKey.ais
}
```

Or (as TARDISgo did):
```haxe
class GoAnyInterfaceMapEntry<T> {
  var key:AnyInterface;
  var val:T;

  function new(k:AnyInterface,v:T) {
    key = k;
    val = v;
  }
}

// Then use the normal target-specific haxe.ds.StringMap 
// with the  stdgo.fmt.Fmt.sprintf("%v",GoAnyInterfaceMapEntry.key) as the key 
// and GoAnyInterfaceMapEntry as the value.
// The proper key value is required in the entry in order to do Go map iteration.

var myMap : haxe.ds.StringMap<GoAnyInterfaceMapEntry<myValueType>>;
myMap[ stdgo.fmt.Fmt.sprintf("%v", myKey) ] = GoAnyInterFaceMapEntry(myKey, myValue);
x = myMap[ stdgo.fmt.Fmt.sprintf("%v", y) ].val; // null checks also needed here
```

I'll look into the `MapIter.Value` issue and get back to you.

**Comment by elliott5** [comment]
> @elliott5 I ran into a slight problem https://pkg.go.dev/reflect#MapIter.Value I think requires all Maps to have the type data passed inside of them, do you think there's a way around it?
> 
> The map iterates on values inside of the map, which means that the value's reflect type is also needed from my understanding.

`reflect.MapIter` is created by [`Value.MapRange()`](https://pkg.go.dev/reflect#Value.MapRange) which is a method of [`reflect.Value`](https://pkg.go.dev/reflect#Value) which already contains the type information. 

The [Go implementation of  MapIter](https://cs.opensource.google/go/go/+/refs/tags/go1.20.2:src/reflect/value.go;l=1820)  includes the map's `Value` (containing the Type information). The map's value can be obtained using [`MapIter.Value()`](https://pkg.go.dev/reflect#MapIter.Value) and the map's type by calling [`MapIter.Value().Type()`](https://pkg.go.dev/reflect#Value.Type).

All of this *only* relates to Go maps accessed via the `reflect` package, normal Go maps do not need their type information stored within them.

**Comment by PXshadow** [comment]
@elliott5 thanks for the help, from first glance I don't see how the first approach works because that would only sort the type string and not the type+value string that is created from fmt sprintf. Am I missing something?

**Comment by elliott5** [comment]
I don't believe any type information ever gets formatted as a string @PXshadow, only the value of the key. 

Fuller code (in my dreadful Haxe) for the `haxe.ds.BalancedTrree` method would be:
```haxe
// define a key type that includes both the original key and its string representation
class GoAnyInterfaceMapKey {
  var ai:AnyInterface;
  var ais:String;

  function new(k:AnyInterface) {
    ai = k;
    ais = stdgo.fmt.Fmt.sprintf("%v",k);
  }
}

// The composite key type defined above forms the key to the map
class GoAnyInterfaceMap<T> 
extends haxe.ds.BalancedTree<AnyInterfaceMapKey,T> {
         // code as you have it but comparing AnyInterfaceMapKey.ais
	override function compare(k1:AnyInterfaceMapKey, k2:AnyInterfaceMapKey):Int {
	         if (k1.ais==k2.ais) return 0; 
		return if (k1.ais > k2.ais) {
			1;
		}else{
			-1;
		}
	}
}

// example use:
var myMap : GoAnyInterfaceMap<MyType>;
myMap[ GoAnyInterfaceMapKey.new(someAnyInterfaceKey) ] = someMyTypeValue;
x= myMap[ GoAnyInterfaceMapKey.new(y) ]; // needs null handling
```

I hope the above code ideas make this approach a little clearer.

**Comment by PXshadow** [comment]
I'll work on implementing the key value string caching and other things now, just wanted to get an initial commit through.
Your Haxe code is a great reference thank you, and I get it now, you don't want to have to remake the string values every time the map iterates for an exists/set/get function. It should be a massive difference, thanks @elliott5 !

**Comment by PXshadow** [comment]
Current benchmark holding up GoMap performance

```go
package main

import (
	"fmt"
	"time"
	"unicode"
)

func main() {
	stamp := time.Now()
	for i := 0; i < 1_000_000; i++ {
		unicode.IsUpper('ű')
	}
	fmt.Println(time.Since(stamp))
}
```

Haxe: 10.365405952s
Go: 16.157997ms

There is an allocation occuring in __slice__ -> __ref__ and I'm not sure how to get rid of it yet.

**Comment by elliott5** [comment]
I'm not sure if an allocation can be avoided when making a ref to a slice, it would be faster if it were not required.

However, in this case the issue is probably optimisation. Since the following code has no effect (the result of `IsUpper()` is not used and `IsUpper()` has no side-effects) the call to `IsUpper()` and possibly even the whole `for` loop is probably optimised away by Go:
```go
	for i := 0; i < 1_000_000; i++ {
		unicode.IsUpper('ű')
	}
```

See this go playground code showing if `IsUpper()` is in or out makes no difference to the execution time - https://go.dev/play/p/XKvlnBAwAnM

**Comment by PXshadow** [comment]
@elliott5 [here](https://github.com/go2hx/go2hx/blob/master/stdgo/Slice.hx#L251)

**Comment by elliott5** [comment]
I don't think an allocation to hold a sub-slice's "pointer-and-offsets" is avoidable. 

The optimisation question is, why is this `unicode.IsUpper('ű')` code creating a sub-slice at all? Could it's creation be avoided?

**Comment by PXshadow** [comment]
Go map implementation is drastically different now, closing and made a new post for the benchmark issue.
