### ISSUE TITLE
Pointers need to have unique values (rather than always being `1`, as now)

### ISSUE THREAD

**Issue by elliott5** [go2hx/go2hx#164]
Note also that pointers need to have unique values (rather than always being `1`, as now), as pointers are often used as map keys.

From the above `makeKey()` code:
```haxe
	return cast(a,Pointer).toUniqueVal();  
```

Pointers are also often cast to `uintptr` and then processed and compared.

In TardisGo, each Go object in Haxe contained an integer field `uRef` assigned a unique value when the object was created, which acted as its "pointer". This could be cast to `uintptr` when required and to string for use as map keys.

```haxe
// as part of new object creation...
// uniqueCount is a global variable & would need a mutex round it for go2hx use
	uniqueCount += 1;  
	uRef = uniqueCount;
```

_Originally posted by @elliott5 in https://github.com/go2hx/go2hx/issues/163#issuecomment-1469386026_

**Comment by elliott5** [comment]
This is a break-out issue from #163 .

Go relies on objects in memory having unique addresses for much of its logic.

So, `uintptr(&x)` & `fmt.Println(&x)` need to yield unique and repeatable results (rather than always "1") for the code that's generated to work correctly

This unique uint64 value could be created directly on some targets, for example `cpp` has a [`Pointer`](https://api.haxe.org/cpp/Pointer.html) type that is exactly what is required.

On targets without pointers, the value will have to be simulated as described above.

**Comment by PXshadow** [comment]
I think uintptr is going to need a rework as well.

**Comment by PXshadow** [comment]
Looked at the latest implementation pointers create a unique address using a globalAdress and mutext to prevent race conditions.

```go
package main

func main() {
	s := 0
	s2 := 2
	println(&s, &s2)
}
```

```
hl runrnd.hl
0x3 0x4

~~~~~~~~~~~~expected~~~~~~~~~~~~
0xc00004e728 0xc00004e720
```
