### ISSUE TITLE
Confused about the helloworld on the manual.

### ISSUE THREAD

**Issue by fy0** [go2hx/go2hx#176]
Sorry for this unprofessional issue, but i have no idea how to proceed.

I'm a golang programmer and I don't know how to use Haxe at all, just try some tools to convert go to another language.

I followed the manual, it said:

https://go2hx.github.io/manual/getstarted.html

1. Create a main.go:
```
package main
func main() {
    println("hello world")
}
```

2. Run compiler:
```
haxelib run go2hx ./main.go
```

Then i got a folder `golibs`, a Main.hx inside the folder "golibs/_internal"

```
package _internal;
function main():Void {
    stdgo.Go.println(("hello world" : stdgo.GoString));
}
```

Am i successed? How could I invoke my go program? What should I do now?
It's really a puzzle for a beginner, i can't find any tutorial on internet.

**Comment by elliott5** [comment]
欢迎，中文是我的爱好！是的，你成功了——干得好！

Yes, you have succeeded - well done!

But there are quite a few more steps required to invoke the program I'm afraid.

The Haxe website is at https://haxe.org/ from which you will need to download the Haxe compiler.

You will need to download the HashLink ("HL") code generator and interpreter from https://hashlink.haxe.org/  .

A little experimentation should allow you to run the code you have generated.

Haxe is a multi-target language, created by a multi-national team, I hope you find it interesting too.

**Comment by fy0** [comment]
> 欢迎，中文是我的爱好！是的，你成功了——干得好！
> 
> Yes, you have succeeded - well done!
> 
> But there are quite a few more steps required to invoke the program I'm afraid.
> 
> The Haxe website is at https://haxe.org/ from which you will need to download the Haxe compiler.
> 
> You will also need to download the HashLink ("HL") code generator and interpreter from https://hashlink.haxe.org/ .
> 
> A little experimentation should allow you to run the code you have generated.
> 
> Haxe is a multi-target language, created by a multi-national team, I hope you find it interesting too.

嗨，感谢回复。

yeah, i got haxe compiler, but i found the code of haxe is similar to java: it needs a class and publc void main() 

it's different from generated code.

I tried to compile it:
```
cd golibs
haxe --main _internal.Main --interp
```

Then i got error:
```
_internal/Main.hx:27: characters 22-36 : Type not found : stdgo.GoString
```

There must be some library path or package.json like files.
I'm still trying to make it works

**Comment by fy0** [comment]
Good news: it works!
Other beginners can follow my method:

After this command executed, you will got a folder names golibs at same path:
```
haxelib run go2hx ./main.go
```

Then:

```
$ cd golibs
$ haxe --main _internal.Main -lib go2hx --interp
C:\HaxeToolkit\haxe\lib\go2hx/git/stdgo/_internal/internal/Macro.macro.hx:44: non hxb types:,224
hello world
```

`-lib go2hx` just like gcc's lib path and it means all packages in go2hx is in code namespace, so `stdgo` can be invoke.
`--interp` means execute by interpreter (https://haxe.org/manual/compiler-usage.html#common-arguments)

The generated code file is not like haxe's java-style helloworld (https://haxe.org/manual/introduction-hello-world.html)
There only a `main()` function without class. I guess it's a feature like C#'s Top-level statements

**Comment by PXshadow** [comment]
Thank you for the issue @fy0 , I've updated the manual based on your feedback.
Thank you as well @elliott5
