### ISSUE TITLE
Incorrect type conversion for (int)((uint32)(m))

### ISSUE THREAD

**Issue by Yeaseen** [go2hx/go2hx#177]
# Issue with go2hx Translation: Incorrect Type Conversion

## Source Go Code

```go
package main
import "fmt"
func main() {
    var local_int int = 1
    var m int = -1
    fmt.Printf("local_int before the loop: %d\n", local_int)
    m = 15 - ((int)((uint32)(m )))
    fmt.Printf("m before the first loop: %d\n", m)
    for ; m < 15; m++ {
        local_int = 0
    }
    fmt.Printf("local_int after the first loop: %d\n", local_int)
}
```

### Output of the Go Code

```
local_int before the loop: 1
m before the loop: -4294967280
local_int after the loop: 0
```

## Translated Haxe Code

```haxe
package _internal;
function main():Void {
    var _local_int:stdgo.GoInt = (1 : stdgo.GoInt);
    var _m:stdgo.GoInt = (-1 : stdgo.GoInt);
    stdgo._internal.fmt.Fmt.printf(("local_int before the loop: %d\n" : stdgo.GoString), stdgo.Go.toInterface(_local_int));
    _m = ((15 : stdgo.GoInt) - (((_m : stdgo.GoUInt32) : stdgo.GoInt)) : stdgo.GoInt);
    stdgo._internal.fmt.Fmt.printf(("m before the loop: %d\n" : stdgo.GoString), stdgo.Go.toInterface(_m));
    stdgo.Go.cfor((_m < (15 : stdgo.GoInt) : Bool), _m++, {
        _local_int = (0 : stdgo.GoInt);
    });
    stdgo._internal.fmt.Fmt.printf(("local_int after the loop: %d\n" : stdgo.GoString), stdgo.Go.toInterface(_local_int));
}
```

### Output of the Haxe Code

```
local_int before the loop: 1
m before the loop: 16
local_int after the loop: 1
```

## Description of the Issue

The primary issue with the `go2hx` translation lies in the handling of type conversions for the variable `m`. In the original Go code, `m` is cast from `int` to `uint32` and back to `int`, resulting in a large negative value (`-4294967280`). This allows the subsequent loop (`for ; m < 15; m++`) to execute correctly, updating `local_int` to `0`.

However, in the translated Haxe code, the same type conversions incorrectly set `_m` to `16`. This prevents the loop from executing, leaving `_local_int` unchanged at `1` after the loop. The root cause appears to be that `go2hx` does not correctly map Go's `int` to Haxe's `GoInt64` on a 64-bit system, leading to improper interpretation of the converted value. Consequently, the loop condition fails, and the intended modifications within the loop do not occur.

This discrepancy indicates a flaw in the `go2hx` translator's type conversion logic, particularly when handling signed and unsigned integer casts on 64-bit architectures.

## Steps to Reproduce

1. **Run the Source Go Code:**
   - Observe the correct output where `local_int` is updated after the loop.

2. **Translate the Go Code to Haxe using `go2hx`:**
   - Use the provided translated Haxe code.

3. **Execute the Translated Haxe Code:**
   - Notice that `m` is incorrectly set to `16`, and the loop does not execute, leaving `local_int` unchanged.

## Expected Behavior

The translated Haxe code should replicate the behavior of the original Go code, resulting in `local_int` being updated to `0` after the first loop.

## Actual Behavior

In the Haxe translation:
- `m` is set to `16` instead of `-4294967280`.
- The loop does not execute because `16` is not less than `15`.
- `local_int` remains `1` instead of being updated to `0`.

## Suggested Fix

Ensure that the `go2hx` translator correctly maps Go's `int` type to Haxe's `GoInt64` on 64-bit systems. This involves accurately handling the casting between signed and unsigned integers to preserve the intended binary representation and resulting values.

**Comment by elliott5** [comment]
Thank you @Yeaseen - this is exactly the type of thoughtful, detailed, and helpful feedback that go2hx needs.

I know it should not be relevant, but for completeness, could I please ask which Haxe target you tested on?

This may be an important fundamental bug. If so, fixing this will resolve other problems elsewhere in the system. It may also relate to the size of "int"/"stdgo.GoInt" in the generated code. 

I'm out today, but will look in more detail tomorrow.

**Comment by Yeaseen** [comment]
Thank you for your response. 
The Haxe target was version `4.3.4`

Looking forward to your detail.

**Comment by PXshadow** [comment]
Hello @Yeaseen 

go2hx simulates a 32 bits environment regardless of Haxe target for simplicity, i.e int is equal to int32 under the hood.
However explicit int64 or uint64 declaration is allowed.

This type of behavior is [spec compliant](https://go.dev/ref/spec#Numeric_types) and follows standard practice of another compiler [gopherjs](https://github.com/gopherjs/gopherjs?tab=readme-ov-file#general)

To have the same behavior as a 64 bits system you can add a type alias of int to int64:
```go
type int int64
```

Lastly Haxe targets are the [compiler targets](https://haxe.org/documentation/introduction/compiler-targets.html) that Haxe code compiles into, such as into python, js, c++ etc.

I hope this resolves your current issue!

I am also open to changes in this behavior in the form of a ci passing pull request supporting int64 as the type alias of int for 64 bits systems/targets.
