### ISSUE TITLE
go2hx fails to translate zero-comparison for arrays, resulting in unexpected runtime panic

### ISSUE THREAD

**Issue by Yeaseen** [go2hx/go2hx#179]
`go2hx` encounters a runtime error when translating Go code that performs a comparison on arrays that are already zeroed (e.g., `x != [4]int{}`). In Go, comparing an array initialized to zero with [4]int{} should evaluate to false. However, in Haxe, the translated comparison incorrectly evaluates to true, causing an unintended panic.

## Source Go Code:

```go
package main
func main() {
	var x [4]int = [4]int{}
	if x != [4]int{} {
			panic("PANIC!") // Trigger panic if array is not all zeroes
	}
}
```

## Expected Go Behavior:

No panic message as this kind of comparison is straightforward in Go.

## Translated Haxe Code:

```haxe
package _internal;
function main():Void {
    var _x:stdgo.GoArray<stdgo.GoInt> = (new stdgo.GoArray<stdgo.GoInt>(4, 4, ...[]).__setNumber32__() : stdgo.GoArray<stdgo.GoInt>)?.__copy__();
    if (stdgo.Go.toInterface(_x) != stdgo.Go.toInterface((new stdgo.GoArray<stdgo.GoInt>(4, 4, ...[]).__setNumber32__() : stdgo.GoArray<stdgo.GoInt>))) {
        throw stdgo.Go.toInterface(("PANIC!" : stdgo.GoString));
    };
}
```

## 
In Haxe, the comparison fails, resulting in the following error:

```
_internal/Runner.hx:5: characters 9-14 : Uncaught exception PANIC!
```

## Observation:

It appears that `go2hx` does not correctly handle comparisons between arrays when both sides are zeroed arrays. Go allows direct comparison for arrays, but Haxe’s translation seems to misinterpret `x != [4]int{}`, causing an exception even though `x` was initialized as `[4]int{}` and should match `[4]int{}`.

The equivalent Haxe translation could use a helper function to compare each element, ensuring that zeroed array comparisons in Go translate reliably to Haxe.

**Comment by elliott5** [comment]
Thank you @Yeaseen - this is unexpected.

As you say, a Haxe helper function would be the most straightforward approach for simple types (as in this example), but may not work with more complex Go types.

go2hx is generating a comparison between two Go interface values, so we'll need to research why this might be and how the runtime handles array comparisons between interfaces.

**Comment by Yeaseen** [comment]
Thank you for looking into this! Yes, a Haxe helper function seems like a clean solution for simpler types, and it would likely streamline cases like this. For more complex Go types or scenarios where interfaces are involved, perhaps examining how `go2hx` handles interface comparisons specifically might help identify any additional needs. If there are examples of `go2hx` successfully managing array comparisons with interfaces, that could give insights into any runtime nuances.

**Comment by PXshadow** [comment]
@Yeaseen  How are you running the code?

If you are using the git version via haxelib you can update by running:
```sh
haxelib git go2hx https://github.com/go2hx/go2hx
```

[The latest commit](https://github.com/go2hx/go2hx/commit/a325b8be50d07be34b9e26ab0bc86c6e1ed02fdc) adds in your test case and it passes correctly on latest.

I'll keep this open to make it easier to respond to.

**Comment by Yeaseen** [comment]
@PXshadow I am on this latest git version: 

`commit c7b64bd2d86c2bbadc416a4c5219f439a003d546 (HEAD -> master, origin/master, origin/HEAD)`

The source `go` code above is just built and run without the panic call. The generated tax code is still the same. I am running the following command inside the `golibs` folder where the `_internal/Runner.hx` is available. I am running the haxe code in its interpreter.

`haxe --main _internal.Runner -lib go2hx --interp`

The output:
`_internal/Runner.hx:5: characters 9-14 : Uncaught exception PANIC!`
 
The haxe code should not throw the panic call as the if condition is true. 

Let me know if I can provide any more info.

**Comment by PXshadow** [comment]
My mistake it seems to be working on hashlink target but not on interp. I will investigate what the cause is.

**Comment by PXshadow** [comment]
Okay try now @Yeaseen  it should work, and thanks for looking into the issue it means a lot to me, and really helps out the project, I am grateful

**Comment by Yeaseen** [comment]
@PXshadow The latest patched version works fine. Thanks for the good work! I'm glad to help, and I'm looking forward to contributing more to the project.
