### ISSUE TITLE
Performance regression for strconv TestIsPrint and TestIsGraphic for strconv

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#180]
go_goto branch (on personal computer)

```haxe
=== RUN  TestIsPrint
-- PASS: TestIsPrint (49.5220510959625)

=== RUN  TestIsGraphic
-- PASS: TestIsGraphic (51.3606071472168)
```

master branch (on github actions):

```haxe
-- PASS: TestIsPrint (12.3976559638977)

=== RUN  TestIsGraphic
-- PASS: TestIsPrint (12.3976559638977)
```

I suspect it will be even slower when ran on github actions with less powerful specs, but exactly the same.

**Comment by PXshadow** [comment]
Closing this, probably a false flag of having lots of prints for debugging on my computer.

Latest from master with goto changes merged:
```haxe
-- PASS: TestIsGraphic (13.485641002655)
 -- PASS: TestIsPrint (12.5122849941254)
```

**Comment by elliott5** [comment]
Good news!
