### ISSUE TITLE
go2hx Fails to Emit Runtime Error for Uncomparable Types (Slice, Map, Func) within Interfaces

### ISSUE THREAD

**Issue by Yeaseen** [go2hx/go2hx#183]
## Description

When translating Go code involving comparing two slices, `go2hx` incorrectly translates the comparison. In Go, comparing two slices with `==` should result in a runtime panic, as slices are uncomparable types. However, in the translated Haxe code, `go2hx` evaluates the comparison as `false` without throwing an error, which leads to unexpected behavior.

## Steps to Reproduce

1. Source Go code:

   ```go
   package main

   import "fmt"

   func main() {
       var a interface{} = []int{1, 2, 3}
       var b interface{} = []int{1, 2, 3}
       fmt.Println(a == b) // This should panic in Go as slice comparison is illegal
   }
   ```

2. Run the Go code:

   - **Expected Behavior**: The Go code builds successfully but throws a runtime panic when executed, due to an attempt to compare uncomparable types (slices).

3. Translated Haxe code by`go2hx`:

   ```haxe
   package _internal;
   function main():Void {
       var _a:stdgo.AnyInterface = stdgo.Go.toInterface((new stdgo.Slice<stdgo.GoInt>(3, 3, ...[(1 : stdgo.GoInt), (2 : stdgo.GoInt), (3 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>));
       var _b:stdgo.AnyInterface = stdgo.Go.toInterface((new stdgo.Slice<stdgo.GoInt>(3, 3, ...[(1 : stdgo.GoInt), (2 : stdgo.GoInt), (3 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>));
       stdgo._internal.fmt.Fmt_println.println(stdgo.Go.toInterface(_a == (_b)));
   }
   ```

4. Run the Haxe code inside `golibs` directory in Haxe interpreter using this `haxe --main _internal.Runner -lib go2hx --interp`
   - **Unexpected Behavior**: The Haxe code outputs `false` instead of throwing a runtime error.

## Expected Behavior

The translated Haxe code should throw an error or emulate Go's runtime panic when comparing uncomparable types, such as slices, rather than returning `false`.

## Additional Information

- **Go Version**: `go1.23.0`
- **go2hx Version**: `commit 29d31384b7036a6469091f7339360722df2f3086 (HEAD -> master, origin/master, origin/HEAD)`
- **Haxe Version**: `4.3.6`

This discrepancy could lead to incorrect assumptions in code that relies on Go's runtime behavior for uncomparable types. Implementing a similar runtime check in Haxe to mimic Go’s handling of slice comparisons would help ensure consistent behavior between Go and Haxe.

**Comment by elliott5** [comment]
Well spotted @Yeaseen !

**Comment by PXshadow** [comment]
These 3 types (map,slice,func) hould now cause a runtime panic in the same manner as go

**Comment by Yeaseen** [comment]
Thanks for your great effort, @PXshadow. I tried the latest git version of `go2hx`, which mimics the `Go` behavior to handle incomparable types within interfaces.

**Comment by PXshadow** [comment]
No problem, and thank you @Yeaseen for your hard work finding problems and testing the compiler. It is equally valuable work!
