### ISSUE TITLE
`go2hx` Allows Uncomparable Type Comparisons (invalid in Go), Incorrectly Returning `false` Instead of Causing a Panic

### ISSUE THREAD

**Issue by Yeaseen** [go2hx/go2hx#184]
## Description

In Go, certain types are uncomparable and attempting to directly compare them with `==` or `!=` results in a runtime panic. These uncomparable types include structs with slices, maps, and functions. However, `go2hx` allows these comparisons and translates them to Haxe code that simply returns `false`, which is inconsistent with Go's runtime behavior.

## Steps to Reproduce

1. **Example Code** (Struct with Slice Field):

   ```go
   package main

   import "fmt"

   type MyStruct struct {
       Field1 int
       Field2 []int // Slice makes this struct uncomparable
   }

   func main() {
       s1 := MyStruct{Field1: 1, Field2: []int{1, 2, 3}}
       s2 := MyStruct{Field1: 1, Field2: []int{1, 2, 3}}

       fmt.Println(s1 == s2) // This line will panic in Go
   }
   ```

2. **Example Code** (Map Comparison):

   ```go
   package main

   import "fmt"

   func main() {
       a := map[string]int{"a": 1}
       b := map[string]int{"a": 1}

       fmt.Println(a == b) // This line will panic in Go
   }
   ```

3. **Example Code** (Function Comparison):

   ```go
   package main

   import "fmt"

   func main() {
       f1 := func() int { return 1 }
       f2 := func() int { return 1 }

       fmt.Println(f1 == f2) // This line will panic in Go
   }
   ```

4. Translate the code to Haxe using `go2hx`.

5. Execute the translated Haxe code:
   - **Unexpected Behavior**: In each case, the Haxe code outputs `false` instead of causing a runtime error.

## Expected Behavior

The translated Haxe code should mimic Go’s behavior by either throwing an error or causing a runtime exception when attempting to compare uncomparable types, rather than silently returning `false`.

## Actual Behavior

`go2hx` translates the comparisons in such a way that they print `false` in Haxe, leading to incorrect assumptions in code that rely on Go's panic behavior for incomparable type comparisons.

## Additional Information

- **Go Version**: `go1.23.0`
- **go2hx Version**: `commit 29d31384b7036a6469091f7339360722df2f3086 (HEAD -> master, origin/master, origin/HEAD)`
- **Haxe Version**: `4.3.6`

## Impact

This discrepancy can lead to subtle bugs in codebases that rely on Go’s runtime error handling for uncomparable types. Implementing a runtime check in the Haxe translation to mimic Go’s behavior would ensure consistency and prevent potential misinterpretations.

## Note
Issue #183 is different because the source Go code in #183 does not produce a `go` build error, whereas the above Go codes result in build errors in Go, but the translated Haxe programs behave differently.

**Comment by elliott5** [comment]
This is an interesting issue @Yeaseen .

The examples above fail at compile time in `go`. Given that `go2hx` requires valid `go` code as input (its purpose is to translate working `go` libraries after all), I'm not sure that `go2hx` needs to defend against these exact errors.

However, if you transpose the `go` examples above to use `interface{}` variables, then they should produce runtime panics, as you describe.

Structs:
```go
package main

import "fmt"

type MyStruct struct {
	Field1 int
	Field2 []int // Slice makes this struct uncomparable
}

func main() {
	var s1, s2 interface{}

	s1 = MyStruct{Field1: 1, Field2: []int{1, 2, 3}}
	s2 = MyStruct{Field1: 1, Field2: []int{1, 2, 3}}

	fmt.Println(s1 == s2) // This line will panic in Go
}
```

Maps:
```go
package main

import "fmt"

func main() {
	var a, b interface{}

	a = map[string]int{"a": 1}
	b = map[string]int{"a": 1}

	fmt.Println(a == b) // This line will panic in Go
}
```

Functs:
```go
ackage main

import "fmt"

func main() {
	var f1, f2 interface{}

	f1 = func() int { return 1 }
	f2 = func() int { return 1 }

	fmt.Println(f1 == f2) // This line will panic in Go
}
```

I'm afraid I've not tested what `go2hx` does with these revised examples.

**Comment by PXshadow** [comment]
Okay the cases of func, slice and map interface equality checking should now be consistent, and return the same runtime error that Go does.

Runtime errors should function the same within reason.

However I am also in agreement with @elliott5 , not valid Go code, is not supported by go2hx in anyway. 

Down the road as a quality of life improvement I'd be fine with non valid Go code showing the compiler error from Go, and preventing go2hx compilation.

I say we close this issue, and keep #183 open until confirmation that it's working runtime panic wise.

**Comment by Yeaseen** [comment]
Yeah. Agree with both of you @elliott5 and @PXshadow 
The patterns in #183 should be the concern as these appear in the runtime errors. I am closing this issue and putting @elliott5's  revised codes in #183 comment

**Comment by Yeaseen** [comment]
Yeah. Agree with both of you @elliott5 and @PXshadow 
The patterns in #183 should be the concern as these appear in the runtime errors. I am closing this issue and putting @elliott5's  revised codes in #183 comment
