### ISSUE TITLE
GoArray bounds check

### ISSUE THREAD

**Issue by elliott5** [go2hx/go2hx#20]
GoArray bounds check at
https://github.com/PXshadow/go2hx/blob/master/stdgo/GoArray.hx#L45
allows an index of an array to be = the length of the array, which is outside the underlying array.
test for error should be `>=` 
```
        if (i >= this.length) {
            throw "array out of bounds, index: " + i + " length: " + length;
        }
```

**Comment by PXshadow** [comment]
@elliott5  good point, I've disabled bounds checking temporarily, there seems to be some flaw internally with knowing the correct length, I tested it with append.go test and it is failing the test by a massive out of bounds of the index compared to the length, I also refrenced bounds checking error for the BTree library at #17 

Let's consolidate discussion for correct length and bounds checking here.

**Comment by elliott5** [comment]
I can confirm from testing that the GoArray bounds testing should be as above.

For slices, it is more complex because of sub-slice handling, the `pos` value gives the offset from the start of the underlying array, while the `length` value stores the number of valid entries in the underlying array after `pos`.
But actually the code required turns out to be exactly the same, as it all resolves to being inside the `0<=x<length` range.
So provided the bounds check is done before `pos` is added it should be:
```
    private inline function boundsCheck(i:Int) {
        #if !no_check_bounds
        if (i >= this.length) { // length of this (sub)slice
                throw "slice out of bounds, index: " + i + " length: " + this.length;
        }
        if (i<0) // a -ve index is always out of bounds
            throw "slice negative index out of bounds";
        #end
    }
``` 
I've run tests on both a slice and sub-slice, which fail as required.

**Comment by PXshadow** [comment]
Thank you for the investigation and testing, I still don't know the underlying reasoning why it is failing, I think I'll just build a simple demo with some of the features and slowly debug through it and see if I can find the culprit.

**Comment by elliott5** [comment]
My test:
```
package main

import "fmt"

func main() {
	var ar [4]int
	for i := 0; i < 4; i++ { // change to 5 to fail
		ar[i] = i
	}
	//ar[-1] = 42 // will not compile in go

	sl := make([]int, 5)
	for i := 0; i < 5; i++ { // change to 6 to fail
		sl[i] = i
	}
	//sl[-1]=42 // will not compile in go

	sl2 := sl[1:3]
	for i := 0; i < 2; i++ { // change to 3 to fail
		sl2[i] = sl2[i] + 10
	}
	//sl2[-1]=42 // will not compile in go

	fmt.Println(ar, sl, sl2)
}
```

**Comment by elliott5** [comment]
Since both the array and slice `boundsCheck(i:Int)` are inline functions, every time they are used, potentially every time and array or slice element is accessed in user code, the two `throw` messages would be included it the program code too, inflating its size.

Having the throw code in a single subroutine would probably generate less code:
```
    private function throwOutOfBounds(i:Int, limit:Int) {
        throw "array/slice out of bounds, index: " + i + " length: " + limit;
    }

    private inline function boundsCheck(i:Int, limit:Int) {
        #if !no_check_bounds
        if (i<0 || i >= limit) { 
                throwOutOfBounds(i, limit);
        }
        #end
    }
```

**Comment by PXshadow** [comment]
Good point, the entire bounds check itsself can just be inline, I think only having the throw be inline still inflates the output size because of the if statement, I like the consolidating of the if statements with a unified error message though, I will change it out for this today :)

**Comment by PXshadow** [comment]
Its It's been consolidated, working now on making sure it doesn't throw for working go examples within bounds range.
