### ISSUE TITLE
KeyValueExpr and BasicLiterals can be intermixed in a CompositeLit

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#21]
Currently KeyValueExprs are supported using the @:structInit system and BasicLiterals are supported by using the new constructor and adding into it by order, however there is no system in place to be able to intermix the two (as I had no idea it was possible) and as such a new system needs to be built to allow intermixing. Best option seems to be a macro, since this case is rare almost all composite literals should have very nice syntax for constructing.

**Comment by PXshadow** [comment]
"If any element has a key, every element must have a key." - https://golang.org/ref/spec#Composite_literals

**Comment by PXshadow** [comment]
I've traced it back to initialize.go test, I'm not sure how this is working, since the from what I understand the spec says this is not possible. https://github.com/golang/go/blob/master/test/initialize.go#L35

**Comment by elliott5** [comment]
Wow, I never knew that was valid Go!

But the format does make sense, because non-initialised variables always contain 0.

It is described further down the text at https://golang.org/ref/spec#Composite_literals ...
```
For array and slice literals the following rules apply:

- Each element has an associated integer index marking its position in the array.
- An element with a key uses the key as its index. The key must be a non-negative constant representable by a value of type int; and if it is typed it must be of integer type.
- An element without a key uses the previous element's index plus one. If the first element has no key, its index is zero.
```

**Comment by PXshadow** [comment]
Dang sorry for missing that @elliott5 this is very useful thank you! Its a cool system it makes complete sense now I'll work on implementing it and getting it closed soon.

**Comment by PXshadow** [comment]
After all this time, this is still the most mind boggling Golang syntax I keep running across and get caught up for 10 mins trying to figure out what the heck is going on.

**Comment by PXshadow** [comment]
Supported!
