### ISSUE TITLE
Access to native Haxe from go2hx Go

### ISSUE THREAD

**Issue by elliott5** [go2hx/go2hx#24]
In GopherJS they have a specific `js` pseudo-Go module, see https://pkg.go.dev/github.com/gopherjs/gopherjs/js

TardisGo also had a similar `hx` pseudo-Go module, see https://github.com/tardisgo/tardisgo/blob/e0dd9a7e46b597cdc4d310c8a677c2da7444008e/haxe/hx/hx.go

So go2hx needs a similar pseudo-Go module. This will allow much of the `reflect` (and maybe other low-level) modules to be written in Go, and therefore able to reuse existing Go code from elsewhere.

_Originally posted by @elliott5 in https://github.com/PXshadow/go2hx/issues/8#issuecomment-796662137_

**Comment by PXshadow** [comment]
I have a few implementations for calling Haxe code that I think are pretty good and serve diffrent purposes.

1. The rather advanced one is macro generation of exported Haxe code into Go code to be used as an autocompletion bridge that fits correctly at compile time. This one is rather complex and is a pretty large system on its own, the reason why I think it's quite useful is it would allow, full Go autocompletion of Haxe code, no need on either side to define what parts are being exposed, and very easy generation in a plug and play style.

2. CGo/Go assembly inspired implementation, allow Go code to define a Haxe function that will replace the body of the Go function. Could be quite familar and easy to work with on the Go side, only issue is it neglects types and variable exposure, which is quite core for alot of Haxe that can be quite OOP.

3. ``hx`` pseudo-Go module as described above similar to Haxe's [Syntax](https://api.haxe.org/js/Syntax.html),  call a function to execute Haxe code in string form. Can be quite useful for little hacky things etc, not very good for large or systematic code chunks.

In refrence to #39 I think the usage of only number 2 is probably the best as types and global variables can just be in Go code and functions bodies that fall into the criteria of being modified can just be switched out by the compiler with a preamble comment.

**Comment by elliott5** [comment]
Option 2 is actually part of the [function declaration section of the Go language specification](https://golang.org/ref/spec#Function_declarations).

The Haxe code would still be able to see public go2hx generated global/public variables.

As you say, a preamble comment could help to generate the right code for calls:
```
//#go2hx_implementation stdgo.reflect.glue.myHelperFunction
func MyHelperFunction(a, b string) int
```

This will feel like a big step forward to me, when it is implemented.

**Comment by elliott5** [comment]
I've eventually got what you've implemented to work, but it is not quite what I was expecting!

You have very skilfully picked up the code for the  function referenced by `//#go2hx` and replaced the body of the Go function  beneath that `//#go2hx` with the code from the other file.

My expectation was that what would be generated would be a simple call to that other external Haxe method.

So my Go code:
```
//#go2hx /Users/elliott/Documents/haxe/go2hx_test/golibs/elliott/Elliott.TestHarness.testHarness
func testHarness()
```
Against my Haxe code:
```
class TestHarness {
	public static function testHarness() {
		trace("Elliott's testHarness code");
	}
}
```
Currently generates:
```
private function testHarness():Void {
		trace("Elliott's testHarness code");
	}
```
I was expecting it to generate:
```
private function testHarness():Void {
        elliott.Elliott.TestHarness.testHarness();
}
```

**Comment by PXshadow** [comment]
Yeah I initially had the idea to just do a simple call too @elliott5 however I thought the package paths might be quite confusing to figure out. It also requires the TestHarness code to be manually moved into the golibs folder, witch adds a decent amount of complexities. I see though that the path that you had to set for the TestHarness was not portable as well. I'll push the call access method one right now, in order to use the call one, no backslashes can be in the path, otherwise it defaults to the other one.

I'd like for one or both of the methods to fit the criteria of being very portable i.e either one of us can setup externs for TestHarness and be able to use them hassle free with no path changing, and no fiddling with settings or a build system.

**Comment by PXshadow** [comment]
Keep in mind also that the module paths are determined by the Haxe build.hxml source paths, so it's not very straight forward to be able to figure out where the Haxe file being refrenced in the native function access are in order to bundle them into the golibs folder. Final note to explain the golibs folder, it is to have an export folder for Go -> Haxe code and be able to easily set it as a source path for example: ``-cp golibs`` and use it in the Haxe code or set the Main file after.

**Comment by elliott5** [comment]
Yes @PXshadow, the code-inclusion method is very cool, there are occasions where it may be the best approach ... even if it is not classically how Go handles calls to C/assembly language functions.

I can see that getting the correct  Haxe module paths is a big problem too, and is also a problem for the `reflect` system prototype I am working on. 

In the prototype, a Go named type or interface references it's method-set by giving the textual Haxe class path, as returned by [`Type.getClassName(MyHaxeClass)`](https://api.haxe.org/Type.html#getClassName). This allows the Haxe class to be referenced at runtime using [`Type.resolveClass("path.to.MyHaxeClass")`](https://api.haxe.org/Type.html#resolveClass). A resolved class can then access the `rtti` data, if the `@:rtti` metadata was added.

**Comment by PXshadow** [comment]
@elliott5 Wow that is a fantastic find with regards to using Type's resolveClass and getClassName! So I assume you need the``_typeName_`` on Structs to be set with the Haxe module path? Let me know if I'm missing anything.

**Comment by elliott5** [comment]
The `rtti` data is only for Haxe classes. So typed Go structs work fine, because they compile to Haxe classes:
```
type Tx struct {
	X rune
	Y string
}
``` 
The Haxe `Type.getClassName` for this in my testing is `command_line_arguments.Tx`, so the `_typeName_` field is not required.

But untyped Go structs currently generate Haxe anonymous structures, `@:ntti` is not available for these, so the prototype falls-back to using Haxe `Reflect`. Unfortunately, this technique does not see any abstract data types, like `GoInt8`, only the Haxe native types like `Int`.

I will talk more about this as the `reflect` prototype develops.

**Comment by PXshadow** [comment]
@elliott5 would you like to have anonymous structures during compiling be turned into classes?

> Unfortunately, this technique does not see any abstract data types, like GoInt8, only the Haxe native types like Int.

Yeah that's unfourtnate not sure how to deal with that properly until the``is`` operator works for Abstracts.

**Comment by elliott5** [comment]
The reflect code will work in a simplistic way on anonymous structures for now, but the Go types will only be right if just Haxe equivalent int/float/bool/string types are used, and the field values are not null when inspected to determine their type.

There is exactly the same issue with reflect for array/slice/map. Worse, for chan/func values there seems no way to inspect the values required to create an accurate Go type.

So yes, classes for anonymous struct would solve that problem, but the array/slice/map and chan/func issues will need further consideration.

**Comment by PXshadow** [comment]
> array/slice/map and chan/func issues will need further consideration.

using ``Type.typeof`` and ``Type.getClassName`` of a generic class with ``@:generic`` meta data you can actually obtain the T type underneath.

https://try.haxe.org/#5e3aE979

No idea though how to obtain type information of a function at runtime in Haxe.

**Comment by PXshadow** [comment]
> Unfortunately, this technique does not see any abstract data types, like GoInt8, only the Haxe native types like Int.

Wild idea for this, use the ``@:using`` extension approach to turn the underlying type for abstract GoUInt8 for example as ``@:using(StdGoTypes._UInt8__extension) typedef _UInt8 = Int`` then every data type (including anon structs in the future) will have _typeName_ so you won't even need to resolve the type, instead you can just call ._typeName_ for any type including abstract data types. Let me know what you think, it's purely theoritical I have not tested if it works.

**Comment by elliott5** [comment]
That could be a great idea in the medium term. But the type information is actually set-up by the `@:to ... AnyInterface` in the abstract, it can't be called once the GoUInt8 is passed to the AnyInterface ... I've tried without success ;)

**Comment by PXshadow** [comment]
> That could be a great idea in the medium term. But the type information is actually set-up by the @:to ... AnyInterface

Oh yeah I totally forgot that system exists... Wouldn't passing to AnyInterface and obtaining typeName there solve the issue? I know it probably doesn't because things are not that simple but on first glance I'm not sure why this approach wouldn't. Also if you need extra data passed to AnyInterface for, for instance GoUInt8 that can be handleded.

**Comment by elliott5** [comment]
Sorry @PXshadow , I missed your tip about getting the Haxe generic type for a class from `Type.getClassName(c)` - I will try it out, but it is unlikely to reference Go types that are abstracts.

In the longer term, getting the correct type (in `GT_enum` format as constructed by the go2hx transpiler, then serialized) passed within AnyInterface will always be the best solution.

For non-rtti compex types (function/map/chan/array/slice/... maybe also anon struct), I had the idea of creating the variable as an AnyInterface, so that the type info would always be available.

So the Go:
```
c := make(chan int8)
```
Might generate something like:
```
var c = new AnyInterface({value: Go.make(((_ : Chan<GoInt8>))), typeName: new reflect.Type(GT_chan(GT_int8)).serialize());
```
All normal access to the channel would be via `c.value`, but when it needs to be sent to an interface, `c` would be used.

After everything is working, the system can be optimised to not use typeName (string) in AnyInterface, but rather just use type (GT_enum) instead.

**Comment by elliott5** [comment]
Copied and pasted the https://try.haxe.org/#5e3aE979 code into reflect, but unfortunately I can't see any classes of the form "class_typeName":
```
stdgo/reflect/Reflect.hx:606: ====>name  underlying type: eval.Vector
array [2]int64 17 array true

stdgo/reflect/Reflect.hx:606: ====>name stdgo. underlying type: Slice.SliceData
slice []bool 23 slice false

stdgo/reflect/Reflect.hx:606: ====>name stdgo. underlying type: GoMap.MapData
stdgo/reflect/Reflect.hx:606: ====>name github underlying type: com.pxshadow.go4hx.rnd.Vertex
map map[string]github_com.pxshadow.go4hx.rnd.Vertex 21 map false

stdgo/reflect/Reflect.hx:606: ====>name  underlying type: stdgo.Chan
chan chan invalid 18 chan true
```

**Comment by PXshadow** [comment]
It works on Chan class but abstracts seem to prevent the name having the type param as a string. I'm working on another way to get this working with typed T param and some code generation, will have a prototype soon.

**Comment by elliott5** [comment]
... although inspecting class name suffixes will only give Haxe types, rather than Go types.

**Comment by PXshadow** [comment]
The prototype code (mentioned above) is now commited, can now add typeNames of generic types such as chan/array/slice. A design doc should probably get created though in order to know how reflect/type switching and AnyInterface map to each other and what fields are required across the systems. I'm pretty sure at this point "typeName"" is legacy and should get replaced with a more sophiscated system more aligned with data types in reflect, and then have reflect be able to print out "[]int" for a Slice Int with the data. Curious to know your thoughts though @elliott5 , I'll work on the new stdgo rewrite for now #43

**Comment by elliott5** [comment]
I agree, `typeName` as a string is a legacy.

It would be far better to use `reflect.Type`, which is to say `stdgo.reflect.GT_enum`, to represent the Go type, since it allows any Go type to be represented.

This would require changing the specification of `AnyInterface` to use `type` rather than `typeName` then changing all those `@:to` functions - a major job.

I should probably commit my latest `reflect` version before you attempt this.

**Comment by PXshadow** [comment]
This system should be working, edge cases where it is not feel free to open a new issue.
