### ISSUE TITLE
iota and methods on non-struct named types - example reflect.Kind

### ISSUE THREAD

**Issue by elliott5** [go2hx/go2hx#25]
```
package main

import "fmt"

const (
	Invalid Kind = iota
	Bool
	Int
	Int8
	Int16
	Int32
	Int64
	Uint
	Uint8
	Uint16
	Uint32
	Uint64
	Uintptr
	Float32
	Float64
	Complex64
	Complex128
	String
	UnsafePointer
	Chan
	Interface
	Ptr
	Slice
	Array
	Func
	Map
	Struct
)

type Kind int

func (k Kind) String() string {
	switch k {
	case Bool:
		return "bool"
	case Int:
		return "int"
	case Int8:
		return "int8"
	case Int16:
		return "int16"
	case Int32:
		return "int32"
	case Int64:
		return "int64"
	case Uint:
		return "uint"
	case Uint8:
		return "uint8"
	case Uint16:
		return "uint16"
	case Uint32:
		return "uint32"
	case Uint64:
		return "uint64"
	case Uintptr:
		return "uintptr"
	case Float32:
		return "float32"
	case Float64:
		return "float64"
	case Complex64:
		return "complex64"
	case Complex128:
		return "complex128"
	case String:
		return "string"
	case UnsafePointer:
		return "unsafe.Pointer"
	case Chan:
		return "chan"
	case Interface:
		return "interface"
	case Ptr:
		return "ptr"
	case Slice:
		return "slice"
	case Array:
		return "array"
	case Func:
		return "func"
	case Map:
		return "map"
	case Struct:
		return "struct"
	default:
		return "invalid"
	}
}

func main() {
	fmt.Println("Kind test harness")
	for i := 0; i < 30; i++ {
		k := Kind(i)
		fmt.Println(i, k.String())
	}
}

```
Does not compile on go2hx.
Both because `iota` is not implemented; and 
because Go methods on non-struct named types are not implemented properly (no link between code and type).

**Comment by elliott5** [comment]
All named Go types will need a Haxe Class to put their methods in.

**Comment by PXshadow** [comment]
I did work previously to support the IOTA system, I'm currently going to opt for the simplier system for now, that being just having a system of constant variables like how Go does it, The issue with an enum abstract is handling the new scoping diffrences in the Go code versus the Haxe code. On that subject as well I'm a little bit stuck on how to deal with Go allowing types to be overrided by variables in this case, How did you work around it since Haxe does not allow the same thing? Thanks for  the help!

**Comment by elliott5** [comment]
I don't understand the problem you describe I'm afraid, could you give me an example?

I'd make two points though ... 
- first, all go2hx input must be valid Go, so the generated Haxe does not need to worry about Go code misbehaving; and
- second, the iota logic can be quite complex - so an alternative would be to write a Go program that compiled the iota code and output the required Haxe, run that go program on the fly, then include the generated Haxe in the output. See example auto-generated go program to auto-generate Haxe below: 
```
package main

import "fmt"

const (
	Invalid int = iota
	Bool
	Int
	//...
)

func main() {
	fmt.Println("final Invalid =", Invalid, ";")
	fmt.Println("final Bool =", Bool, ";")
	fmt.Println("final Int =", Int, ";")
	//...
}
```

**Comment by elliott5** [comment]
Just to prove how complex the `iota` logic can be, and why it would be easier to let the Go compiler do it for you see https://medium.com/swlh/iota-create-effective-constants-in-golang-b399f94aac31 .

**Comment by PXshadow** [comment]
example:
```go
package main

func main() {
	{
		type string int //redefine string to int
		var s string = 0
		println(s)
	}
	var s string = "hi"
	string := 2
	println(s, string)
}
```

being able to redefine types for Go and also turn type names into variables. When I attempt to try something similar in Haxe I get this https://try.haxe.org/#0D448B57 ``error: Type name String is redefined from module String``. I think the solution will be to increase the awareness of the compiler when it comes to block scoping and being able to redefine types as needed within a local scope, I'd be curious what you think about the problem and perhaps that I'm missing something?

Also as for the iota logic being complex, that seems more straightforward to me then compiler scoping, I think I can follow all of those rules for the IOTA system and achieve the same result as Go, I agree it could technically be easier to generate a Go program execute it and then aquire the result, but it does have a hefty drawback, of increased complexity (needing to properly type and write on the fly programs and then grab the output of the program) and much more time needed to transpile the code. I do like the idea of using Go to self generate complex parts of the spec though, I'd like to use it for other parts of the spec possibily that are hard to deal with on the Haxe side, witch could still be for the IOTA system, I just want to take a shot at replicating the system first. Thanks for all of the help @elliott5 these discussions have given me very good direction to write code to continue to fill in the spec, and I deeply apperciate it.

**Comment by elliott5** [comment]
You're welcome @PXshadow, good luck with the `iota` code, however you approach it.

As for your Go example, there are two issues for me - using a reserved word as an identifier, and block scoping a type.

I'm disappointed that Go allows built-in types to be overloaded in this way, as it makes code less readable, which seems against the point of Go in the first place. So my advice is to throw a go2hx error at this point, then wait to see if there is some production use that means an important Go library cannot be converted to Haxe because of it.

Block scoping a type is a more common problem. The obvious way to do it is to change the name of the `type`/`Typedef` to something like `userTypeName__userFuncName_blockNumber` then, during the generation of that block, map the user's type name to the generated one.

**Comment by PXshadow** [comment]
> I'm disappointed that Go allows built-in types to be overloaded in this way, as it makes code less readable, which seems against the point of Go in the first place. So my advice is to throw a go2hx error at this point, then wait to see if there is some production use that means an important Go library cannot be converted to Haxe because of it.

Solid idea I will implement it.

Block scoping a type is a more common problem. The obvious way to do it is to change the name of the type/Typedef to something like userTypeName__userFuncName_blockNumber then, during the generation of that block, map the user's type name to the generated one.

Amazing idea as well, I'll do this as well, these two ideas and the scoping system implemented, the last scoping item will be package depth, thanks! This is extremly good stuff.

**Comment by PXshadow** [comment]
The String function ``func (k Kind) String() string`` interferes with the switch statement case for k == string, as the names conflict, but only on the Haxe side, the standard method of changing out name conflicts when casing is turned to lowercase doesn't work as both identifieres are uppercase, not sure of a good fix for this, I could brute force it and declare all function identifiers be named one way and a variable be named another.

**Comment by elliott5** [comment]
I've seen other contexts where the Go->Haxe renaming does not work, because the code doing the renaming often does not know the full Go context of the name. An example of this is field names with upper/lower case first letters.

I think it would be better to always rename in a brute-force way, but keep the original Go names (because they don't clash).

[`Haxe reserves the identifier prefix _hx_ for internal use.`](https://haxe.org/manual/expression.html)

A simple "Haxe" way to do the renaming would therefore be to preface all names with `_go_`.

Haxe types would not be a special case, because: `Type names must start with an upper-case letter A-Z or an underscore _.`

**Comment by PXshadow** [comment]
I like following the convention of ``_hx_`` but for go identifiers now. Yeah I think your  advice is the most sound that if a rename occurs make it in a brute force way to avoid other headaches. I still have the urge to put a few exception notes however, first should come working usable code, afterwards can come polish and petrifying.

I'll look into the field name uppercase and lowercase test and see if I can fix it, thanks.

**Comment by elliott5** [comment]
Sorry, looking at my failing upper/lower case example again, it looks like an instantiation issue. Go code:
```
package main

import (
	"fmt"
)

type T struct {
	S string
	s string
}

func (t T) String() string {
	return t.S + "-" + t.s
}

func main() {
	message := T{S: "upper", s: "lower"}
	fmt.Println(message.String()) // output: "upper-lower"
}
```

**Comment by elliott5** [comment]
Confirm instantiation issue fixed.

**Comment by PXshadow** [comment]
Nice I'll close this, if you find any occurence of IOTA failing feel free to make another issue.

**Comment by elliott5** [comment]
The only think I'd say is that  in the code generated for the original example, the first value `Invalid` is of type `Kind` but subsequent values are of type `GoInteger`.
Not a problem in the short term, but could be later...

**Comment by PXshadow** [comment]
I'll fix that and close after, good point.
