### ISSUE TITLE
Small integer types not constrained to maximum size allowed after arithmetic

### ISSUE THREAD

**Issue by elliott5** [go2hx/go2hx#26]
```
package main

import (
	"fmt"
)

func main() {
	a := uint8(255)
	b := uint8(1)
	fmt.Println(a + b) // go2hx prints 256, go prints 0
}
```

**Comment by PXshadow** [comment]
So in order to restrict the number types, a clamp function as you've discussed earlier would be the best way to go @elliott5 ?

**Comment by elliott5** [comment]
Yes so for `a + b` above the code should be `clampUInt8(a+b)` where
```
inline function clampUInt8(x:UInt8):UInt8 {
	return x & 0xff;
}
```
Clamp functions for `uint16` and `uint32` just have bigger masks `0xffff` and `0xffffffff`.

Clamp functions for signed integers are more complicated as they require their sign extended.

The "clamp" functions I wrote for TardisGo, including platform-specific code, are here:  https://github.com/tardisgo/tardisgo/blob/e0dd9a7e46b597cdc4d310c8a677c2da7444008e/haxe/haxeRuntime.go#L82

The TardisGo `toInt32` clamp function is wrong if an `Int` on the target platform is 64 bits, in this case masking & sign extension are still required.

**Comment by elliott5** [comment]
Note that it is necessary to "clamp" after every binary operation, not on assignment. This to prevent unexpected side effects.

**Comment by PXshadow** [comment]
Armimm.go test is the first milestone for this testing wise, most number types still need the operator overloads for binary operators on most targets, I have written up the clamp functions for each of the numbers, I'm not making sure implicit casting is working properly across the types and also changing out the standard division functionality to the Go style of always staying an integer.

**Comment by elliott5** [comment]
I agree that `armimm.go` is a good milestone. I tried to compile it after a `lix install` and got lots of errors, most related to Go constant type conversion issues.

Go constants are not typed until they are used, other than being `bool`, `integer`, `float` or `string`. Therefore modelling `integer` constants in Haxe will require some extra work to accomplish.

My suggestion would be to create a Haxe abstract `GoIntegerConstant`, where the underlying constant is held as 64 bits, but where there are `@to:` methods for each of the Go u/int variants.

Second issue ... I noticed in the generated code that an `int64` constant was created from a float:
```
private final c64a : GoInt64 = haxe.Int64Helper.fromFloat(47851696654647398);
``` 
This will not always work, since a `float64` cannot accurately hold the full range of `int64` values - not enough bits!

**Comment by PXshadow** [comment]
> Go constants are not typed until they are used, other than being bool, integer, float or string. Therefore modelling integer constants in Haxe will require some extra work to accomplish.

Ah I see! Well that's unfortunate as it could make the code signifilicantly slower, I should run some test cases to understand how Go does casting more, for instance if a number is an int32 but is added to, to become over the range, would a Go Int constant just be an int64 in the end where as a set Int32 would become 0?

> My suggestion would be to create a Haxe abstract GoIntegerConstant, where the underlying constant is held as 64 bits, but where there are @to: methods for each of the Go u/int variants.

That sounds good, I think the GoInt64 could just be used as long as sneaky implicit casting is not working to break tests.

> This will not always work, since a float64 cannot accurately hold the full range of int64 values - not enough bits!

Changed it to parsing a string I think that should work thanks for the tip @elliott5 !

**Comment by elliott5** [comment]
> I think the GoInt64 could just be used... 

I do not think it would be wise to use Haxe `GoInt64` (modelling Go `int64`) to hold Go integer constants.

Go integer constants *should always* auto-convert to the actual type required when seen in the code (including to `float64/float32`). 

By contrast all Go types (including `int64`) *should never* auto-convert. Go always requires an explicit cast between types. Making types explicit was one of the original design goals of the language, in order to remove the bugs caused by implicit conversions (as seen for example in `C/C++`).

**Comment by PXshadow** [comment]
Yeah you're right. Thank you for the advice I will follow it, also I found this https://golang.org/src/builtin/builtin.go?s=3808:3828#L105 perhaps it could be named IntegerType. I also may be really shooting myself in the foot the more I think about the auto conversion you mentioned with the casting system, I've written now quite a few @:from and @:to casts in order for the Go assert to actually no longer need be a macro and instead use Haxe's CheckType ``(expr: type)`` . I'm not sure if this will now allow implicit casts all of the time and screw everything up. Also I'm still trying to wrap my head around the idea that adding two diffrent integer types is not allowed in Go and everything is explicit, I still have much to write and delete... all in good fun though!

**Comment by elliott5** [comment]
> perhaps it could be named IntegerType

Using the same name as is used in the Go documentation will always make life easier long-term, so `IntegerType` is a good choice here.

> use Haxe's CheckType `(expr: type)` 

Since the `(expr: type)` Haxe notation is a compile-time function that recognises abstracts, it sounds ideal for this purpose.

So Go like `x := uint8(y)` might generate Haxe like `var x = (y:UInt8)`, with the compiler calling the appropriate `@:to` function (in this case to `uint8`), if required.

I'm not clear what the use-case for `@:from` conversions would be though.

**Comment by PXshadow** [comment]
Decent work on this front, I also have a very expirimental Complex128 working for small numbers but I think it's broken perhaps for larger number not sure, esentially I just took the exact same approach haxe did for the Int64 and just did it with Int128 using two Int64s, I'm also pretty happy with the IntegerType system I currently have it as 3 diffrent abstracts, one that holds an int32 size, second holding an int64 and finally the last holding a int128/complex128, I then have generated quite a few operator overload functions so whenever an IntegerType is included into a binary expr it gets converted into the other type in the binary operation. I've also attempted to isolate the main functionality of the numbers for the Armimm test that way I can add back in the CheckType after the test is passing so see if it at all interfers with the results. I am very happy as I am understanding the number situation much better now, I hope this progress update greets you well.

**Comment by elliott5** [comment]
It sounds like you are making great progress @PXshadow !

I'll take a look at the `IntegerType` code later today, to see if there is anything I can usefully give you feedback on.

However, I'm very concerned that you have mis-understood what Go `complex64/complex128` numbers are.
A `complex64` value holds two `float32` values; a `complex128` value holds two `float64` values.
The two float values represent the "real" and "imaginary" parts of a [complex number](https://en.wikipedia.org/wiki/Complex_number).
My Haxe code for implementing it in TardisGo was:
```
class Complex {
	public var real:Float;
	public var imag:Float;

	public function new(r:Float, i:Float) {
		real = r;
		imag = i;
	}

	public static function neg(x:Complex):Complex {
		return new Complex(0.0 - x.real, 0.0 - x.imag);
	}

	public static function add(x:Complex, y:Complex):Complex {
		return new Complex(x.real + y.real, x.imag + y.imag);
	}

	public static function sub(x:Complex, y:Complex):Complex {
		return new Complex(x.real - y.real, x.imag - y.imag);
	}

	public static function mul(x:Complex, y:Complex):Complex {
		return new Complex((x.real * y.real) - (x.imag * y.imag), (x.imag * y.real) + (x.real * y.imag));
	}

	public static function div(x:Complex, y:Complex):Complex {
		if ((y.real == 0.0) && (y.imag == 0.0)) {
			Scheduler.panicFromHaxe("complex divide by zero");
			return new Complex(0.0, 0.0); // dummy value as we have hit the panic button
		} else {
			return new Complex(((x.real * y.real) + (x.imag * y.imag)) / ((y.real * y.real) + (y.imag * y.imag)),
				((x.imag * y.real) - (x.real * y.imag)) / ((y.real * y.real) + (y.imag * y.imag)));
		}
	}

	public static function eq(x:Complex, y:Complex):Bool { // "=="
		return (x.real == y.real) && (x.imag == y.imag);
	}

	public static function neq(x:Complex, y:Complex):Bool { // "!="
		return (x.real != y.real) || (x.imag != y.imag);
	}

	public static function toString(x:Complex):String {
		return Std.string(x.real) + "+" + Std.string(x.imag) + "i";
	}
}
```

**Comment by elliott5** [comment]
Looking at the `IntegerTypeInt` code I was very surprised to see all of the binary operators, as I would expect these to be in the abstracts for the specific integer types (like `int8`) themselves.

I was expecting the code more like https://try.haxe.org/#c77D2576 , with only `@:to` functions in `IntegerTypeInt`. The Haxe compiler will work out which conversion to do in order to make the types correct on a binary operation (as shown in the example).

The only binary operations `IntegerTypeInt` might need are with other `IntegerTypeInt` values in order to create compound constants.

**Comment by elliott5** [comment]
I'm afraid I still think it would be better to for `IntegerType` to be based on Haxe `Int64` while you are getting it working, then maybe optimise to `Int` later.
In particular this is because two `Int` constants added or multiplied together could overflow into an `Int64`.
But also because you will save some time while getting it working.

**Comment by PXshadow** [comment]
Oh shoot, thank you for telling me! I will change the complex numbers straight away sorry about that, I somehow didn't comprehend that complex numbers are floats. For the complex64 can it just be shortcuted and use a single float64? or does the Go code allow the refrencing of the real and imaginary parts?

> Looking at the IntegerTypeInt code I was very surprised to see all of the binary operators, as I would expect these to be in the abstracts for the specific integer types (like int8) themselves.

Yeah you're right your example seems to work very well, I wasn't able to get it working at the time before but seeing that I defiently prefer your approach more.

And you're also right that IntegerType should just be an Int64 the optimization is hardly anything now that I know the innerworking of the high/low system better, and it's much quicker to get working.

I'll get straight to work using your code as a refrence for complex128, I really apperciate your help pointing out these errors, and I hope I have not scared you to badly, thank you for your patients.

**Comment by elliott5** [comment]
I'm afraid a `complex64` cannot be put inside a `float64`, it requires two `float32` variables to represent the real & imaginary parts of a complex number.

**Comment by elliott5** [comment]
Complex code from TardisGo above using a generic type would allow for both very easily, something like:
```
typedef Complex64 = Complex<Float32>;
typedef Complex128 = Complex<Float64>;

class Complex<T> {
	public var real:T;
	public var imag:T;

	public function new(r:T, i:T) {
		real = r;
		imag = i;
	}

        //... as in TardisGo
}
```

I've not tested the above code, so the Haxe may be incorrect!

**Comment by PXshadow** [comment]
I've used this code and it seems to be working, I still have a lot to implement and figure out for creating the Complex numbers with the builtin functions as well as how the type assertion from a float or int to a complex works. Must numbers seems to have most of the spec done. One of the main ones that still needs alot of work will be UInt64s and potentially UInt32 if I don't want to represent them as Int64 and instead an Int32. My idea for UInts is to have them be able to be parsed as String as they can be over the int32 limit, and then represent them as a type of controlled overflow internally, and they getting exported out can be modified to correctly fit the type asserted.

**Comment by elliott5** [comment]
Uint and Int addition/subtraction arithmetic is exactly the same, the only way they differ is in how you interpret the resulting bit-pattern. But some operations need to be different for Uint, including: 
- less/greater than comparisons, (not)/equal are the same
- `*`, `/`, `%`
- right shift operations (always insert 0)
- encoding in-to and out-of string representation (as you suggest)

The TardisGo code to do some of this:
- `uint` comparison function is at https://github.com/tardisgo/tardisgo/blob/master/haxe/haxeRuntime.go#L296
- `/` https://github.com/tardisgo/tardisgo/blob/master/haxe/haxeRuntime.go#L333 note that the `sv` parameter is `0` if an unsigned division is required, otherwise it gives the length of the types being divided in bytes to handle the special Go processing required at https://github.com/tardisgo/tardisgo/blob/master/haxe/haxeRuntime.go#L313
- `%` likewise at https://github.com/tardisgo/tardisgo/blob/master/haxe/haxeRuntime.go#L313
- `*` special processing only required for some targets at https://github.com/tardisgo/tardisgo/blob/master/haxe/haxeRuntime.go#L352

**Comment by elliott5** [comment]
And for `uint64` in TardisGo:
- `/` https://github.com/tardisgo/tardisgo/blob/master/haxe/haxeRuntime.go#L2096
- `%` https://github.com/tardisgo/tardisgo/blob/master/haxe/haxeRuntime.go#L2129
- comparison `Haxe.Int64.ucompare()`

**Comment by elliott5** [comment]
Extract from https://golang.org/ref/spec on *integer operators* explaining the special processing described above:
《
For two integer values x and y, the integer quotient q = x / y and remainder r = x % y satisfy the following relationships:
```
x = q*y + r  and  |r| < |y|
```
with x / y truncated towards zero ("truncated division").

...

The one exception to this rule is that if the dividend x is the most negative value for the int type of x, the quotient q = x / -1 is equal to x (and r = 0) due to two's-complement integer overflow:

```
                x, q 
 int8        -128 
 int16      -32768 
 int32     -2147483648 
 int64    -9223372036854775808 
```
》

**Comment by PXshadow** [comment]
Thank you for the info this is very helpful, These are the best cheats I could possibly ask for to work on the clamping and finishing support of the numbers. I hope to get all of the numbers functioning properly soon.

**Comment by elliott5** [comment]
Following update f4837dde5a53fb6fd8c1f54b14ea380b7059089c ...

The first example in this issue works, but add one to the second number and it does not:
```
func main() {
	a := uint8(255)
	b := uint8(2)
	fmt.Println(a + b) // go2hx prints 0, go prints 1
}
```

**Comment by elliott5** [comment]
The four `clamp` functions at https://github.com/PXshadow/go2hx/blob/a4809b913a45146ee48b77a719a11b43e9970917/stdgo/StdGoTypes.hx#L83 were altered (https://github.com/PXshadow/go2hx/commit/f4837dde5a53fb6fd8c1f54b14ea380b7059089c) to set the underlying `Int` value to 0 when out of range.

This is incorrect behaviour (as described above) they should "clamp" the underlying value to be within the permitted range, as the previous version of those functions (copied from TardisGo) did.

Also, the function `clampUInt` should not exist, as both `Int` and `UInt` have the same bit-pattern range, it is just their range is interpreted differently depending on whether they are seen as one or the other.
For example, a 32-bit value value of 0xFFFFFFFF means:
- -1 if it is an `Int`; or
- 4,294,967,295 if it is an `UInt`.

**Comment by PXshadow** [comment]
Reverted the clamp functions back, I was doing binop tests and thought they had to be zero but it's fully passing with the changes reverted, so my apologies, and thank you.  As for the UInt clamp you are right and it makes sense, however I'm unsure how to properly allow the overflow into an unsigned int. For instance:
```go
var x uint = 4294,967294 + 1
```
how does the compiler figure out that it will now overload to -1? Thanks for all of the help!

**Comment by elliott5** [comment]
Well done. I'm glad the tests are passing. :)

To illustrate how UInt works in Haxe, I've written - https://try.haxe.org/#6074498C
This works as I would expect in `neko` and `hl` but fails in `JavaScript`.

**Comment by PXshadow** [comment]
Thank you yes me too with regards with the Tests, it's very nice seeing the spec get more and more supported! Thank you for the write up, I am a little confused by it though I thought ``4294967294+3`` = 1 would be negative and less then ``4294967294`` = -2 because of the negative overflow.  The string parsing makes sense as the number is to big to be held as only a postive integer with max range. To sumarize what I'm expecting in code and want to replicate in Haxe code:

```
func main() {
	var x uint = 4294967294
	fmt.Println(x + 1) //string = 4294967295, underlying value = -1
	fmt.Println(x + 2) //string = 4294967296, underlying value = -2
}
```
I'm probably missing something, I apologize if it's quite obvious, apperciate any feedback.

**Comment by elliott5** [comment]
I'm afraid the last line of your Go code is wrong @PXshadow .

4294967296 is one larger than the largest `uint32` value, so in Go it wraps to 0. Just as  `int32`-1+1=0. 

You can see a slightly adapted version of your code running at https://play.golang.org/p/k9mdS38csGS

**Comment by elliott5** [comment]
You may be interested to know that the 32-bit-pattern `0x80000000` 
- as an `uint32` =  2147483648 
- but as an `int32` is its largest negative value  = -2147483648

...and if you take one away from that 32-bit value?
- `uint32`  2147483648 -1 = 2147483647  
- `int32` -2147483648 -1 = 2147483647  
...the `int32` flips from its most negative value to its most positive value, and both are equal!

```
		x := uint32(0x80000000)
		y := int32(x)
		fmt.Println("uint32", x, "int32", y)
		fmt.Println("uint32", x-1, "int32", y-1)
```

**Comment by PXshadow** [comment]
uint32 and uint64 need some love. Need at the top of priority list, however they are important for key things in the future I suspect.

**Comment by jayvdb** [comment]
fwiw, py2many has started implementing something similar, iiuc, but failing when incompatible types are used at https://github.com/adsharma/py2many/blob/a1324a9/py2many/inference.py#L267 , with some very basic tests at https://github.com/adsharma/py2many/blob/d5ef9c3/tests/test_unsupported.py#L162 .  It looks like this issue here provides some good ideas for new tests and likely would find cases the existing py2many code doesn't detect incompatibilities.

**Comment by PXshadow** [comment]
> fwiw, py2many has started implementing something similar, iiuc, but failing when incompatible types are used at https://github.com/adsharma/py2many/blob/a1324a9/py2many/inference.py#L267 , with some very basic tests at https://github.com/adsharma/py2many/blob/d5ef9c3/tests/test_unsupported.py#L162 .  It looks like this issue here provides some good ideas for new tests and likely would find cases the existing py2many code doesn't detect incompatibilities.

Glad the write up is of use again. I could help write some tests for tricky number parts inspired by the golang spec that I imagine get handled differently across languages for py2many.

**Comment by PXshadow** [comment]
> > fwiw, py2many has started implementing something similar, iiuc, but failing when incompatible types are used at https://github.com/adsharma/py2many/blob/a1324a9/py2many/inference.py#L267 , with some very basic tests at https://github.com/adsharma/py2many/blob/d5ef9c3/tests/test_unsupported.py#L162 .  It looks like this issue here provides some good ideas for new tests and likely would find cases the existing py2many code doesn't detect incompatibilities.
> 
> Glad the write up is of use again. I could help write some tests for tricky number parts inspired by the golang spec that I imagine get handled differently across languages for py2many. @jayvdb

**Comment by PXshadow** [comment]
Been looking at uint32 and uint64 support again. I tried to figure out how [int64 works in Haxe](https://github.com/HaxeFoundation/haxe/blob/4.2.1/std/haxe/Int64.hx) I have a little bit better of a grasp but I'm currently pretty weak on bit operations and can't figure out how to correctly modify int64 to become uint64, any advice or help would be very useful. cc @elliott5

**Comment by elliott5** [comment]
I think these posts I made on the topic of `uint64` should give you a starting point: https://github.com/go2hx/go2hx/issues/26#issuecomment-808882068

Let me know if you need more.

**Comment by elliott5** [comment]
Excellent news overall @PXshadow. 

Although the `Haxe/cpp` code shows that `UInt8/16/32/64` as all abstracts over `int`, maybe the generated code does use the [correct underlying types](https://en.cppreference.com/w/cpp/types/integer), testing would be required to determine this.

**Comment by PXshadow** [comment]
Multiple std math pkg tests are now passing. A new issue can be created for using native number types for hxcpp for instance.
