### ISSUE TITLE
pointer, indexing from another pointer, not working correctly

### ISSUE THREAD

**Issue by elliott5** [go2hx/go2hx#28]
```
package main

import "fmt"

var a = []string{"", "the same value", "the same value"}

func main() {
	p1 := &a[1]
	p3 := &a[2]
	fmt.Println(p1 == P2(&a), P2(&a) == p3) // Go=false,true go2hx=false,false
}

func P2(b *[]string) *string {
	return &(*b)[2]
}
```

**Comment by elliott5** [comment]
It looks like you are making great progress on this @PXshadow .

Another minor problem, if the names are changed to 
```
	p1 := &a[1]
	p2 := &a[2]
	fmt.Println(p1 == P2(&a), P2(&a) == p2) 
```
The `p2` and `P2()` names clash, because the name of the function has been changed to `p2()`.

This using build `251fddc1fba48ad6d4cada8929de1a0d3daa37cd`.

**Comment by PXshadow** [comment]
Yeah a seperate issue would be great, I've defiently struggled a decent amount figuring out a good system for name clashing and how to adress depending on the scope and type. I think it will pay off in the long run of turning idents to the Haxe style. The pointers I still have a few more cases and types I need to go through and make sure it can properly detect equivlant values even with tricky aliasing, I appericate the examples 😃

**Comment by PXshadow** [comment]
I think this can be closed.
