### ISSUE TITLE
Public Go API names in hx2go need to be standard, so that existing Go documentation can be used

### ISSUE THREAD

**Issue by elliott5** [go2hx/go2hx#29]
Altering Go naming really should be a last resort, both because:
- the Go API documentation is superb and hx2go programmers should be able to use it directly; and because
- the Go code already has unique names, so changing those names stands the chance of names clashing (as in #28).

For example, look at a `.Next()` method in the Go documentation for accessing `.tar` files:
https://golang.org/pkg/archive/tar/#Reader.Next

Now notice that in the implementation of the `.Next()` public API, uses a private API called `.next()`.
https://golang.org/src/archive/tar/reader.go?s=1315:1356#L37

This is a very common Go design pattern, behind the public API `.Abc()` is a private API `.abc()`.

**Comment by PXshadow** [comment]
@elliott5 okay a standard methodology could be achieved then, the issue with keeping uppercase variables and functions is it messes up the syntax highlighting for editors, perhaps if everylowercase instance would result in an undercase and then the name and then uppercase names would just become lowercase. Also type names have to become uppercase regsrdless, so name changing no matter what is necessary. Would be curious what standard you would like to see. Also with the godocs I agree its vital that they stay able to be used, that's why I prefer to prioritize a better naming convention for exported names where as unexported has the greater name modification done to it.

**Comment by elliott5** [comment]
Yes, I think `Next -> next` for the Go public API naming and `next -> _next` for private variables will work... but there will be a lot of _leading _underscores in the code!

Go public type names will always have a Capital letter 1st anyway, for private names you could always preface them with `T_`.

**Comment by PXshadow** [comment]
More edge case tests are probably needed for the renamer, Private classes could also be prefaced with an underscore, ``T_`` works as well though. As for the _leading_underscores everywhere, yeah I want to avoid that if that's at all possible, I think a decent system is just patching cases and then having a hard fallback if needed.

**Comment by PXshadow** [comment]
Current system in place I think is sufficent, summary: all variables/function names are turned lowercase, all type names uppercase. If a name conflict occurs the renamer changes out the unexported name adding a leading underscore. Therefore all library documentation will only ever be diffrent for function/variables and it will be lowercasing them as in the Haxe style.

I think this should cover the issue, if there is cases where the naming does not work properly feel free to open another issue.

**Comment by elliott5** [comment]
It would probably be worth writing out the rules in full (including reserved word handling) and putting them in the `readme.md` file so that users can see them up-front, to avoid confusion.

Eventually they will need to go into the project wiki, when it is time to build that.

**Comment by PXshadow** [comment]
> It would probably be worth writing out the rules in full (including reserved word handling) and putting them in the `readme.md` file so that users can see them up-front, to avoid confusion.
> 
> Eventually they will need to go into the project wiki, when it is time to build that.

That's a great suggestion, I can probably start on the wiki, there is quite a bit to cover that would make the readme way to massive such as Haxe versions, externs, end target generation etc.
