### ISSUE TITLE
GopherJS handling of goto

### ISSUE THREAD

**Issue by elliott5** [go2hx/go2hx#32]
I see from the part-generated code for `goto` in go2hx that you are thinking of using functions, that was my first thought too. 

As a cross-check, I thought it would be helpful to see how GopherJS did it...

I took the example of a Go `goto` program from https://www.tutorialspoint.com/go/go_goto_statement.htm

Set up GopherJS on a virtual machine (it now requires an old version of Go), and inspected what was generated.

GopherJS uses a case statement to implement `goto` (but also `for`) ... so the Go code:
```
func main() {
	var a int = 10
LOOP:
	for a < 20 {
		if a == 15 {
			a = a + 1
			goto LOOP
		}
		println("value of a:",a)
		a++
	}
}
```
...generates this JS:
```
	main = function() {
		var a, $s;
		/* */ $s = 0; s: while (true) { switch ($s) { case 0:
		a = 10;
		/* LOOP: */ case 1:
		/* while (true) { */ case 2:
			/* if (!(a < 20)) { break; } */ if(!(a < 20)) { $s = 3; continue; }
			/* */ if (a === 15) { $s = 4; continue; }
			/* */ $s = 5; continue;
			/* if (a === 15) { */ case 4:
				a = a + 1 >> 0;
				/* goto LOOP */ $s = 1; continue;
			/* } */ case 5:
			console.log("value of a:", a);
			a = a + (1) >> 0;
		/* } */ $s = 2; continue; case 3:
		$s = -1; return;
		/* */ } return; }
	};
```

I hope that helps your thinking @PXshadow , let me know if you want to see other GopherJS examples.

**Comment by PXshadow** [comment]
This is incredibly helpful thank you @elliott5 ! Yes I'd love to see other examples like this. Its extremly useful for implementation seing equivalencies to compare and contrast.

**Comment by elliott5** [comment]
GopherJS only puts the code inside a `switch/case` statement when necessary:
```
func main() {
	sum := 0
	for i := 0; i < 10; i++ {
		sum += i
	}
	println(sum)
}
```
generates 
```
	main = function() {
		var i, sum;
		sum = 0;
		i = 0;
		while (true) {
			if (!(i < 10)) { break; }
			sum = sum + (i) >> 0;
			i = i + (1) >> 0;
		}
		console.log(sum);
	};
```

**Comment by PXshadow** [comment]
Great, I like the approach of the switch case inside an infinite white statement it allows less temporary variables and seems to be a more understandable controlflow pattern. I'll implement it and have it where it only gets generated if necessary.

**Comment by elliott5** [comment]
The presence of a Go label in the code should trigger this alternate way of managing the control flow.

**Comment by elliott5** [comment]
The use of `fallthrough` in a `switch/case` statement should also trigger the alternate control flow, as Haxe does not allow this natively.

**Comment by elliott5** [comment]
Fun fact: in TardisGo all control flow was managed using "the approach of the switch case inside an infinite white statement".
The `nextCaseToJumpTo` value acted as a [program-counter](https://en.wikipedia.org/wiki/Program_counter) which in turn allowed the implementation of `goroutines` as [coroutines](https://en.wikipedia.org/wiki/Coroutine).

**Comment by elliott5** [comment]
... and TardisGo had goroutines before GopherJS ;)

**Comment by elliott5** [comment]
A proven way to solve the `goto` code generation issue (only for those functions that contain a `goto`) would be to use the TardisGo approach of generating code from the Go SSA static analysis https://pkg.go.dev/golang.org/x/tools@v0.1.0/go/ssa.

In the SSA form: "All looping, branching and switching constructs are replaced with unstructured control flow." TardisGo implemented this using a `switch` statement on an integer program counter showing which block was next.

This could be achieved either:
- by generating Haxe directly from the SSA form (as TardisGo did); or 
- by re-writing the Go functions containing `goto` into valid  Go that uses SSA-style "unstructured control flow" in the Go part of Go2hx, then presenting an AST tree that does not include any `goto` statements to the Haxe part of Go2hx.

With more work, this same approach could also be used to implement `goroutines` as co-routines, if required. Since, only those functions containing a potential context switch (`go` and `chan` operations are the most obvious), or which call such functions, need to be in the SSA control-flow format (that can be suspended as part of a context-switch).

**Comment by PXshadow** [comment]
> by re-writing the Go functions containing goto into valid Go that uses SSA-style "unstructured control flow" in the Go part of Go2hx, then presenting an AST tree that does not include any goto statements to the Haxe part of Go2hx.

I like this approach more, a type of new context for gotos to operate it, a little bit in a way how the recover system well from what I understand where extra code gen is added when recover/goto as presented.

> With more work, this same approach could also be used to implement goroutines as co-routines, if required. Since, only those functions containing a potential context switch (go and chan operations are the most obvious), or which call such functions, need to be in the SSA control-flow format (that can be suspended as part of a context-switch).

Yes that would be amazing! I've been following [pecan](https://github.com/Aurel300/pecan) closely which is a macro based coroutine approach. In the future it could be added to go2hx or Haxe will eventually get native coroutines in the language. Also pecan implements gotos with jump labels using a macro approach which I like.

I'm not opposed completly to using SSA for parts, if things can be done faster using it and get this compiler working in an alpha state.

**Comment by elliott5** [comment]
As pecan has support for `goto` functionality (https://github.com/Aurel300/pecan/blob/e075482e1d8a70c46b226bdd3a83d4e4dede91fe/test/test/TestCoroutine.hx#L709) it would be worth exploring that option as a way to implement `goto` in Go2hx. What is missing from the example is a `self.goto("label")` inside the function.

It would be great if it could be used for goroutines too, but that depends on the functionality of pecan's equivalent to Go channels (https://aurel300.github.io/pecan/features-io.html) matching what Go requires.

Obviously, it would be even better if the Haxe core team were to implement this functionality.

**Comment by PXshadow** [comment]
The example goto code linked above is not a decent test case because no goto functionality gets the same result I have come to realize.

My current self made example is this: 

```go
func main() {
	for x := 0; x < 10; x++ {
		for y := 0; y < 10; y++ {
			println(x, y)
			if x == 5 && y == 7 {
				goto jump
			}
		}
	}
jump:
	println("ok")
}
```

here is the gopherjs generation for it:

```js
var x, y, $s;
		/* */ $s = 0; s: while (true) { switch ($s) { case 0:
		x = 0;
		/* while (true) { */ case 1:
			/* if (!(x < 10)) { break; } */ if(!(x < 10)) { $s = 2; continue; }
			y = 0;
			/* while (true) { */ case 3:
				/* if (!(y < 10)) { break; } */ if(!(y < 10)) { $s = 4; continue; }
				console.log(x, y);
				/* */ if ((x === 5) && (y === 7)) { $s = 5; continue; }
				/* */ $s = 6; continue;
				/* if ((x === 5) && (y === 7)) { */ case 5:
					/* goto here */ $s = 7; continue;
				/* } */ case 6:
				y = y + (1) >> 0;
			/* } */ $s = 3; continue; case 4:
			x = x + (1) >> 0;
		/* } */ $s = 1; continue; case 2:
		/* here: */ case 7:
		console.log("ok");
		$s = -1; return;
		/* */ } return; }
```

I think the gopherjs one although it gets the result, is somehow way more complicated then the goto system.
I'm currently working on trying to achieve the result of keeping the same control flows by building up a system to break out of for/while loops before jumping to the label with the while/switch method. Maybe a sophisicated macro would be better and keep better readbility in Haxe?

Any thoughts on where to take this would be helpful cc @elliott5

**Comment by elliott5** [comment]
The code GopherJS generates is what I was expecting, with `$s` acting as the programme counter. 

As discussed, although the generated code is ugly, I  know it works in the general case.

If you can find a way to generate this code more elegantly, using Haxe macros, that would be great!

**Comment by PXshadow** [comment]
I think I've managed to figure out a decent approach how to do it, the one part I don't quite know about at the moment, is local variable scoping. When should a variable be outside of the main while loop, and when should it be within the case expr?

**Comment by elliott5** [comment]
Local scoping of variables is certainly an issue, as you suggest.

Any variable that is declared other than at the function level needs special handling:
- declared at the function level, but with an auto-generated name that reflects the block it is declared in; and
- re-initialised every time the block it is declared in is entered.

**Comment by PXshadow** [comment]
Thanks for the insight, I think it's dealing with the variable declarations and assigning properly now, It passes the two goto tests for yaegi, feel free to try it out and see if you can find any short comings with it @elliott5

**Comment by PXshadow** [comment]
Closing this as the goto system seems to be working 🤞
