### ISSUE TITLE
Transpile Fmt stdlib into Haxe sucessfully and passing the tests

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#34]
The fmt formatter for Go is pretty sophiscated, currently go2hx was using a modified Haxe library that simulated the formatter for c, however Go has alot of extra features and requirements on top of C's fmt, I think it would be a good idea to eventually get Fmt to transpile properly into Haxe code for use in ``stdgo``

**Comment by elliott5** [comment]
This will be a lot of work @PXshadow, but will be a real breakthrough, because so much native Go uses `fmt` (often just to format strings) and so much of `fmt` is built on `reflect`.

**Comment by PXshadow** [comment]
duplicate #153
