### ISSUE TITLE
NaN integer conversion

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#37]
```go
func main() {
	var nan float32 = 0
	nan /= 0
	println(nan, int32(nan), int64(nan))
}
```
``return: NaN -2147483648 -9223372036854775808``

Not sure how to produce this without hard setting the conversions. Or should it even be reproduced? Currently one of Tinygo's tests relys on [this](https://github.com/tinygo-org/tinygo/blob/release/testdata/float.go#L44-L46).

**Comment by elliott5** [comment]
Go prints `NaN -2147483648 -9223372036854775808`.

GopherJS prints `NaN 0 0`.

In terms of the underlying bit pattern for `NaN` inside 32 or 64 bits, it is completely logical for it to map to a valid `int32` and `int64` value.

So I think you should add a special case for `float32/64` with the value `NaN` when cast to `int32/64`.

That will allow the TinyGo test to pass and may also be behaviour relied upon by other parts of the Go ecosystem.

**Comment by PXshadow** [comment]
Confirmed working with the passing of multiple std math tests that check correct implementation of NaN
