### ISSUE TITLE
Known reflect prototype issues

### ISSUE THREAD

**Issue by elliott5** [go2hx/go2hx#42]
As regards my first pull request #41: 

Only the `Type` side of reflect has been started, no work yet on the `Value` side.

The `Type` system only works fully for simple types with a textual name in the interface and for named types based on a struct, where a Haxe class is created which has had `@:rtti` metadata created.

Named types not based on a struct that generate code using the `@:using(haxe.path.To._MyType__extension)` are still to be worked up.

Anonymous structs work, but with native concrete Haxe types rather than Go type information based on abstract Haxe types.

Other types (array, slice ...)  have not been looked at so far.

**Comment by PXshadow** [comment]
This is great stuff, I assume the method handling for Slices/Arrays/Chans will just a recursive system for the method kind for instance. Do you need some type of transport of:

> Named types not based on a struct that generate code using the @:using(haxe.path.To._MyType__extension) are still to be worked up.

To the reflect system to have it partially handled at compile time somehow? Or potentially add ``@:rtti`` to the generated extensions Classes as well?

**Comment by elliott5** [comment]
I will look into Slices/Arrays/Chans, which should work in the same way as other basic classes.

Certainly `@:rtti` needs to be added to the extension classes.

Because it is not a named type, I think I made a mistake, reflect.Kind should not be an abstract, but rather a typedef with an extension in the same way as a normal type ... which I will change.

Then the problem becomes how to handle haxe typedef + extension class implementations of named types, which I will work on next.

I just noticed that the code you generate for a go2hx class shows which go2hx interfaces it implements, I need to implement that too as a shortcut before checking the function names+signatures (needed for non-go2hx classes).

**Comment by elliott5** [comment]
Latest PR #44 requires code generation changes to work.

Go named types need to be implemented using an abstract, to allow the correct conversion to `interface{}`, and their `__extension` class needs to contain a static `_typeName_` string to provide the name of the underlying type.

The prototype is the [`reflect.Kind`](https://golang.org/pkg/reflect/#Kind) implementation:
```
@:using(stdgo.reflect.Reflect._Kind__extension)
abstract Kind(GoUInt) from(GoUInt) to(GoUInt) {
	public inline function new(?ui:GoUInt = 0) {
		this = ui; 
	}

	@:to inline function __promote() // this is why Kind is an abstract
		return new AnyInterface({value: this, typeName: Type.getClassName(_Kind__extension)});

	@:from inline static function __fromIntegerType(i:IntegerType):Kind {
		return new Kind((i : GoUInt));
	}
}

@:rtti
class _Kind__extension {
	static final _typeName_ = "uint";

	// string must be here to enable it to be seen at runtime
	public static function string(k:Kind):GoString {
		var idx:UInt = (k:GoUInt).toBasic();
		var r = EnumTools.getConstructors(GT_enum)[idx].substr(3);
		if (r == "unsafePointer")
			return "unsafe.pointer";
		return r;
	}
}
```

**Comment by elliott5** [comment]
TypeOf array, slice, map and channel now added.

**Comment by PXshadow** [comment]
@elliott5 let me know if the code generation changes I have pushed thus far is sufficent (class extensions for all alias types and _typeName_ system that as a string holds the underlying type of the alias). Also apologies for the commits as well recently working on getting multiple files to work/proper exporting of types and I needed to quickly get it to a point where it wasn't breaking the compiler, so I could update the code generation needed for the pull request 😅

**Comment by PXshadow** [comment]
> TODO find a way to pass in field types, rather than inspect contents

Perhaps all StructTypes could take the types of their fields and put them into a seralized string to be extracted by reflect in the future?

**Comment by elliott5** [comment]
No need to do this with namedTypes, as these have the rtti data to work from. But for anonymous structs and other complex types without rtti data, that is what I'm hoping for.

**Comment by PXshadow** [comment]
Both Type and Value should be working, and ``@:rtti`` no longer applies.
