### ISSUE TITLE
New stdgo hybrid system

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#43]
The system currently relies on two datasets. ``excludes.json`` and ``stdgo.json``

Whether a module exists or does not exist in either of these lists creates 4 possibilities that map to an intended behavior of the generation.

* Excludes prevents a go package from being parsed and exported as data to then be compiled.
* Stdgo list sets whether or not a root package (example: time, os, math) will have it's exported reference as ``stdgo.Time.Duration`` instead of just ``time.Duration``

1. No stdgo Go code or Haxe.
    example: flag (should require no modifications or changes from stdgo, and as such will be handled as normal compiled Go code to Haxe)
    excluded = false, stdgo = false
2. Haxe code only
    example: os, runtime, unsafe (requires modification but only on the Haxe side and is not worth generating the Go side as it's close to a rewrite)
    excluded = true, stdgo = true
3. Go and Haxe code
    example: time, errors (requires modification of some functionality of the module in Haxe replacing some Go functions, but alot of the module does not need to be rewritten. For module level fields that name conflict with std's Go name field, stdgo's Go field will replace them, following the same system as gopherjs's [compiler native](https://github.com/gopherjs/gopherjs/tree/master/compiler/natives/src) uses)
    excluded = false, stdgo = true
    
*note* : exclude = true, and stdgo = false, can not work because excluded generated Go's std module code and then also not having a reference for the Haxe code means the module path would throw as the path would point no where.
    
With this system in place, it would allow different generation cases to match with the standard libraries module characteristics.

**Comment by elliott5** [comment]
I propose that, for `reflect` (and probably eventually other uses) every go2hx object namable in Go implements a revised https://github.com/go2hx/go2hx/blob/15f7810b56e92ad48a749576e5622dea9122ba58/stdgo/StdGoTypes.hx#L1659.

Change to:
```
extern interface BaseType {
	public var _gt_:stdgo.reflect.GT_enum;
}
```

Because the `_gt_` variable will be read at runtime, it will probably need to be implemented inside a class, rather than an abstract.

For example, `PointerData` would become:
```
class PointerData<T> implements BaseType { // altered
	public var get:() -> T;
	public var set:T->T;
	public var address:Int;
        public var _gt_:stdgo.reflect.GT_enum;  // new

	public function new(get, set, address, targetGT) { // altered
		this.get = get;
		this.set = set;
		this.address = address;
                this._gt_ = stdgo.reflect.GT_ptr(targetGT); // new
	}

	public inline function toString() {
		return Std.string("* " + get());
	}
}
```

**Comment by PXshadow** [comment]
Instead of merging Go code, I think the approach of letting Haxe handle what code to use for exported functions/types works better, it's also closer in spirit to the extern system.

**Comment by PXshadow** [comment]
implemented :)
