### ISSUE TITLE
lix: no @run directive found for library go2hx

### ISSUE THREAD

**Issue by jayvdb** [go2hx/go2hx#53]
When I follow the instructions in the readme on macos, I get this error

```
lix install https://github.com/go2hx/go2hx --global
already downloaded: gh://github.com/go2hx/go2hx#ef2a555ad8e908c003cd27fd57b14da7852dc183
-> mounted as go2hx#0.0.1
> lix run go2hx github.com/tidwall/btree
no @run directive found for library go2hx
```

Same occurs if I specify local file `./print.go`

`lix use haxe nightly` is successful.

I am very new to haxe and lix, so that is probably part of the problem.

Versions:
* lix - v15.10.1
* haxe - 4.2.0-rc.1+b37e43d

Also, I think it would be helpful if there was a section in the readme how to build from a git clone, which describes the various components (e.g. is run.n the workhorse behind go2hx?, what is go4hx? https://golangexample.com/the-go-to-haxe-transpiler/ explains them a bit) and how to run the tests and examples, for people without haxe/neko/etc experience.

I am assuming I have built the bits correctly, but without steps to follow, and CI verifying those steps work, I cant be confident.

Anyways, this is the errors I am getting atm with a local build. 

```
hl tests.hl
> parser:
ident: false test: false
/path/to/go2hx/tests/go/test/alias1.go:12:6: main redeclared in this block
unknown parse type id: Chan
... (repeats many times) ...
unknown parse type id: Chan
> typer: 3
src/Typer.hx:2091: {}
Uncaught exception: type id is null: {}
Called from _Typer.$Typer_Fields_.parseType(Typer.hx:2092)
Called from _Typer.$Typer_Fields_.typeof(Typer.hx:1934)
Called from _Typer.$Typer_Fields_.typeAssignStmt(Typer.hx:1264)
Called from _Typer.$Typer_Fields_.typeStmt(Typer.hx:676)
Called from _Typer.$Typer_Fields_.typeStmtList(Typer.hx:755)
Called from _Typer.$Typer_Fields_.typeBlockStmt(Typer.hx:741)
Called from _Typer.$Typer_Fields_.typeFunction(Typer.hx:2627)
Called from _Typer.$Typer_Fields_.main(Typer.hx:262)
Called from _Main.$Main_Fields_.init(Main.hx:59)
Called from _Run.$Run_Fields_.compile(Run.hx:66)
Called from _Run.$Run_Fields_.gen(Run.hx:60)
Called from _Run.$Run_Fields_.main(Run.hx:16)
Called from fun$1194(?:1)
```

```
hl examples.hl
> parser:
ident: true test: false
> typer: 1
> generator: 0
examples/Examples.hx:34: run libraries
> parser:
ident: true test: false
> typer: 2
src/Typer.hx:2091: {}
Uncaught exception: type id is null: {}
Called from _Typer.$Typer_Fields_.parseType(Typer.hx:2092)
Called from _Typer.$Typer_Fields_.parseType(Typer.hx:2079)
Called from _Typer.$Typer_Fields_.parseType(Typer.hx:2087)
Called from _Typer.$Typer_Fields_.parseType(Typer.hx:2085)
Called from _Typer.$Typer_Fields_.typeCompositeLit(Typer.hx:2338)
Called from _Typer.$Typer_Fields_.typeExpr(Typer.hx:1591)
Called from _Typer.$Typer_Fields_.typeUnaryExpr(Typer.hx:2171)
Called from _Typer.$Typer_Fields_.typeExpr(Typer.hx:1587)
Called from _Typer.$Typer_Fields_.typeAssignStmt(Typer.hx:1251)
Called from _Typer.$Typer_Fields_.typeStmt(Typer.hx:676)
Called from _Typer.$Typer_Fields_.typeStmtList(Typer.hx:755)
Called from _Typer.$Typer_Fields_.typeBlockStmt(Typer.hx:741)
Called from _Typer.$Typer_Fields_.typeFunction(Typer.hx:2627)
Called from _Typer.$Typer_Fields_.main(Typer.hx:262)
Called from _Main.$Main_Fields_.init(Main.hx:59)
Called from _Examples.$Examples_Fields_.gen(Examples.hx:36)
Called from _Examples.$Examples_Fields_.main(Examples.hx:10)
Called from fun$1146(?:1)
```

After running `haxe build.hxml`, and a bit of guess work, it looks like I can get go2hx running without `lix`
```
neko ./run.n /path/to/print.go
> parser:
ident: false test: false
> typer: 2
src/Typer.hx:2091: {}
Called from ? line 1
Called from Main.hx line 17
Called from Main.hx line 59
Called from Typer.hx line 262
Called from Typer.hx line 2627
Called from Typer.hx line 741
Called from Typer.hx line 755
Called from Typer.hx line 675
Called from Typer.hx line 1284
Called from Typer.hx line 1585
Called from Typer.hx line 1850
Called from Typer.hx line 2061
Called from Typer.hx line 2092
Uncaught exception - type id is null: {}
```

fwiw, print.go is https://github.com/adsharma/py2many/blob/main/tests/expected/print.go

**Comment by PXshadow** [comment]
@jayvdb My apologies you caught the project during a move to using Go's type system to start doing static typed analysis on the AST. If you could try latest version and see if it works now that'd be great (make sure to run go build . ). I also updated the README as you recomended. The project is working torwards having fmt get transpiled using go2hx so the library that used to support fmt has been stripped leaving printf currently not supported. There is also quite a bit of work still needed to support the standard library, the language spec supports most exprs and statements now though.

I also checked out your project py2many, seems very neat. Haxe language support is a good idea to increase coverage of the transpiler. I'd be happy to partner up if you would like to go the route of python -> go -> haxe, however I understand if it makes more sense to 1st step into Haxe. It does seem we have the same aims in terms of readable code generation, execution speed, unit testing and portability. Either way I look forward to seeing the progress on your project and I apperciate you taking time to attempt to try out go2hx, cheers!

**Comment by jayvdb** [comment]
The lix command works now.

It generated `golibs/command_line_arguments/Print.hx`, which was an unexpected place to put it.  Can we specify an output filename for single file go files?  The test suite, mostly https://github.com/adsharma/py2many/blob/main/tests/test_cli.py, is focused on those at the moment.  Transpiling entire projects is sort of supported, and being chipped away at https://github.com/adsharma/py2many/issues/158 .

For printgo, go2hx generated:
```haxe
package command_line_arguments;
import stdgo.fmt.Fmt;
import stdgo.StdGoTypes;
import stdgo.Go;
import stdgo.GoString;
/**

    func Show() {
    	fmt.Printf("%v\n", "b")
    	fmt.Printf("%v %v\n", 2, "b")
    	var a float64 = 2.1
    	fmt.Printf("%v\n", a)
    	var b float64 = 2.1
    	fmt.Printf("%v\n", b)
    	var c bool = true
    	if c {
    		fmt.Printf("%v\n", "True")
    	} else {
    		fmt.Printf("%v\n", "False")
    	}
    }
**/
function show():Void {
    stdgo.fmt.Fmt.printf("%v\"n", "b");
    stdgo.fmt.Fmt.printf("%v %v\"n", (2 : GoInt64), "b");
    var a:GoFloat64 = (2.1 : GoFloat64);
    stdgo.fmt.Fmt.printf("%v\"n", a);
    var b:GoFloat64 = (2.1 : GoFloat64);
    stdgo.fmt.Fmt.printf("%v\"n", b);
    var c:Bool = true;
    if (c) {
        stdgo.fmt.Fmt.printf("%v\"n", "True");
    } else {
        stdgo.fmt.Fmt.printf("%v\"n", "False");
    };
}
/**

    func main() {
    	Show()
    }
**/
function main():Void {
    show();
}
```

I think we would want to have a native Haxe transpiler eventually, but going via go2hx is likely to yield better results, and would mean we can build up a solid test suite for haxe generated output, which would help when tackling Haxe directly.

The go target of py2many isnt as advanced as some of the others, but it is ok.  I would rather be fixing the edge cases of py->go than trying to get py->hx working.

https://github.com/adsharma/py2many/pull/290 was a quick hack to explore how to get an external tool working with an intermediate native transpiler, in that case py->dart->js , in order to get our test suite active on the 'third party' transpiler (which typically ends up showing serious incompatibilities with the third party transpiler, or the generated code is ... yuck)

It does seem the aims are similar.  We are supplementing the go language with a runtime lib to avoid spewing algorithms into the generated code.  https://github.com/adsharma/py2many/tree/main/pygo/runtime .  I am guessing go2hx will be able to deal with that, but maybe you have a better solution.

A good test case is https://github.com/adsharma/py2many/blob/main/tests/expected/bitops.go .

**Comment by jayvdb** [comment]
Of our tests in https://github.com/adsharma/py2many/blob/main/tests/expected/ , go2hx fails for binit.go , bitops.go , bubble_sort.go & comb_sort.go .

**Comment by PXshadow** [comment]
> It does seem the aims are similar. We are supplementing the go language with a runtime lib to avoid spewing algorithms into the generated code. https://github.com/adsharma/py2many/tree/main/pygo/runtime . I am guessing go2hx will be able to deal with that, but maybe you have a better solution.

A runtime library is preferable compared to inlined algorithmns everywhere I agree. go2hx uses the approach of meta programming and type analysis as I discussed above. Go has language features that Haxe does not have such as destructing, multireturns etc, (Which I believe both python and go both have). We also have the added benifit of the transpiler using native parts from both language i.e Go's parsing of the AST and types, with Haxe's meta programming, printer and represenation into Haxe's native exprs and typedefs. So it may be a better solution, however I don't know how possible it is if py2many wants to be written completly in python.


> adsharma/py2many#290 was a quick hack to explore how to get an external tool working with an intermediate native transpiler, in that case py->dart->js , in order to get our test suite active on the 'third party' transpiler (which typically ends up showing serious incompatibilities with the third party transpiler, or the generated code is ... yuck)

I think Haxe vs dart for js generation, Haxe should do quite well you can take a look [here](https://try.haxe.org/#11357c93) build+run and then look at the JS source.

> Can we specify an output filename for single file go files? The test suite, mostly https://github.com/adsharma/py2many/blob/main/tests/test_cli.py, is focused on those at the moment. Transpiling entire projects is sort of supported, and being chipped away at adsharma/py2many#158 .

The current tests not passing are using go libraries which entails the output of more then one file, I can work on a system to export out go libraries into Haxe libraries to be used similar to dts2hx. That should allow single file output. I'll have the details soon and work torwards passing the last few tests of the suite.

**Comment by PXshadow** [comment]
@jayvdb in order to fix the tests for go2hx I cloned py2many and ran the Go tests unfortuntatly binit.go , bitops.go , bubble_sort.go & comb_sort.go, are not passing. It'd also help to know how you are calling go2hx for the tests, as these 3 tests use go libraries yet there is no go.mod refrencing the libs. Let me know if I'm missing anything, thanks.

**Comment by jayvdb** [comment]
Those tests all pass for go in our CI. We manually install the deps per https://github.com/adsharma/py2many/blob/main/.github/workflows/main.yml#L39

I would want to be calling `go2hx` like `go2hx <args> print.go` , and the runner can also supply an arg like `--output print.hx` to dictate the file.  That part goes in the py2many/cli.py , c.f. https://github.com/adsharma/py2many/pull/290 

Then test_cli invokes the test cases, on Python and the target language, and requires identical output.  COMPILERS and INVOKERS are defined in the test rig for that. https://github.com/adsharma/py2many/blob/main/tests/test_cli.py#L24

It doesnt matter if some of the tests dont work.  The test rig automatically ignores a test case if the expected generated file doesnt already exist, i.e. hasnt been checked in.  And we can even checkin failing cases, with an addition to the `EXPECTED_*_FAILURES` at https://github.com/adsharma/py2many/blob/main/tests/test_cli.py#L60

**Comment by PXshadow** [comment]
My apologies, I apperciate the explanation that makes sense. I'll follow the main.yml setup and get the tests passing, and then work on the go2hx side thank you @jayvdb

**Comment by PXshadow** [comment]
Took a look at the progress of gettings py2many's go tests passing today, and it is currently blocked until go routines and the select statement are supported. It seems [go-iter](https://github.com/hgfischer/go-iter) and [go-cmp](https://github.com/google/go-cmp) use go routines.

**Comment by PXshadow** [comment]
Primitive go routine, select and channel support is now implemented will look into supporting both of the support libraries pymany uses for go.

**Comment by PXshadow** [comment]
stale, and btree duplicate #17
