### ISSUE TITLE
interface to struct casting

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#56]
[Haxe Between Class/Interface manual](https://haxe.org/manual/type-system-unification-between-classes-and-interfaces.html) shows that something such as: 
```go
ne := err.(*strconv.NumError)
```
where err is of error type, and strconv.NumError is of struct type is not possible in vanilla Haxe.

Not sure how to get this to work with macros.

**Comment by elliott5** [comment]
`strconv.NumError` should not be a struct type, is should be a named type. The  (abridged) type of `err` should be `GT_NamedType("errors.Error",GT_Ptr(GT_NamedType("strconv.NumError",GT_Struct...)))`

A type assertion like this should first check the interface named type contains the instance named type, if not panic, if so use Haxe to cast the interface value (a Haxe `Any`) to the Haxe class that implements the instance named type.

**Comment by PXshadow** [comment]
Update! All interfaces now have a __underlying__ method to retrieve an AnyInterface, I'm pretty sure this is an idea you had. It works extremly well and nicely fills in the rest of the conversion situation. The named type system was hard for me to grasp for a while but I think I get it now, a named type differs from its underlying by the fact that it can have implicit interfaces and recv methods. The explanation for functionality helped alot as well, casting is being detirmined to be safe or not if destructing is involved. I'm more optimistic then I've ever jabe been with the compiler, introducing go type info has made it so much easier to make progress, no more wild macro systems to get around not knowing types. Looking forward to showing you the results soon.

**Comment by elliott5** [comment]
Excellent news @PXshadow !
