### ISSUE TITLE
Unsafe Pointer

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#60]
pointer <-> unsafe pointer
uintptr <-> unsafe pointer

uintptr conversion not sure if it is possible in Haxe as it requires the element to have no reference for the garbage collector.  Currently left with 2 ideas.

1. [Static analysis](https://pkg.go.dev/golang.org/x/tools/go/pointer) should be able to work with simple conversions from uintptr to unsafe Pointer, however the more complicated the harder the problem, such as field offsets, wild pointer arithmetic etc.

2. Serializing, if during serialization to serialization the value changes the address would no longer be correct however, now that I write this it would be possible to have a Pointer update the global map of its address if it exists and reserialize it, could potentially be very slow but it would work! I'll work on that method for now.

The unsafe Pointer work is to get the TinyGo test reflection passing, it is currently running, some basic unsafe pointer logic is needed however in order to complete it.

**Comment by elliott5** [comment]
A Go `unsafe pointer` is an intermediate form to allow a chunk of memory created with one data layout to be re-interpreted with another data layout.

TardisGo did this by actually having Haxe objects as byte arrays, with the fields accessed as offsets into them. So a TardisGo pointer consisted of two parts in Haxe: the byte-array object and the offset within that byte-array. In TardisGo, an `unsafe pointer` was just a pointer where the underlying data-layout was undefined. This made implementation trivial. In TardisGo a `uintptr` was a pair of `uint32` values, the high order one was a reference to the Haxe object, the low order one the offset.

One idea to consider, if `go2hx` is not bound by Go's memory layout (as TardisGo was, described above), is that Go `uintptr` perhaps does not have to be implemented as an integer, it has to be implemented as something that can be cast to-and-from an integer (possibly with special conversion rules), for example a Haxe `Dynamic`.

**Comment by PXshadow** [comment]
> One idea to consider, if go2hx is not bound by Go's memory layout (as TardisGo was, described above), is that Go uintptr perhaps does not have to be implemented as an integer, it has to be implemented as something that can be cast to-and-from an integer (possibly with special conversion rules), for example a Haxe Dynamic.

That is a very clever idea, an abstract with an underlying dynamic would work very nicely and fits the criteria, you're totally right I'll take this approach thank you @elliott5 !

**Comment by PXshadow** [comment]
The approach above was taken and this issue is resolved.
