### ISSUE TITLE
Simple Go Library Bundles

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#67]
A categorized bundle of Go libraries curated by the go2hx compiler team. Allows the compiler to begin producing propositional value, without the compiler meeting spec compliance yet.

*Here is a mockup for a postcard design to showcase off the graphics bundle 1.0 in the future.*

![go2hx_graphics_bundle_1 0](https://user-images.githubusercontent.com/9813078/128456972-d165e09e-af80-4258-afdd-5fe410ac9426.png)

**libs:**

* [triangula](https://github.com/RH12503/Triangula)
* [physarum](https://github.com/fogleman/physarum)
* [fauxgl](https://github.com/fogleman/fauxgl)

I took inspiration from [armory3d](https://github.com/armory3d/armory) which creates nice showcase images for updates. For a compiler I think the only tangible way to do this is to showcase off working libraries therefore library bundles.

### Ideas for other bundles

* ASCII
* web formatters, js compression/ css precompiler etc
* unicode text processing
* data structures
* image manipulation, image resizing, background removing etc

cc @elliott5 I'd be interested to hear your first impressions and wisdom.

**Comment by elliott5** [comment]
This is a great idea of course @PXshadow, visual images attract attention at a visceral level in a way that words cannot. 

I searched the 3 graphics libraries for "go " and discovered that both [physarum](https://github.com/fogleman/physarum/search?q=%22go+%22) and [fauxgl](https://github.com/fogleman/fauxgl/search?q=%22go+%22) use goroutines. But `triangula` does not seem to use goroutines, so is a good candidate.

Beyond beautiful images, doing boring stuff reliably is also really useful. 

In addition to your excellent suggestions, I would add a personal favourite: https://github.com/microcosm-cc/bluemonday

> bluemonday is a HTML sanitizer implemented in Go. It is fast and highly configurable.
> 
> bluemonday takes untrusted user generated content as an input, and will return HTML that has been sanitised against an allowlist of approved HTML elements and attributes so that you can safely include the content in your web page.
> 
> If you accept user generated content, and your server uses Go, you need bluemonday. 

I suspect that many other useful repurposing opportunities exist.

**Comment by PXshadow** [comment]
@elliott5 Thank you for the feedback. Bluemonday looks very nice, I'd be happy to prioritize supporting it. If you'd like I'm interested in you expanding on what you mean with regards to "many other useful repurposing" also if you have any other suggestions for libraries to test initally feel free to post more. Also I agree with your sentiment on the compiler doing boring stuff reliably also being useful, This bundle idea is not grounded untill the compiler is able to do much more of that boring stuff 😄

**Comment by elliott5** [comment]
It might be best to ask potential users of `go2hx` to add to this thread and say what Go library they would like to use from Haxe. This would need an explanation and link from `readme.md`.

**Comment by PXshadow** [comment]
Hey @sonygod I know you are looking for support with [jsonparser](http://github.com/buger/jsonparser) and [btree](github.com/tidwall/btree) is there any more libraries you would like to see support for in the short term?

@chloe_cdq I remeber you were doing Go -> Haxe -> C++ was there any libraries that you wanted to use as well from Go besides I except the standard library?

**Comment by sonygod** [comment]
thank you @PXshadow ,what's stuatus of this project? here list want libs.

**base project**

[sqlite](https://github.com/mattn/go-sqlite3)

[mysql](https://github.com/go-sql-driver/mysql)

[websocket](https://github.com/gorilla/websocket)

[async ](https://github.com/Azure/go-asynctask)



**block chain project** 


[swarm bee](https://github.com/ethersphere/bee)

[ipfs](https://github.com/ipfs/go-ipfs)

useful lib   in chinese

https://learnku.com/articles/41230

**Comment by PXshadow** [comment]
Hey @sonygod thanks for the list! I see the article if I understand correctly translates the [awesome-go repo](https://github.com/avelino/awesome-go)

The quckist library from that list to get supported will probably be "mysql" the others use cgo and so are more long term.

As for the status of the project. No cgo support, no goroutines, no automatic translatation of the standard library yet. What is supported is almost all control flows except fallthrough, a subset of reflect, most numbers binary operations, most statements and exprs. The main task being worked on right now is finishing up the test runner and going through the golang and yaegi test suites.

**Comment by PXshadow** [comment]
All of @sonygod listed libraries will be added into a list and the go2hx github action will track the progress of when the underlying stdlibs will be supported and therefore the libraries too. Track the progress on the lib tracker here #154
