### ISSUE TITLE
Memory over consumption

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#68]
After about 100 tests are run via the TestRunner the program is holding at least 8 gigabytes of ram, some issue of not freeing resources is going on and has to be resolved in order to get the runner to go through the entire yaegi TestSuite in one go.

The current test runner works by spawning 4 go4hx (go portion of the compiler) processes and has them connect to a locally hosted tcp server, the server then accepts the connections and each time a compile function is invoked the arguments are passed as a socket write and then read by the go4hx client front end compiled and then outputted as json via a socket write to the server.

go2hx (the server) takes the json, converts it into typed export data and runs it through the typer and the typer's results are run through the generator that generates Haxe files, after that an onComplete function is invoked and a Haxe compiler process is spun up to execute the code that is connected to a local Haxe cache/completion server, a Timer is created to check the exit code of the Haxe execution process and when done calls the test adapter and decrements a tests left int, when that int hits 0 the client and server are closed along with all of the other processes.

**Comment by elliott5** [comment]
Glad to hear that the impressive-sounding testing infrastructure you are building is coming on so well that you have encountered this type of problem!

Does it have the same problem when it does not run in parallel? It is always best to get the code working sequentially first, then parallelise. I suggest you put a parameter in to control the number of parallel processing streams, check it all works with `parallelStreams=1` then run tests to see what the optimum number of parallel streams is. 

An alternative approach would be to run the four stages of testing in parallel, with a queue between each stage:
1) All the Go `go2hx` runs : Go -> JSON
2) All the Haxe `go2hx` runs : JSON -> Haxe
3) All the Haxe compiler runs : Haxe -> executable
4) All the actual tests : executable -> test results

**Comment by PXshadow** [comment]
@elliott5 Thanks for the help! Setting how many processes are in parallel at a time helps massively. I've narrowed down the issue using that approach to the rerunning of the go process and not having memory be freed for each consecutive run.

I chose a socket approach over json because it was the biggest limiter for the test runner as my hard drive would be at 100% write speed.

I know benchmarks are not good to be doing at this stage but just to check for regressions I benchmarked this approach compared to json, and it's about 50-100% faster for a single run. It's nice as now it seems much more feasible for the compiler in the far distant future being a drop in replacement for the go compiler.

**Comment by PXshadow** [comment]
Here is the data from [MemStats](https://pkg.go.dev/runtime#MemStats), printing at the end of each run (program does not close for a new compiler run in order to eliminate start up time):

```
Alloc = 0 mb    TotalAlloc = 2 mb       Sys = 13 mb     NumGC = 2
Alloc = 0 mb    TotalAlloc = 3 mb       Sys = 13 mb     NumGC = 4
Alloc = 0 mb    TotalAlloc = 5 mb       Sys = 13 mb     NumGC = 6
Alloc = 8 mb    TotalAlloc = 150 mb     Sys = 117 mb    NumGC = 19
Alloc = 7 mb    TotalAlloc = 152 mb     Sys = 117 mb    NumGC = 21
Alloc = 15 mb   TotalAlloc = 297 mb     Sys = 127 mb    NumGC = 29
Alloc = 22 mb   TotalAlloc = 442 mb     Sys = 141 mb    NumGC = 35
Alloc = 21 mb   TotalAlloc = 444 mb     Sys = 141 mb    NumGC = 37
Alloc = 29 mb   TotalAlloc = 588 mb     Sys = 151 mb    NumGC = 43
Alloc = 28 mb   TotalAlloc = 590 mb     Sys = 151 mb    NumGC = 45
Alloc = 28 mb   TotalAlloc = 592 mb     Sys = 151 mb    NumGC = 47
Alloc = 28 mb   TotalAlloc = 593 mb     Sys = 151 mb    NumGC = 49
Alloc = 36 mb   TotalAlloc = 738 mb     Sys = 161 mb    NumGC = 54
Alloc = 43 mb   TotalAlloc = 883 mb     Sys = 174 mb    NumGC = 58
Alloc = 42 mb   TotalAlloc = 884 mb     Sys = 174 mb    NumGC = 60
Alloc = 50 mb   TotalAlloc = 1029 mb    Sys = 180 mb    NumGC = 64
Alloc = 57 mb   TotalAlloc = 1175 mb    Sys = 189 mb    NumGC = 68
Alloc = 64 mb   TotalAlloc = 1319 mb    Sys = 211 mb    NumGC = 72
Alloc = 63 mb   TotalAlloc = 1321 mb    Sys = 211 mb    NumGC = 74
Alloc = 71 mb   TotalAlloc = 1468 mb    Sys = 224 mb    NumGC = 78
Alloc = 78 mb   TotalAlloc = 1613 mb    Sys = 229 mb    NumGC = 81
Alloc = 85 mb   TotalAlloc = 1759 mb    Sys = 234 mb    NumGC = 84
Alloc = 92 mb   TotalAlloc = 1907 mb    Sys = 243 mb    NumGC = 87
Alloc = 91 mb   TotalAlloc = 1908 mb    Sys = 243 mb    NumGC = 89
Alloc = 91 mb   TotalAlloc = 1910 mb    Sys = 243 mb    NumGC = 91
Alloc = 99 mb   TotalAlloc = 2055 mb    Sys = 248 mb    NumGC = 94
Alloc = 106 mb  TotalAlloc = 2200 mb    Sys = 257 mb    NumGC = 97
Alloc = 113 mb  TotalAlloc = 2345 mb    Sys = 258 mb    NumGC = 100
```

**Comment by PXshadow** [comment]
Issue with test, I should run the exact same test 50+ times and use that to see if memory is being freed, using a collection of tests messes up the results because the memory can fluctuate based on how big or small it is.

Also it seems that for certain tests the data gets passed to the Haxe side and then is not freed on the Haxe side, so I am now also getting mem stats for the hashlink gc.

**Comment by PXshadow** [comment]
Found out the memory issue came from the type hasher not being cleared for each run... Yay! On the topic of memory though "net/http" takes up about 8.9 gigabytes of ram before then sending it to the Haxe side. For the moment net/http can be added to the excludes list, but it's probably a good idea in the future to send the package and even file data on demand, in order to not have such large buffers.

**Comment by elliott5** [comment]
Well done for fixing the immediate issue, and for starting to recognise and find strategies for some longer-term issues too.

**Comment by PXshadow** [comment]
No longer an issue.
