### ISSUE TITLE
some of package name was wrong .

### ISSUE THREAD

**Issue by sonygod** [go2hx/go2hx#74]
`fmt.Println(math.Sin(n))`

will print

` stdgo.Fmt.println(stdgo.Math.sin(n));`

should be 

` stdgo.Fmt.println(stdgo.math.Math.sin(n));`

and there are lot's package name should fixed

and time gen wrong code.

```
switch time.Now().Weekday() {
	case time.Saturday, time.Sunday:
		fmt.Println("It's the weekend")
	default:
		fmt.Println("It's a weekday")
	}
```

**Comment by PXshadow** [comment]
@sonygod I'm not able to reproduce try these commands and let me know if you get the same issue.

```
haxelib git go2hx https://github.com/go2hx/go2hx
```

```
haxelib run go2hx
```
Should start go2hx in REPL mode with the line starting with ``>`` for the input line.

```
fmt.Println(math.Sin(10.2))
```
**output:**
stdgo.fmt.Fmt.println(stdgo.math.Math.sin((10.2 : GoFloat64)));

**Comment by sonygod** [comment]
https://github.com/go2hx/go2hx/blob/master/stdgo/time/Time.hx

package stdgo; 

->

package stdgo.time
