### ISSUE TITLE
println pointer was wrong 

### ISSUE THREAD

**Issue by sonygod** [go2hx/go2hx#75]
```
func main() {
	i := 1

	fmt.Println("pointer:", &i)   //got 0x0  ,should be 0xc000014088  
}
```

both target  node js and hl got same result.

**Comment by PXshadow** [comment]
All pointers are simulated at the moment so any display of pointer adresses will be asthetic instead of for functionality. With that in mind @sonygod @elliott5 any prefrences for pointer display.

Current ideas for, on pointer construction:
1.  generate a random address.
2.  count up for each pointer created.
3.  same as before.

**Comment by elliott5** [comment]
I think GopherJS also uses `0x0` when casting a pointer to `uintptr`.

It has the merit of being an obviously wrong value, that no-one will think can be validly compared to anything else. 

To be a valid `uintptr` that could be used for comparison, every unique addressable entity (including fields in structures and elements in arrays) would need to be allocated a unique "address", and when a pointer is created, the  "address" required calculated and made part of the pointer. 

I'm not sure it is worth doing that yet ... but it feeds into a larger discussion about how best to model `unsafe.Pointer`.

**Comment by PXshadow** [comment]
Thanks for the insight that makes sense, ``unsafe.Pointer`` handling is later down the roadmap, and has an intersection with normal Pointers.

**Comment by PXshadow** [comment]
To just note I'm changing the toString of pointer to be this now:

```haxe
public inline function toString() {
		return "&" + Go.string(get());
}
```

It allows structs/slices/maps/arrays to properly print, I don't care much to conform to showing the pointer adress value when it's a basic type, it can be done but I think this way, 1. shows an even more clear distinction for how go2hx operates pointers compared to go, and 2. the info of the value inside the pointer is better then ``0x0``

**Comment by elliott5** [comment]
Obviously the `&pointedAtData` notation printing will not work for a self-referential `struct` (or set of related `struct` types) with non-null pointers, because of infinite recursion.

**Comment by PXshadow** [comment]
Will change this to be 0x1 for set pointers, and ``&pointedAtData`` will be cleaned up with having go2hx compile fmt.

**Comment by PXshadow** [comment]
go2hx's subset does not support pointer addresses https://go2hx.github.io/manual/subset.html#unsupported .
