### ISSUE TITLE
Robust/compliance > features/readability/scope

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#85]
### Working on the compiler I believe I've identified a few traps that have been fallen into, and how to get out and keep moving.

1. Features, having a wide range of support for parts of the compiler all over the place, because they are developed in a scattered way, the result is that the code is scattered to, rebuilding core components over and over and making it hard to fix parts of the system without breaking everything.

- The fix is planning on what parts of the compiler you will work on and keeping it within that scope, if for some reason you need to leave the scope, by very mindful and try to pull from other modules and create shared utility code.

2. Readability, spending time on systems that inevitably need to be removed because they are not robust enough, should've prioritize the higher goal of robustness over readability in the first place.

- The fix is realize readability comes only after a robust and working system, and that the readability its self needs to be robust when implementing.

3. Scope, partially supporting a large portion of the language spec and/or standard library however not taking the time to properly shelter the implementation thereby letting it rust away.

- The fix is clearly frameing what parts are protected and what are not and working on slowly growing the support rather then covering a large land area with no actual compliance.

### Actual terms of what needs to be refractored/fixed:

1. The naming system needs to be unified and follow a simple rule pattern.
2. Refractoing assignTranslate/assignEqual and the rest.
3. Unify any duplicate systems.
4. Make the compiler much more modular
5. Get rid of the hidden Reflect functions that are called modularally such as isNamed getElem etc.
6. Use a enum extract module for single case switches rather then massive switches also use the pattern matching better.
7.  Look into removing info

cc : @elliott5  Anything else I'm missing, perhaps export.go refractoring?

**Comment by elliott5** [comment]
These are all good strategies @PXshadow, but I'm currently too unfamiliar with the code to comment on the details.

**Comment by PXshadow** [comment]
Ah no worries I'll read some of the go style guides.

**Comment by PXshadow** [comment]
I'm happy with this for now.
