### ISSUE TITLE
Constant to big of number

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#86]
```go
package main

import (
	"fmt"
)

func main() {
	const tooBig = 1267650600228229401496703205376
	const huge = 1 << 100
	const large = huge >> 38

	fmt.Println(int64(large))
}

// Output:
// 4611686018427387904
```

No system in place to handle large numbers over int64 for constant.

**Comment by elliott5** [comment]
Go itself probably uses https://pkg.go.dev/math/big to achieve this.

**Comment by elliott5** [comment]
Could the Go part of `go2hx` use the `math/big` package to resolve the values of `const` declarations (including those in expressions); then pass those const values over to the Haxe part of `go2hx` in 3 forms `complex128` (includes `float64`), `uint64` and `int64`.

**Comment by PXshadow** [comment]
@elliott5 Yes to the first part with [Int.SetInt](https://pkg.go.dev/math/big#Int.SetString), the second part I don't understand the 3 forms system, is it in order to become any type on the Haxe side of go2hx? Should be possible to know the type on the go side, since that's where the information comes from for the Haxe end.

**Comment by elliott5** [comment]
Sometimes a constant can be declared globally, then used in assignments to multiple different types. That was why I suggested the 3 forms approach.

**Comment by PXshadow** [comment]
Ah I didn't know that was possible thanks for the info. I'll use the 3 form approach then, not quite sure how it will work in practice now, but I'm sure it can be figured out.

**Comment by PXshadow** [comment]
Last approach needed is a way to construct big number equivalents on the Haxe side, which is blocked until std math/big passes tests.

**Comment by PXshadow** [comment]
Constants need ``math/big`` support still.

**Comment by PXshadow** [comment]
Constants don't need ``math/big`` as they are converted at compile time and only exist in the form of a constant for documentation. It would be nice in the future to represent them using ``math/big`` it's not required.
