### ISSUE TITLE
multi file packages

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#88]
go's files at compile time esentially don't exist and instead are grouped together into a single package file. In order to replicate the style rather then the functionality.

 I implemented an ``imports.hx`` system and PkgName global name space that would declare types, unfourtantly this doesn't really work without the global name space being in a seperate package because Haxe does not allow redefining of the same type name within the same package, an example of how this would look ``stdgo.fmt.main.Fmt`` .... 
 
 So I think I just scrap the current system and focus on functionality and simplicity and mash all of the go files of a package into a single Haxe file. This should make apis easier to call and the compiler more functional and less complex. 
 
 Another step similar to the renaming rework to cut the exceptions and have clear cut rules to increase functionality. 

cc @elliott5 would be curious on what you think, and if you have any ideas for a better system.

**Comment by elliott5** [comment]
Simple is best. So merging all the generated code from a Go package into a single Haxe file is the right way forward I think. 

If you could annotate the generated Haxe code with comments giving the original Go file it was generated from, that would be helpful for the reader.

**Comment by PXshadow** [comment]
@elliott5 good idea, I believe I hid the generation of the original go code as a comment behind a flag to enable. Do you think it should be enabled by default? I chose against it at the time because it made it very hard to read through packages with large function bodies.
