### ISSUE TITLE
systematically testing std packages

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#89]
At the moment I'm unable to run ``go test math`` for instance, I'm pretty sure I was able to in the past however I don't know what setup of go is required to properly be able to test the standard library the current error being ran into is no test files being found, and if cding into the math src folder ``cpu_test.go:8:2: use of internal package internal/cpu not allowed`` relating to [internal directories rules](https://pkg.go.dev/cmd/go#hdr-Internal_Directories).

**Comment by PXshadow** [comment]
Working now, go install needs to be bootstrapped in order to be able to run ``go test math`` at least for linux/amd64.

**Comment by elliott5** [comment]
Well done for sorting this out yourself @PXshadow, an esoteric problem if ever there was one!

**Comment by PXshadow** [comment]
Thanks for the encouragement @elliott5 , yes indeed it is quite the esoteric problem, with this out of the way I'm now working on priority number 1 of getting std to pass. I'll leave the issue open as I need to test against a few more operating systems when a github action workflow is setup.

**Comment by PXshadow** [comment]
Testing against different operating system is unnecessary at this stage I find, and only really helpful, after full release, as OS specific issues are rare if coding properly to account for multiple OSes.
