### ISSUE TITLE
Target conditionals for native numerical types

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#9]
If there is a native equivlant to a number type it should replace go2hx's version.

**Comment by elliott5** [comment]
The [haxe.Int32](https://github.com/HaxeFoundation/haxe/blob/4.2.0/std/haxe/Int32.hx) implementation provides an excellent example of how a generic implementation of Go's types might be done, especially with respect to the clamp() function and high-bit extension, plus other adjustments, where required by different implementations.

What will require some work, is working-out how to use implementation-specific types in an abstraction like this.

**Comment by elliott5** [comment]
Updated a [prototype gist](https://gist.github.com/elliott5/dd7e29e7d9d48f79a5e5fd75dd7f1e2a) for the Go uint8 abstraction to use C "unsigned char" when the hl target is used (generates correct looking C code). 

```
abstract 
#if (hl)
GoUInt8(hl.UI8) from hl.UI8
#else
GoUInt8(UInt) from UInt 
#end
{
// abstract body
}
```

**Comment by PXshadow** [comment]
This is currently done, it does need to be tested more, however that can come in the future when the test suite is passing completly or near complete on one target.
