### ISSUE TITLE
Cache std library building into go2hx stdgo package

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#91]
At the moment a majority of the compile time is spent rebuilding packages that have already been built before. With the new Go interface changes coming soon (therefore no need to set implements in the std for gen code). The standard library can be generated by the compiler and then added into stdgo. 

The major question now however is where should the injection classes be as they are currently located in ``stdgo``, and then inject into the go name space, ex: ``stdgo.time.Time`` injects via macro into ``time.Time``. 

The injector macro class its self is located in ``stdgo.internal.Injector``, perhaps ``stdgo.internal.injector.time.Time``?

**Comment by elliott5** [comment]
That sounds like sensible Go-like naming.
