### ISSUE TITLE
Question: will go2hx support *.d.ts?

### ISSUE THREAD

**Issue by sonygod** [go2hx/go2hx#92]
question: will go2hx support *.d.ts? or support haxe extern?

that's may be fun if go2hx support *.d.ts to compile js.

**Comment by PXshadow** [comment]
Hey @sonygod go2hx will not support *.d.ts , I want to improve *.d.ts support for Haxe and I will do that through contributing to dts2hx. 

As for Haxe externs go2hx could support generating Go externs to link to Haxe as well as Haxe code.

It should be possible to use both dts2hx and go2hx on the javascript target once it has more testing.

If I'm missing anything from the question let me know.

**Comment by sonygod** [comment]
thank you for your reply .no more questions are current.
