### ISSUE TITLE
Go Generics 1.18

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#93]
Last missing Language feature!

The feature adds 2 new Go types:

* TypeParam: name:String and constraint:Type
* Union:  tidle:Bool (I don't know what this does) and type:Type

Haxe does not support Unions, and does not have constraints for binary operators, field access etc.

The best approach as far as I'm aware would be to send in pull requests to the Haxe compiler for new constraints such as [Constructible](https://api.haxe.org/haxe/Constructible.html) but for all other missing constraints as noted above. Then build a system so that all Go basic types have a list of constraints it supports and for unions simply remove the constraints not shared by all types within the union.

Let me know what you think a good approach on the matter would be, cc @elliott5

**Comment by elliott5** [comment]
I've not used Go generics yet, so I'm on the edge of my knowledge.

On the face of it, the two generic systems (Go & Haxe) seem quite similar. As you say, the differences seem to be in how they define what constrains there are on the instantiated types.

`go2hx` does not need to police the Go rules on type constraints - if a Go program does not compile, it is not valid input to `go2hx`! 

All `go2hx` needs to do is give sufficient information to the Haxe compiler to generate working code.

Haxe does have Unions, but you don't have to specify them explicitly, see - https://haxe.org/manual/type-system-unification-common-base-type.html

However in Go  generic parameter type constraints, if you want to allow all types with a common base type of `X` you need to use the tilde format `~X` (for this Union, the tilde:Bool would be true).

Best to get something simple working, then find where it fails!

Hope that helps, let me know if you need more.

**Comment by PXshadow** [comment]
Here is something tricky I didn't expect, T doesn't return type union of the compile type but rather the type at runtime.

```go
package main

import "reflect"

func main() {
	add(10.2,10.2)
	add(10,11)
}


func add[T int64 | float64 | int](x T, y T) {
	println(reflect.TypeOf(x).String())
}
```
```
float64
int
```

Therefore it's most likely best to overload the function for every type in the union, because as you said go2hx should only care about valid go input code.

**Comment by elliott5** [comment]
I think code generation of overloaded functions (with all the combinations of types) would be a perfectly valid way to provide this functionality.

**Comment by PXshadow** [comment]
I'm sitting on 98 pending changes for the compiler, the rabbit hole is very real.... anyways, overloads are preferable but currently are restricted to only working with inline functions, which means unoptimized  local functions and the same body code being generated x amount of times depending on the type union. I think a mix is preferable, and will switch over to having the macro based approach use overloads when the inline restriction is lifted.

**Comment by elliott5** [comment]
The Haxe compilation process should do dead code elimination to remove unused method functions from the final binary.

**Comment by PXshadow** [comment]
> The Haxe compilation process should do dead code elimination to remove unused method functions from the final binary.

Yes, I mean for the Haxe source code, if the type union had 12 types in it, and the function body had 1k lines it would be 12k lines of code. Perhaps it would still make sense though, I just wish there was a way to share the overload bodies outside of a macro context.

**Comment by PXshadow** [comment]
No issue at the moment with the generic implementation.
