### ISSUE TITLE
Haxe compiler hanging on compilation of generated code

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#97]
When any field/type is used of math/big at the moment, for compiled Haxe code the compiler hangs. Using the ``--verbose`` flag the last typing is ``Typing stdgo.math.big._Big.Big_Fields_._karatsubaSqr``

It's not very practical to look through the entire function without any specifics from the compiler of where exactly the compiler is looping/stopped etc and other information.

```haxe
function _karatsubaSqr(_z:T_nat, _x:T_nat):Void {
        var _n:GoInt = (_x != null ? _x.length : ((0 : GoInt)));
        if ((((_n & ((1 : GoInt))) != ((0 : GoInt))) || (_n < _karatsubaSqrThreshold)) || (_n < ((2 : GoInt)))) {
            _basicSqr((_z.__slice__(0, ((2 : GoInt)) * _n) == null ? null : _z.__slice__(0, ((2 : GoInt)) * _n).__copy__()), (_x == null ? null : _x.__copy__()));
            return;
        };
        var _n2:GoInt = _n >> ((1 : GoUnTypedInt));
        var _x1:T_nat = (_x.__slice__(_n2) == null ? null : _x.__slice__(_n2).__copy__()), _x0:T_nat = (_x.__slice__(((0 : GoInt)), _n2) == null ? null : _x.__slice__(((0 : GoInt)), _n2).__copy__());
        _karatsubaSqr((_z == null ? null : _z.__copy__()), (_x0 == null ? null : _x0.__copy__()));
        _karatsubaSqr((_z.__slice__(_n) == null ? null : _z.__slice__(_n).__copy__()), (_x1 == null ? null : _x1.__copy__()));
        var _xd:T_nat = (_z.__slice__(((2 : GoInt)) * _n, (((2 : GoInt)) * _n) + _n2) == null ? null : _z.__slice__(((2 : GoInt)) * _n, (((2 : GoInt)) * _n) + _n2).__copy__());
        if (_subVV(_xd, _x1, _x0) != ((0 : GoUInt))) {
            _subVV(_xd, _x0, _x1);
        };
        var _p:T_nat = (_z.__slice__(_n * ((3 : GoInt))) == null ? null : _z.__slice__(_n * ((3 : GoInt))).__copy__());
        _karatsubaSqr((_p == null ? null : _p.__copy__()), (_xd == null ? null : _xd.__copy__()));
        var _r:T_nat = (_z.__slice__(_n * ((4 : GoInt))) == null ? null : _z.__slice__(_n * ((4 : GoInt))).__copy__());
        (_r == null ? null : _r.__copy__());
        _karatsubaAdd((_z.__slice__(_n2) == null ? null : _z.__slice__(_n2).__copy__()), (_r == null ? null : _r.__copy__()), _n);
        _karatsubaAdd((_z.__slice__(_n2) == null ? null : _z.__slice__(_n2).__copy__()), (_r.__slice__(_n) == null ? null : _r.__slice__(_n).__copy__()), _n);
        _karatsubaSub((_z.__slice__(_n2) == null ? null : _z.__slice__(_n2).__copy__()), (_p == null ? null : _p.__copy__()), _n);
    }
```

Any help would be greatly appreciated. (not target specific either from what I can tell)

**Comment by elliott5** [comment]
A serious problem, clearly, hitting some internal Haxe limitation. Is there some internal Haxe error code you could view?

The obvious thing would be to reduce the complexity of the generated code in some way, does turning off in-lining improve the situation?

**Comment by PXshadow** [comment]
@elliott5 potentially but I think it would require me to build the Haxe compiler from source which is what I plan to do, since I agree it is a serious problem.

Reducing the complexity of the generated code is a good idea, there is some ways to make the situation much better, but I'm hesitant in case it doesn't change the hanging outcome, I'll try it though, and I'm not sure what in-lining you are referring to (unless you mean all of the in place nil checks)

**Comment by elliott5** [comment]
If rebuilding the Haxe compiler from source gives better error indications, it may be worth it.

Yes, the nil/null checks are what stand out as repeated code ... but I appreciate it may not be easy to replace the approach without significant re-writing. 

But...
What does the following line in the generated code achieve? The result does not seem to be assigned.
```
   (_r == null ? null : _r.__copy__());
```
The matching Go code it was generated from seems to be:
```
	copy(r, z[:n*2])   
```
Is this a code generation error?

**Comment by PXshadow** [comment]
@elliott5 Oh yes it is! Nice catch, oh shoot 😓 I must have removed it as I thought it was a value copy rather then a slice copy. I'll revert back the Go.copy macro function and rename it to avoid confusion as I had for it, thanks!

**Comment by PXshadow** [comment]
Still hanging unfortunately after change, but a great change none the less.
