### ISSUE TITLE
Suffix "_test" for package vs name for testing

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#98]
Files can be incorporated into the compile build packages when the test flag is triggered.

The issue is the ``_test`` suffix for files is built in such a way that it is included into the library package and that causes issues for std library tests because the standard library is not being generated with the ``-test`` flag in mind, and would be preferred for it to be generated as a separate entity and then used in unison. 

For example: math.go with package ``math`` and ``math_test.go`` with package math would generate the file ``golibs/math/Math.hx`` with ``math_test.go`` defs/decls included in. When the test main would be run it would use the ``stdgo`` version not the generated golibs one, and therefore miss important defs for test running.

The quickest fix I see is simply regenerating all of the ``stdgo`` with the ``-test`` flag, Is there a better alternative though perhaps?

Interested to know your thoughts @elliott5

**Comment by elliott5** [comment]
How about generating every library including the `_test.go` files, but with the generated code from those `_test.go` files subject to [Haxe Conditional Compilation](https://haxe.org/manual/lf-condition-compilation.html), say using a `-D GOTEST` flag.

That approach should have no effect on ordinary library use, but allow tests to be run simply by creating a Haxe test-runner program that calls each chosen module test in turn and is compiled using the flag to enable test compilation.

**Comment by PXshadow** [comment]
> How about generating every library including the `_test.go` files, but with the generated code from those `_test.go` files subject to [Haxe Conditional Compilation](https://haxe.org/manual/lf-condition-compilation.html), say using a `-D GOTEST` flag.
> 
> That approach should have no effect on ordinary library use, but allow tests to be run simply by creating a Haxe test-runner program that calls each chosen module test in turn and is compiled using the flag to enable test compilation.

Amazing idea thank you @elliott5 I'll need to build a system to extract and separate out the test package before merging but I really like the idea, I'll begin work on it now.

**Comment by elliott5** [comment]
I was expecting to see a `sort` and a `sort_test` package, but not one called `sort.test`.

I notice that `sort_test.go` includes an `import . "sort"` statement - https://cs.opensource.google/go/go/+/refs/tags/go1.18.1:src/sort/sort_test.go;l=12

Could this be the origin of the mysterious `sort.test` package?

**Comment by elliott5** [comment]
See https://go.dev/ref/spec#Import_declarations for what the `.` means in the import.

**Comment by PXshadow** [comment]
Figured out the test package naming, should be resolved now.
