### ISSUE TITLE
Error: std@put_env at end of each compile

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#99]
I can't catch where this is coming from yet but each compile run the last line before exit is ```Error: std@put_env```

**Comment by elliott5** [comment]
There only seem to be 3 places in the Haxe compiler where an `Error: `+? message can be generated, 
all in `compiler.ml` lines: [358](https://github.com/HaxeFoundation/haxe/blob/development/src/compiler/compiler.ml#L358), 360 & 597.

The `std@put_env` string appears in Neko - https://github.com/HaxeFoundation/haxe/blob/development/src/compiler/compiler.ml#L358

**Comment by elliott5** [comment]
@PXshadow links above corrected.

**Comment by tobil4sk** [comment]
This was an issue with nightly haxelib being incompatible with non-nightly neko, should have been fixed now.

**Comment by PXshadow** [comment]
> This was an issue with nightly haxelib being incompatible with non-nightly neko, should have been fixed now.

Thanks for the info @tobil4sk !
